### PR TITLE
Enable C++17

### PR DESCRIPTION
**Pull request by sbx320**
Note: Not quite done yet, requires premake update for Linux (and Mac? @qaisjp) as well as some update to the internal build pipeline and most likely CI as well

### CODE REVIEW

**Comment by qaisjp** [comment]
> (and Mac? @qaisjp)

Nope, Mac doesn't work yet.

**Comment by qaisjp** [comment]
accidental rebased master pull from upstream?

**Comment by sbx320** [comment]
I have no idea what actually happened.

**Comment by qaisjp** [comment]
> I have no idea what actually happened.

those commits from master aren't the actual commits (different hashes), so if you do `git rebase -i 08c0267` and then replace each `pick` in `pick sha1hashofoldcommit` with `d` (`drop`), then do a `git push --force`, you can get rid of those commits

**Comment by sbx320** [comment]
The entire rebase was very weird, with git telling me I haven't resolved all conflicts (despite `git status` not showing anything. I'll most likely just squash everything together anyway.

**Pull request merged**
