### PR TITLE
Improve ped sync

### PR DESCRIPTION
**Pull request by tederis**
Originally MTA does nothing but send kinematics data and just applies it without any interpolation. So what we can see as a result is twitching among recieved points. This simple commit intended to mitigate these ped's jumps and brings a bit more lighter sync packets.

### CODE REVIEW

**Comment by botder** [comment]
Do you mind uploading a video demonstration of the before/after? Code looks good.

**Comment by tederis** [comment]
Yes, of course: https://youtu.be/UcSOXd9PxhE. There are still some issues with rotation snapping, but I'm intending to solve them. Indeed, MTA has anything to make ped's sync quite better, but I decided to start with these small changes.

**Comment by botder** [comment]
Do you intend to add more to this pull request or leave it as it is?

**Comment by tederis** [comment]
Yes, I want to. The intention of this pull request was to get feedback from the community. From my point of view, any network related decisions are always risky and I want to get know is there any sense to go further or not.

**Comment by qaisjp** [comment]
> Yes, I want to. The intention of this pull request was to get feedback from the community. From my point of view, any network related decisions are always risky and I want to get know is there any sense to go further or not.

Sync improvements are always appreciated. Go forth and conquer!

**Comment by botder** [comment]
@tederis are you going to finish this pull request draft soon?

**Comment by tederis** [comment]
> @tederis are you going to finish this pull request draft soon?

I'll try to finish this in the near future

**Pull request closed without merging**
