### PR TITLE
Fix invincible peds

### LINKED ISSUE #414: Using setElementHealth on a dead ped makes it invincible
**Describe the bug**
The only way to respawn a ped is with setElementHealth, yet after calling setElementHealth on a dead ped, the server returns `true` for `isPedDead`. You can't damage the ped any more even though `ped.health == 100`.

**To Reproduce**
```
crun setElementPosition(localPlayer, 1968, -2033, 13)
srun a = createPed(0, 1967, -2025, 13)
-- Kill the ped
srun isPedDead(a) -- true
srun setElementHealth(a, 100)
srun isPedDead(a) -- true (should be false)
-- Shoot the ped, it won't take damage
```

**Expected behaviour**
@qaisjp said:
> Setting the health of a ped to a `health > 0` should respawn the ped.

**Additional context**
Do this after calling setElementHealth: setElementSyncer(a, true) and the ped will be able to take damage again, but onPedWasted isn't triggered.

From https://bugs.mtasa.com/view.php?id=8790

### PR DESCRIPTION
**Pull request by FileEX**
Fixes #414 

**Bug description**
The only way to respawn a ped is with setElementHealth, yet after calling setElementHealth on a dead ped, the server returns true for isPedDead. You can't damage the ped any more even though ped.health == 100.

**To reproduce**
crun setElementPosition(localPlayer, 1968, -2033, 13)
srun a = createPed(0, 1967, -2025, 13)
-- Kill the ped
srun isPedDead(a) -- true
srun setElementHealth(a, 100)
srun isPedDead(a) -- true (should be false)
-- Shoot the ped, it won't take damage

Now isPedDead returns false after setElementHealth on dead ped. And ped after setElementHealth(ped,100) isn't invicibles, and will got damage.

### CODE REVIEW

**Comment by ArranTuna** [comment]
Looks like you commit some changes in this that were for another PR.

**Comment by FileEX** [comment]
Removed changes from others PR

**Comment by ArranTuna** [comment]
I've tested this PR and well it works but there's an issue. After killing the ped and doing setElementHealth(a, 100) the ped gets back up again but then falls down dead again 1 second later. It's alive state is correct but it acts dead, streaming out and back in shows it as stood up. However if I call setElementHealth a second time the ped stands up correctly. Strange.

**Comment by qaisjp** [comment]
@FileEX have you had a chance to address @ArranTuna's report?

**Comment by FileEX** [comment]
@qaijp Yes, I saw it. I've done a lot of tests and I do not know why this is happening. If the ped is lying on the back, after using SetElementHealth gets up, falls after a second, but always falls on the stomach and vice versa. If he was lying on his stomach, he falls on his back, strange.

**Pull request closed without merging**
