### PR TITLE
Drag and drop files to import them into MTA

### PR DESCRIPTION
**Pull request by CrosRoad95**
This feature basicly adds a new event "onFilesDrop", it is triggered when you drag and drop file onto mta window from any location of your computer. Behind  the scene it using fileOpen, fileRead and fileClose to read content. Event gives you table of all droppped files [`fileName] = content`, fileName does not contain full path, just file name. You can't drop folders ( not implemented ).

```lua
local textures = {}
addEventHandler("onClientRender", root, function()
  for i,v in ipairs(textures)do
    dxDrawImage(200 + i * 128, 200, 128, 128, v)
  end
end)

addEventHandler("onFilesDrop", localPlayer, function(files)
  for fileName, data in pairs(files)do
    outputChatBox(string.format("Dropped file: %s of size: %i", fileName, string.len(data)))
    local extension = gettok (fileName, 2, "." )
    if(extension == "png" or extension == "jpg")then
      local texture = dxCreateTexture(data)
      if(texture)then
        textures[#textures + 1] = texture
      end
    elseif(extension == "txt")then
      outputChatBox("File content: "..tostring(data))
    end
  end
end)
```

how it works in action:
https://www.youtube.com/watch?v=5w5G3snKY1g

Related issues #1953 #2489

### CODE REVIEW

**Comment by Fernando-A-Rocha** [comment]
What about Fullscreen users? Maybe an alternative way for them to pass files to the window? 🤔

**Comment by Vadya963** [comment]
I think you can make it easier ctrl+c and ctrl+v, copied the picture, went into the game and inserted it and call the event onFilesClipboard

**Comment by CrosRoad95** [comment]
> I think you can make it easier ctrl+c and ctrl+v, copied the picture, went into the game and inserted it and call the event onFilesClipboard

had idea to make something like that, clipboard where you get raw string, and second argument would be some kind of rich content of what you copied. For example if you copy paste files you get files names and content, if you copy html you get all tags ect

**Comment by lopezloo** [comment]
Such thing could be useful for script/model/map development but it needs to be implemented carefully IMO.

My suggestions:
1. Add `onFilesDragStart` and `onFilesDragEnd` events which would be called when user starts and stops hovering files over game window. Could be used to draw appropriate UI.
`onFilesDragStart` parameters could have some basic information such as amount of files (and/or folders).

2. Implement creation of modal to confirm user choice asking if s/he really want to upload files (notify user that the dropped file contents and name will be read by the game and can be uploaded to remote server). Add an optional checkbox which allow to skip creation of next modals for current server session. Example:



3. Add informational client console message containing file paths after files being dropped.
Also send similar message if drop was blocked because user disallowed it.

Related issue: #2489

**Comment by CrosRoad95** [comment]
> Implement creation of modal to confirm user choice ...

i will add it if you provide me at least one example from the past of people accidently uploading their files to someones website ( a news article, a website that bait people to upload their computer to their servers )

**Comment by lopezloo** [comment]
> i will add it if you provide me at least one example from the past of people accidently uploading their files to someones website ( a news article, a website that bait people to upload their computer to their servers )

IMO browsers should create similar modal on file drop. I don't know how often such thing happen but it's definitely possible to accidently drop file to wrong window.

**Comment by CrosRoad95** [comment]
i accidently can paste my password on public chat, and what? nothing. if you want to treat people as babies all the time, you can implement such dialog :)

**Comment by PlatinMTA** [comment]
> > Implement creation of modal to confirm user choice ...
> 
> i will add it if you provide me at least one example from the past of people accidently uploading their files to someones website ( a news article, a website that bait people to upload their computer to their servers )

Considering this is similar to #2489, you should prompt the user anyway

**Comment by Shuubaru** [comment]
This is awesome but I agree a confirmation prompt is needed. In that way you can avoid throwing files by accident (yes, it happens) and you can also avoid the client/server to process unwanted files, it's just a QoL feature.

**Comment by CrosRoad95** [comment]
two security improvments i could introduce:
1. make impossible to drag and drop files from user documents and simillar locations 
2. add option in settings that enables all formats ( by default disabled ), by default allow text files, lua scripts, models, .xml files, html files so you can't drop your "cv.doc" by default or any other documents

**Comment by PlatinMTA** [comment]
> 1. make impossible to drag and drop files from user documents and simillar locations

That seems rather unwanted, I would be annoyed if I had a file on my user documents I want to share but I can't because of this

> 2. add option in settings that enables all formats ( by default disabled ), by default allow text files, lua scripts, models, .xml files, html files so you can't drop your "cv.doc" by default or any other documents

This would be cool

>Implement creation of modal to confirm user choice asking if s/he really want to upload files (notify user that the dropped file contents and name will be read by the game and can be uploaded to remote server). Add an optional checkbox which allow to skip creation of next modals for current server session.

But why not this tho?

**Comment by CrosRoad95** [comment]
image
don't want to overengineer it, added a dropdown in settings that let you specify what do you want, by default first option is selected: allow mta specific files only which means: allow formats: ".txt", ".lua", ".luac", ".txd", ".dff", ".col", ".xml", ".json", ".png", ".jpg", ".svg", ".map" ( probably i missed some extensions ).

**Pull request closed without merging**
