### PR TITLE
Fix incorrect model name

### PR DESCRIPTION
**Pull request by Dezash**

### CODE REVIEW

**Comment by qaisjp** [comment]
Does anyone know if this is this a typo on MTA's side or a typo by Rockstar?

**Comment by 4O4** [comment]
@qaisjp actually Rockstar named it **NITESTICK** internally (nitestick.txd, nitestick.dff)

**Comment by qaisjp** [comment]
Hmm, that is what my research said too. Perhaps we should rename it to `nitestick` rather than `Night_Strick`?

Will this cause any issues with _backwards compatibility_?

**Comment by ccw808** [comment]
NIGHTSTICK is used in weapon.dat and gta_sa.exe

Edit: Typo is also in [editor]\editor_gui\client\browser\objects.xml

**Comment by 4O4** [comment]
My personal opinion regarding backwards compatibility: I don't see why would any developer choose to hardcode model name instead of its ID in scripts, and if they did - it is their fault then ;)

**Comment by ccw808** [comment]
If they were both present in this order: `334, "Night_Strick",  334, "Night_Stick",` then:
engineGetModelIDFromName("Night_Strick") returns 334
engineGetModelIDFromName("Night_Stick") returns  334
engineGetModelNameFromID("334") returns "Night_Stick"

**Pull request merged**
