### PR TITLE
Add persist parameter to setElementSyncer

### PR DESCRIPTION
**Pull request by MegadreamsBE**
Related to issue #2923 

Adds a parameter "persist" to setElementSyncer which causes the selected player to always be the syncer of the vehicle/ped/object until the player either leaves the server or setElementSyncer is called again without persist. This parameter is only available if a player is passed and not when passing true/false as the first parameter.

This gives servers more finer control over who syncs which vehicle/ped/object if so desired.

### CODE REVIEW

**Comment by MegadreamsBE** [comment]
[syncer.zip](https://github.com/multitheftauto/mtasa-blue/files/10951457/syncer.zip)

Attached is a resource I used to test this functionality. There are multiple commands synctest1 to synctest7 testing different scenario's. When a player leaves the syncer is reset and default behavior continues. Elements with persistent syncers do not fall through the map even if they are far out of view.

**Comment by CrosRoad95** [comment]
what if persistant syncer left server? what i i'm only syncer ( persistant syncer ) and i left the game?

**Comment by MegadreamsBE** [comment]
> what if persistant syncer left server? what i i'm only syncer ( persistant syncer ) and i left the game?

It'll go back to the default behavior of dynamically figuring out who should be the syncer. Thankfully all I needed to do was disable persist in StopSync as this is already called when a player leaves. When you're the only syncer and leave the game then it'll stop sycning these elements (which is also the current behavior) until someone suitable is in the server

**Comment by MegadreamsBE** [comment]
I did some testing with a second player, here's the results:

- When the syncer is far away the vehicle will not fall through the map or act weird.
- If the syncer from a far distance moves the vehicle into the air (but not close enough to be streaming it) it will fall down on the other players screen but sync back into place once the vehicle is in streaming distance. - This is completely fine
- If the second player touches or enters the vehicle they will become the syncer breaking the persistence. This behavior can easily be changed with some if-statements BUT this behavior is fine as the second player is actively interacting with the vehicle. This can be up for discussion but is fine as-is in my opinion.
- Peds cannot be damaged by the second player unless the syncer is in streamable range.

Nothing seems to be out of the ordinary as everything is in line with the purpose of this persist boolean based on my testing.

**Comment by MegadreamsBE** [comment]
I've added extra checks that ensure that in the scenarios outlined in my previous comment in which the syncer does modify the server will no longer do so. Do note that the player actively driving the vehicle will actually be in charge of syncing but the player set by setElementSyncer will resume doing so after this player leaves.

**Comment by CrosRoad95** [comment]
how about an option to switch to "manual" synchronization? so when change syncer i will never be changed by mta itself?

**Comment by MegadreamsBE** [comment]
In addition to persist you mean? Since that's what this persist parameter already does.

**Comment by CrosRoad95** [comment]
`setElementSynchronizationMode(element, "auto"/"manual")`

**Comment by MegadreamsBE** [comment]
> `setElementSynchronizationMode(element, "auto"/"manual")`

I mean, we certainly could add a completely separate function to control it but I personally do prefer just having a boolean as part of setElementSyncer (as it is a cleaner solution and directly related to setElementSyncer) to control the behavior. But this is something that can be up for discussion.

**Review by botder — APPROVED** [review]

**Pull request merged**
