### PR TITLE
Add matchingDimension param for onPickupLeave

### LINKED ISSUE #846: onPickupLeave+setDimension
onPickupLeave do not detect the dimension change,idk how about interior.

### PR DESCRIPTION
**Pull request by fresholia**
Fixes #846

### CODE REVIEW

**Comment by botder** [comment]
This breaks backwards compatibility and we should only merge it for 1.6

**Comment by sbx320** [comment]
Even for 1.6 this seems like a very significant compat break, since you'd suddenly be able to trigger pickups from other dimensions. To me this seems more of a thing for the API versioning suggestion.

**Comment by Allerek** [comment]
> This breaks backwards compatibility and we should only merge it for 1.6
(Writing this from script perspective, wasnt looking into code)
It shouldnt break compatibility as older script doesnt have that argument in event, so they if they havent had it, it will doesnt make big difference(if parameter order is still same, and MTA Code doesnt brake that compatibility by itself)

**Comment by Allerek** [comment]
> This breaks backwards compatibility and we should only merge it for 1.6

(Writing this from script perspective, wasnt looking into code)
It shouldnt break compatibility as older script doesnt have that argument in event, so they if they havent had it, it will doesnt make big difference(if parameter order is still same, and MTA Code doesnt brake that compatibility by itself)

**Comment by sbx320** [comment]
@Allerek Old resources wouldn't expect pickups to trigger in other dimensions. For example consider a weapon pickup in dimension 1 which gives a player a deagle when leaving the pickup. 
**Old Behavior**:
Players in dimension 0 cannot reach the pickup (onPickupLeave)
**New behavior**:
Players in dimension 0 can reach the pickup. onPickupLeave gets triggered and since I did not check for the dimension, the player gets the weapon.

**Pull request closed without merging**
