### PR TITLE
Add support for driving and being a passenger in client-side vehicles, client-side vehicle damage and animated vehicle entering/exiting through new functions for client-side peds/local players

### LINKED ISSUE #1352: Allow client-side peds to enter/exit client-side vehicles
**Is your feature request related to a problem? Please describe.**
[setPedControlState page on the wiki](https://wiki.multitheftauto.com/wiki/SetPedControlState):
>  **Note**: You can't use enter_exit or enter_passenger on a ped.

_Client-side_ peds can't enter/exit _client-side_ vehicles.

**Describe the solution you'd like**
Allow client-side peds to enter/exit client-side vehicles.

**Describe alternatives you've considered**
\-

**Additional context**
\-

### PR DESCRIPTION
**Pull request by MegadreamsBE**
### Summary
This pull request makes it possible for players to drive client-side vehicles or be a passenger in them (a ped can be scripted to drive the vehicle). Similarly it also makes it possible to damage client-side vehicles.

While Multi Theft Auto always was a mod to allow multiple players to play with each other it has grown into something so much bigger. This PR gives a greater control to server owners (in the end it is up to them to either allow or not allow a player to be desynced from others).

There are enough occasions where you may require a vehicle to be in there (cutscenes for example or being flown from one airport to another in a plane) that other players do not need to see but that, if we want our player to be in there, requires us to create a server-side vehicle instead. This removes that need. Similarly allowing client-side vehicles from taking on damage from weapons and/or driving makes them more useful overall.

Fixes #1352 

## New features
- It is now possible to get into and drive client-side vehicles as a player.
- It is now possible to damage client-side vehicles unless this is disabled through scripting.
- Added various new functions/events for client-side peds listed below.

## New functions [CLIENT-SIDE ONLY]
- **getPedNearestVehicleEntryPoint(ped, checkDriverDoor, checkPassengersDoors)**
  This function returns a valid entry point (number) for the nearest vehicle to the ped/player and the vehicle itself.
- **getPedEnterVehicleTarget(ped)**
  This function returns the vehicle together with the seat and entry point of the vehicle the ped is trying to enter.
- **getVehicleEntryPoints(vehicle)**
  This functions returns all entry points for a given vehicle with the entry point id (starting at 0) as the index and then the coordinates of the entry point.
- **setPedEnterVehicle(ped, vehicle, seat)**
  This function makes a client-side ped enter a client-side vehicle. This function also works on the local player whom can also enter server-side vehicles with it.
- **setPedExitVehicle(ped)**
  This function makes a client-side ped (or the local player) leave their current vehicle.
- **cancelPedEnterVehicle(ped)**
  This function makes a client-side ped (or the local player) stop trying to enter a vehicle.

## New events [CLIENT-SIDE ONLY]
- **onClientPedStartEnterVehicle** - ped is the source.
    This event is triggered when a ped is starting to enter a car. It can be cancelled.
    - vehicle: the vehicle the ped is entering.
    - seat: the seat the ped will be in.
    - door: the door the ped is entering through.
    - jacking: if the ped is carjacking, the ped/local player being carjacked is stored in here.
- **onClientPedStartExitVehicle** - ped is the source.
    This event is triggered when a ped is starting to exit a car (or being carjacked). It can be cancelled.
    - vehicle: the vehicle the ped is entering.
    - seat: the seat the ped is in.
    - door: the door the ped is exiting through.
    - jacker: if the ped is being carjacked, the ped/local player responsible is stored in here.
- **onClientPedEnterVehicle** - ped is the source.
    This event is triggered when a ped has entred a car.
    - vehicle: the vehicle the ped is entering.
    - seat: the seat the ped will be in.
    - jacking: if the ped carjacked, the ped/local player that was carjacked is stored in here.
- **onClientPedExitVehicle** - ped is the source.
    This event is triggered when a ped has exited a car (or was carjacked).
    - vehicle: the vehicle the ped is entering.
    - seat: the seat the ped is in.
    - jacker: if the ped was carjacked, the ped/local player responsible is stored in here.

### TODO
- [x] Add support for damage to cars without requiring the player to enter the car first.
- [x] Add support for ped jacking (client-side only)
- [x] Add function to gracefully enter a car instead of warping (client-side only, players sync).
- [x] Add function to check if a player or a ped is near a car that can be entered and through which door.
- [x] Add support for "onClientVehicleStartEnter", "onClientVehicleEnter", "onClientVehicleStartExit" and "onClientVehicleExit" events.
- [x] Add support for cancelling the entering process of a ped. - **cancelPedEnterVehicle(ped)**
- [ ] Add support for getting the seats you can access through a specific entry point. - **getVehicleSeats(vehicle, entryPointId)**
- [x] Add support for getting all available entry points for a given vehicle. - **getVehicleEntryPoints(vehicle)**
- [x] Add support for receiving the current target vehicle a ped is trying to enter. **getPedEnterVehicleTarget(ped)**
- [x] Properly handle ped jacking (when you carjack from a ped), this currently does not update the status of the ped who still thinks he/she is in the car.
- [x] Properly handle falling off a bike.
- [x] Fix a glitch through which a ped thinks it is inside a vehicle while it is not when forced to run behind the vehicle it is trying to enter.
- [ ] Much needed code cleanup such as bringing the code up to current standards.
- [ ] Fix entry points not always being accurate.

### CODE REVIEW

**Comment by MegadreamsBE** [comment]
Please help by testing this PR to verify that it does not break any existing functionality and is stable. Any ideas to still be added (or existing functionality to be modified) are always welcome.

**Comment by MegadreamsBE** [comment]
Projectiles (from vehicles like rhino/hunter) have been found to still sync. This should probably be fixed before this PR gets merged. The minigun on the hunter however does not sync.

**Comment by MegadreamsBE** [comment]
I know the explosion check is not a 100% accurate but it's very close to that. The only case I know where you could make a legit explosion not sync is when you shoot a rocket into the air and within that time-span manage to get into a client-side vehicle. This requires the door to be open beforehand and is quite neglectable as the chance of this happening is so tiny.

It's still better than client-side vehicle projectile explosions syncing and until we have a better way of knowing the exact cause of a explosion this should do fine.

**Comment by qaisjp** [comment]
Nice work. What does it look like to other players when you're in a vehicle?

**Comment by MegadreamsBE** [comment]
Thanks! To other players it looks like you're sliding around (or floating if in a helicopter/plane). When using certain controls (like "fire") you may perform animations like punching on their screen. It is really up to the server owners though to prevent other players from seeing this. (Although it is funny)

**Comment by FileEX** [comment]
Now if we will use client-side vehicle as argument in triggerSeverEvent, the event don't will be triggered. This PR fix it too?

**Comment by MegadreamsBE** [comment]
No, client-side vehicles can at no point exist on the server nor on the client of another player. It wouldn't make any sense for the vehicle to be allowed as a parameter in this event. It's not a bug.

**Comment by FileEX** [comment]
Sure, but should be show info about this in debug. Because user may don't know why him code don't work and why trigger isn't triggered.

**Comment by MegadreamsBE** [comment]
Fair point, but that should be done in its own pull request. I suggest to open up an issue about this.

**Comment by MegadreamsBE** [comment]
Also tested states in which the ped is blocked from getting into the vehicle or getting out. Both acted the way it should, when a ped tries to get into a vehicle but is unable to the ped keeps on trying (and if you're driving - following the car). 

When exiting the game teleports out the ped if it's blocked from stepping out (can be prevented using the events by the scripters).

Perhaps a future PR could still add setPedCancelEnterVehicle or setPedCancelExitVehicle or something, but setPedAnimation may also interrupt this (yet to be tested).

**Comment by MegadreamsBE** [comment]
Using setPedAnimation it is indeed possible to cancel out trying to enter the vehicle IF you first set an actual animation and cancel out of that. This however makes the ped still believe it is trying to get in and setPedExitVehicle needs to be called after that to return things back to normal. 

Either a setPedCancelEnterVehicle should be implemented or setPedAnimation should automatically cancel the entering of a vehicle and restore its state properly (recommended).

I also found a glitch that can be reproduced as follows:
1. Get in a client-side vehicle.
2. Use setPedEnterVehicle on a client-side vehicle.
3. When the ped opens the door and is about to get in drive backwards AND turn steeply.
4. The ped has abandoned getting in but actually believes it is inside the vehicle.

Will need to address this.

**Comment by MegadreamsBE** [comment]
Bringing this back to a WIP state to implement changes that have been discussed with @qaisjp a few months ago. Said changes have been added to the "TODO". Then there is also the question if there should be a function to check if a ped is trying to enter a vehicle as it is possible for them to abandon this process. This could be done with an event but that would be more chaotic imo.

**Comment by qaisjp** [comment]
>Then there is also the question if there should be a function to check if a ped is trying to enter a vehicle as it is possible for them to abandon this process. 

Something like `entryPoint, seat getPedEnterVehicleTarget(ped)` (not sure about the name)

Does `getPedOccupiedVehicle` return the vehicle if you are still trying to enter it? Otherwise the target vehicle can be included there.

**Comment by MegadreamsBE** [comment]
> Does `getPedOccupiedVehicle` return the vehicle if you are still trying to enter it? Otherwise the target vehicle can be included there.

No, until you are physically inside the vehicle it will return false. I do like the idea of a separate function for this more though as otherwise this could cause some compatibility issues.

**Comment by MegadreamsBE** [comment]
Found a new glitch during my last round of testing. It can be reproduced as follows:

1. Spawn a client-side vehicle & ped
2. Get in the vehicle (as a driver for example)
3. Use setPedEnterVehicle to get the ped to enter onto your seat (carjacking you essentially)
4. Drive away quickly right when the ped is starting to carjack you, cancelling it
5. A few seconds later "network trouble" appears, letting the ped complete the carjack through script afterwards corrects it

**Comment by qaisjp** [comment]
Nice find. #80 *PROBABLY* had the same issue with being carjacked by a ped. Either it's a weird client-side problem (why would this cause a network trouble?) or you're forgetting to fence off a block of code intended for synced vehicles.

**Comment by MegadreamsBE** [comment]
There seems to be a fifth entry point as well, will look into that but for now I have kept it out of the getVehicleEntryPoints function as it overall lacks support inside of MTA anyways.

**Comment by MegadreamsBE** [comment]
The entry points given in the events and when checking your target vehicle are not always 100% accurate, that's due to limitations at this stage. Once again, I will look into this when I add entry point/door support to setPedEnterVehicle in a separate PR, for now they're more of a guidance.

**Comment by MegadreamsBE** [comment]
Will continue my research in the ability to force a ped to use a specific door very soon. It will likely require partially rewriting the logic behind the task that handles this.

**Comment by MegadreamsBE** [comment]
Dropping the functionality that allows you to specify what door you want a NPC or player to use for now. This will be in a different PR. The methods getVehicleEntryPoints and getVehicleSeats will still be made available so that it's possible to manipulate what door will be used using scripts for the time being (ex. making the NPC first walk to the entry point before triggering the setPedEnterVehicle method).

**Comment by MegadreamsBE** [comment]
PR #1748 introduces setPedEnterVehicle client-side which is different from the setPedEnterVehicle introduced in this PR:
`setPedEnterVehicle(ped, [, vehicle = nil, seat = 0 ])`
vs
`setPedEnterVehicle(ped [, vehicle = nil, passenger = false ])`

In which seat is numerical in my PR (as there is one driver seat but multiple passenger seats to choose from) whereas the mentioned PR prefers using a bool which does not give that same control. A solution for this conflict should be found. However I do not see the point of downgrading my function in favor of the one introduced in that PR.

**Comment by qaisjp** [comment]
> However I do not see the point of downgrading my function in favor of the one introduced in that PR

I agree yours is more powerful.

However, we can change the API later as both of these will be merged into the same version of MTA.

What do you think about overloading here?

**Comment by MegadreamsBE** [comment]
> What do you think about overloading here?

Works for me.

**Comment by MegadreamsBE** [comment]
Since I can't really seem to push this PR forwards I might just split up parts of it and introduce them as their own PRs.

**Comment by MegadreamsBE** [comment]
Although... I had forgotten I had dropped support for telling a ped to go to a specific seat. Can someone just give me a kick or something so I finally finish this PR?

**Pull request closed without merging**
