### PR TITLE
Blowfish encryption functions

### PR DESCRIPTION
**Pull request by Kernell**
string blowfishEncrypt( string key, string value )
string blowfishDecrypt( string key, string value );

### CODE REVIEW

**Comment by qaisjp** [comment]
Please fix your tabs

**Comment by Kernell** [comment]
Fixed

**Comment by ccw808** [comment]
Kernell wants to merge 3,714 commits ?

**Comment by Disinterpreter** [comment]
@ccw808 i think it's bug make @Cazomino05

**Comment by Cazomino05** [comment]
I'm working on fixing github authors at the moment, pull requests will break as it is re-exporting the entire tree each time but it's something I want to get right (x86 wasn't showing and he has well over 100 commits).

I'm closing this one just because it's not going to merge properly and will break my fix as it'l overwrite the tree I just fixed.

**Pull request closed without merging**
