### PR TITLE
Add engineSet/GetModelVisibleTime

### PR DESCRIPTION
**Pull request by CrosRoad95**
This functions are responsible for nights object, you can adjust when object disappear/appear

List of nights objects https://github.com/multitheftauto/mtasa-resources/blob/master/%5Beditor%5D/editor_gui/client/browser/objects.xml#L310

Functions:
`timeOn, timeOff = engineGetModelVisibleTime( modelID )` - returns when object disappear/appear, 0,0 if model is incompatible.
`bool engineSetModelVisibleTime( modelID, timeOn, timeOff )` - sets when object disappear/appear
time is between 0 and 23.

Example usage:
- disable disappearing and use this models for your own custom models
- you have club on server, make flashing lights shown when club is open, not randomly, all time like now

Example result: nights lights are visible at day ( between 10 and 12 )
pr

Script that i used
```lua
createObject(9934, -2420.85303, -605.81470, 133.16147)

t = {
    engineSetModelVisibleTime(1337, 10, 12),
    engineSetModelVisibleTime(9934, 10, 12),
    {engineGetModelVisibleTime(1337)},
    {engineGetModelVisibleTime(1338)},
    {engineGetModelVisibleTime(7220)}, -- casino
    {engineGetModelVisibleTime(9934)}, -- night model
    {engineGetModelVisibleTime(9933)}, -- night model
}
outputChatBox(inspect(t))
```

### CODE REVIEW

**Comment by Wolfee-J** [comment]
Would add nearly 10 thousand new usable IDs.

**Comment by 4O4** [comment]
Great piece of work! 

Is it possible to make the model visible for the whole day and night without any break? I assume that if you use the time range from 0 to 23, the object would still invisible for one hour - please correct me if I'm wrong here. 

What about the time range from 0 to 0? Does the game support it on compatible models? 

Also may I suggest a different name for this property? In my personal opinion "model time" is a bit ambiguous... I think some more verbose name like `engineSetModelVisibilityTimeRange`, `engineSetModelVisibilityHours` or something similar would be a bit better at describing what the property is actually responsible for.

**Comment by Woovie** [comment]
I agree with the naming here, I was really confused as to what `engineGetModelTime` might be when first seeing this pop up.

**Comment by CrosRoad95** [comment]
so what is the best name for this function? i also check once again did limit 0-23 is correct

**Comment by qaisjp** [comment]
`engineSetModelVisibleTime` might work.

What is the difference between this function and simply setting alpha to 0/255 during certain hours of the day?

**Comment by CrosRoad95** [comment]
Changed name to `engineSetModelVisibleTime` and `engineGetModelVisibleTime`, when you set hours to `0, 24` object is visible all time. Now if model is incompatible, Get will return 0,24

> What is the difference between this function and simply setting alpha to 0/255 during certain hours of the day?

This property overwrites alpha, even onClientRender with setElementAlpha will not be able to show object if is outside "visible time"

**Comment by qaisjp** [comment]
I think we could maybe remove the ability to change the model's visible time, and just add a feature to make models _always_ visible (irrespective of ingame time).

Visible time can then be implemented in Lua, per each individual object as well!

**Comment by CrosRoad95** [comment]
you can write function that loop all id's and set time 0,24
per model is more customizable

**Comment by CodyJL** [comment]
@qaisjp This would greatly reduce the amount of code needed for something like that.
`-- Tables --
off = {}
nightElements = {}

-- Functions --
function isNightElement(object)
	local id = (getElementID(object) or getElementData(object,'ID'))
	
	if type(data.defintions[id]) == 'table' then
		if tonumber(data.defintions[id].on) then
			nightElements[id] = nightElements[id] or {}
			nightElements[id][(#nightElements[id])+1] = object
			if getLowLODElement(object) then
				nightElements[id][(#nightElements[id])+1] = getLowLODElement(object)
			end
		end
	end
end

function nightElementReload()
	nightElements = {}
	off = {}
	for i,v in pairs(getElementsByType('object',resourceRoot)) do
		isNightElement(v)
	end
	fadeNightElements()
end

function reloadElements()
	if isTimer(timer) then
		killTimer(timer)
		timer = setTimer ( reloadStuff, 2000, 1 )
	end
end

function isWithinTimeRange(start,stop)
	hour = getTime()

	if start > stop then
		return (hour < start and hour > stop)
	else
		return (not (hour < stop and hour > start))
	end
end

function fadeNightElements()
	for i,v in pairs(nightElements) do
		if not tonumber(data.defintions[i].on) then
			NightReload()
		else
			if isWithinTimeRange(tonumber(data.defintions[i].on),tonumber(data.defintions[i].off)) then
				if not (off[i] == 1) then
					off[i] = 1
					for ia,va in pairs(v) do
						if isElement(va) then
							setObjectScale(va,0)
						end
					end
				end
			else
				if not (off[i] == 2) then
					off[i] = 2
					for ia,va in pairs(v) do
						if isElement(va) then
							setObjectScale(va,1)
						end
					end
				end
			end
		end
	end
end

setTimer(fadeNightElements,1000,0)
`
There's the system I use to just handle these, ~70 lines and there are issues associated such as desyncs.

**Comment by Wolfee-J** [comment]
Having a function like this would greatly reduce the amount of code needed. To handle object time properties the script I use consists of around 70 lines of code.

**Comment by forkerer** [comment]
Gotta agree with @CrosRoad95 here, can't see anything wrong with giving people access to that, and it will reduce lua script length by a lot in systems like those.

**Comment by qaisjp** [comment]
alright the API you've proposed will do.

basically my concerns were to do with conflicting resources. if it becomes an issue, we can always implement a modelmanager or something like that as a resource.

**Comment by CrosRoad95** [comment]
you can't see some object at day, this feature let you do this, look at example models: https://dev.prineside.com/en/gtasa_samp_model_id/customsearch/?c%5B%5D=5&s=id-asc&bc=-1&bb=-1&bt=-1&ba=-1

**Review by qaisjp — APPROVED** [review]

**Comment by qaisjp** [comment]
thank you

**Comment by Wolfee-J** [comment]
Doesn't function as expected. Models that already have time cycle data still disappear.

**Comment by qaisjp** [comment]
> Doesn't function as expected. Models that already have time cycle data still disappear.

Can't reproduce this.

```lua
run object = createObject(9934,0,0,5) 
crun engineSetModelVisibleTime(9934,0,24) 
run setMinuteDuration(1)
```

Edit: @StrixG says that it only works in Debug, and I can reproduce this (it does not work in Release)

**Pull request merged**
