### PR TITLE
Add onClientPlayerWeaponSwitch for remote players

### LINKED ISSUE #1141: onClientPlayerWeaponSwitch should trigger for remote players
**Is your feature request related to a problem? Please describe.**
onClientPlayerWeaponSwitch doesn't trigger when weapon slot is changed for remote players.

**Describe the solution you'd like**
It should trigger also for remote players. If possible.

**Describe alternatives you've considered**
At the moment, there's no possibility to detect changes for weapon slot, the only possibility is using loop. (for render usage f.e)

**Additional context**
It would be very nice, if we could detect those changes on client-side by event provided by MTA.
I think this is possible to do, since onClientPlayerWeaponFire triggers for local/remote player.

### PR DESCRIPTION
**Pull request by Woovie**
This brings in the changes by @correaAlex in #1143. Created on behalf of @majqqq

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
I just saw the PR review by @qaisjp. Yeah, `onClientPedWeaponSwitch` is definitely good.

**Review by qaisjp — CHANGES_REQUESTED** [review]
https://github.com/multitheftauto/mtasa-blue/pull/1143#pullrequestreview-374741027

**Comment by patrikjuvonen** [comment]
Going to take over and change this to `onClientPedWeaponSwitch` as discussed, which will add support for peds and players.

**Comment by ricksterhd123** [comment]
@patrikjuvonen is this dead?

**Comment by patrikjuvonen** [comment]
> @patrikjuvonen is this dead?

No, I've had my hands full so haven't done this yet.

**Comment by patrikjuvonen** [comment]
Repository has been deleted, opened a clone at #2181

**Pull request closed without merging**
