### PR TITLE
Add getElementSpeed function

### PR DESCRIPTION
**Pull request by HexonDev**
Based on the useful function. Most people use this rather than get velocity

### CODE REVIEW

**Comment by LosFaul** [comment]
i think it's a bad idea to hardcode something like this
since there are also other speed units
for example there is knots for boats and planes

another point:
i'm also not sure if it's a good practice to hardcode non SI-Units since mph is an imperial speed unit

**Comment by qaisjp** [comment]
Hi, thanks for the pull request.

I'm not convinced this is necessary when [the Lua equivalent](https://wiki.multitheftauto.com/wiki/GetElementSpeed) seems to work perfectly fine.

What's the reasoning for adding this to MTA?

**Comment by HexonDev** [comment]
> What's the reasoning for adding this to MTA?

1. In my opinion, since the MTA does not have a "require” or "import" function, it is simpler than copying and pasting code parts a hundred times where you want to use.

2. Exports are very slow to add an exported function.

**Comment by Pirulax** [comment]
I agree with him.
Exports can be very slow(something which hopefully will be improved with my PR), but to give you exact numbers:
10 000export calls, can take around 80 ms, and now, thats a lot.

And to be honest, who uses `getVelocity`? Everyone needs the speed, why not add it as a default function?

**Comment by Pirulax** [comment]
> i think it's a bad idea to hardcode something like this
> since there are also other speed units
> for example there is knots for boats and planes
> 
> another point:
> i'm also not sure if it's a good practice to hardcode non SI-Units since mph is an imperial speed unit

Thats a good point actually. But since people already use them, why not?

**Comment by Shuubaru** [comment]
> i think it's a bad idea to hardcode something like this
> since there are also other speed units
> for example there is knots for boats and planes
> 
> another point:
> i'm also not sure if it's a good practice to hardcode non SI-Units since mph is an imperial speed unit

since this is mainly used for vehicles, knots should be included too.

**Comment by HexonDev** [comment]
> since this is mainly used for vehicles, knots should be included too.

I added knots (kn) to the speed units

**Comment by LosFaul** [comment]
if this gets accepted or not
but:
please, do not write KMPH but KPH for km/h
for knots use factor: 97.19222454 instead of 180 * 0.539956803

**Comment by LosFaul** [comment]
may make it so, if no string for speed unit is passed
that it returns GTA SA speed unit

**Comment by qaisjp** [comment]
> In my opinion, since the MTA does not have a "require” or "import" function, it is simpler than copying and pasting code parts a hundred times where you want to use.

I'm still not convinced that adding this function to MTA is the solution to that problem, esp. since there are so many different units that users may want to use.

I'm going to close this PR by the end of the week, unless another contributor is convinced this is worth merging?

**Comment by Pirulax** [comment]
I think if they really want to use those special units they want, they can always google up something like "m/s to <my special unit>" and just apply a multiplier to it
The unit thing is there for convenience, and more readable code, but if users want to use some specific units they can always just multiply any of the given units

**Comment by AlexTMjugador** [comment]
In addition to what @qaisjp said, why limit this function to peds, players and vehicles? Objects, projectiles, weapons and even sounds also have velocities (and thus speed), according to this function: [https://github.com/multitheftauto/mtasa-blue/blob/1e2d9ae5683249cac9594e86817897a1546ece69/Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L438](https://github.com/multitheftauto/mtasa-blue/blob/1e2d9ae5683249cac9594e86817897a1546ece69/Client/mods/deathmatch/logic/CStaticFunctionDefinitions.cpp#L438)

Overall, I feel that this function is just a convenience for the what may be the top 10 uses of GetElementVelocity, that by its design will no matter what leave some use cases out, and I don't think that its perceived performance advantage really justifies having one more API to perform the same operation. Right now, to get the speed of an element, we first get the velocity vector, and then compute its length by either manual exponentiation operations or the Vector class (which IMHO is very nice from a readability and mathematical point of view). This PR would add another way, making the Lua API unnecessarily more complex.

If the performance advantage is really that big, then I think that some actual benchmarks comparing real scripts that need to compute a lot of speeds would be interesting to see. I also feel that most script developers just want this function to draw some kind of speedometer on screen, where exporting it for use between resources is not needed (computing an element speed is like two lines of code using the Vector class, and you don't really keep your code much more DRY by exporting it) and maybe they can get away with any performance issue by using a digital speedometer and lowering the velocity sampling frequency. As a wise man once said, _premature optimization is the root of all evil_.

Edit: in case someone misinterpreted the previous quote as against optimizations: I believe there was/is/were/are some PR about optimizing the Vector class performance. In fact, I think that optimizations should aim to make that generic and highly reusable class faster, instead of addressing these individual use cases like this. And AFAIK the Vector class performance can still be improved in some ways, perhaps very noticeably.

**Comment by Pirulax** [comment]
That PR is mine, the vector one.
The best solution to the Vector thing wouldve been to implement it in pure Lua. But afaik it wasn't so any faster really, and reading it would become slower as we'd need to traverse the array.

**Comment by Pirulax** [comment]
Btw, Im not sure if that * 50 for the m/s is accurate
One GTA unit is exactly a meter, but I'm pretty sure velocity uses `precision unit` which is 1 / 16 of a meter, so 6,25 cm. 
[Source](https://gta.fandom.com/wiki/Unit)

But we left it this way, because the useful function had used it like this already.

**Comment by Pirulax** [comment]
Oh and, last time I've tried in-game, Ped and other's returned `0` as their velocity.

**Comment by LosFaul** [comment]
> 
> 
> Btw, Im not sure if that * 50 for the m/s is accurate
> One GTA unit is exactly a meter, but I'm pretty sure velocity uses `precision unit` which is 1 / 16 of a meter, so 6,25 cm.
> [Source](https://gta.fandom.com/wiki/Unit)
> 
> But we left it this way, because the useful function had used it like this already.

since i'm working a lot with setElementVelocity
i can tell you 1/50 is the correct factor for speed units

**Comment by AlexTMjugador** [comment]
> Oh and, last time I've tried in-game, Ped and other's returned `0` as their velocity.

Does it happen with `getElementVelocity` too? If not, I think something inconsistent is going on there.

**Comment by qaisjp** [comment]
@AlexTMjugador comment goes into a lot of detail, and mirrors my thoughts: https://github.com/multitheftauto/mtasa-blue/pull/1554#issuecomment-655078544

> If the performance advantage is really that big, then I think that some actual benchmarks comparing real scripts that need to compute a lot of speeds would be interesting to see.

We've not seen this, so I'm going to go ahead and mark this as decline and close it. I'm, of course, happy to reopen this if we see some useful metrics. Thank you very much for taking the initiative and creating this pull request, @HexonDev :)

**Comment by Pirulax** [comment]
The speed difference is actually pretty big, at least compared to the Lua version of the function on Wiki.
Especially because of #321.
Would you guys agree to add this function, but without hardcoding units?
We could return `m/s`, as thats a SI unit, and can be converted to anything on demand.

**Comment by qaisjp** [comment]
The original version never used OOP https://wiki.multitheftauto.com/index.php?title=GetElementSpeed&direction=prev&oldid=42919

Someone replaced it with OOP in ~~2017~~ 2014: https://wiki.multitheftauto.com/index.php?title=GetElementSpeed&direction=next&oldid=36719

Please feel free to replace the implementation on the wiki with a non-OOP implementation

**Comment by Pirulax** [comment]
Can't argue with that

**Comment by qaisjp** [comment]
In fact, it was @AlexTMjugador that replaced it in *2014

**Comment by LosFaul** [comment]
i personally would just start with returning speed in GTA units
since getElementVelocity also returns speed in GTA units

**Comment by AlexTMjugador** [comment]
> In fact, it was @AlexTMjugador that replaced it in *2014

Good old times when I didn't know what a class was and thought that short-circuiting every check was cool and readable... 😂

Anyway, anybody, feel free to improve that function. I'm sorry if because of it anybody thought that getting an element speed is slower than it needs to be.

**Pull request closed without merging**
