### PR TITLE
Move vendor/lua to a submodule

### PR DESCRIPTION
**Pull request by Pirulax**
I made a PR in which Qais suggested me to use create a repo for our Lua vendor, and do modifications there instead.
This PR implements his idea.
It contains all previous commits back to 2008.

TODO: Test if everything works.

### CODE REVIEW

**Comment by Pirulax** [comment]
Thanks man.. I was getting very annoyed.

**Comment by Pirulax** [comment]
[Discussion over at Discord.](https://discord.com/channels/801330706252038164/802148157152428052/821731568355246080)

**Comment by Pirulax** [comment]
I'll need to rebase this if we decide to merge it

**Comment by patrikjuvonen** [comment]
Let's not do this for Lua at this time.

**Comment by Pirulax** [comment]
Let's do it now, what do you think?
We need submodules for Luau anyways.

**Comment by TheNormalnij** [comment]
There is no benefits from this.
Submodules are good for external dependencies. For internal dependencies they make life harder.
Lua submodule just adds extra step in development:
1. Create PR into lua repo
2. Create PR into mta-blue remove with submodule update

This has no sense. Submodules should be used for external or shared dependencies

**Comment by tederis** [comment]
I would agree with TheNormalnij. The Lua version MTA uses is the internal thing. It is an inseparatable part of MTA that cannot be used in anywhere else.

**Pull request closed without merging**
