### PR TITLE
0009916: update SQLite to 3.24.0

### PR DESCRIPTION
**Pull request by patrikjuvonen**
**Mantis Bug Tracker issue:**
[9916](https://bugs.multitheftauto.com/view.php?id=9916)

Requested initially by @Dutchman101

Our current SQLite version is 3.13.0.

**Test resource:**
[test_sqlite_3_24_0.zip](https://github.com/multitheftauto/mtasa-blue/files/2217713/test_sqlite_3_24_0.zip)

**New in 3.24.0:**
https://www.sqlite.org/releaselog/3_24_0.html

**Since our current version:**
SQLite Release 3.14.2 On 2016-09-12: https://www.sqlite.org/releaselog/3_14_2.html
SQLite Release 3.15.2 On 2016-11-28: https://www.sqlite.org/releaselog/3_15_2.html
SQLite Release 3.16.2 On 2017-01-06: https://www.sqlite.org/releaselog/3_16_2.html
SQLite Release 3.17.0 On 2017-02-13: https://www.sqlite.org/releaselog/3_17_0.html
SQLite Release 3.18.0 On 2017-03-30: https://www.sqlite.org/releaselog/3_18_0.html
SQLite Release 3.19.3 On 2017-06-08: https://www.sqlite.org/releaselog/3_19_3.html
SQLite Release 3.18.2 On 2017-06-17: https://www.sqlite.org/releaselog/3_18_2.html
SQLite Release 3.20.1 On 2017-08-24: https://www.sqlite.org/releaselog/3_20_1.html
SQLite Release 3.21.0 On 2017-10-24: https://www.sqlite.org/releaselog/3_21_0.html
SQLite Release 3.22.0 On 2018-01-22: https://www.sqlite.org/releaselog/3_22_0.html
SQLite Release 3.23.1 On 2018-04-10: https://www.sqlite.org/releaselog/3_23_1.html
SQLite Release 3.24.0 On 2018-06-04: https://www.sqlite.org/releaselog/3_24_0.html

### CODE REVIEW

**Comment by CrosRoad95** [comment]
what's are mainly changes between current and new one?

**Comment by patrikjuvonen** [comment]
There have been various improvements, additions, bug fixes including memory leak fixes, database corruption fixes.
Regarding CPU usage for example: https://www.sqlite.org/cpu.html

It's worth checking the changelogs.

In general we're out of date on that so it would be good to get it updated as there have been numerous bug fixes and improvements and nothing has been deprecated according to the changelogs.

**Review by qaisjp — APPROVED** [review]
Thanks for this. File parity with SQLite library confirmed. Handing the issue over to @Dutchman101 who would like to do further testing.

**Comment by patrikjuvonen** [comment]
Added a test resource to the original post: https://github.com/multitheftauto/mtasa-blue/files/2217713/test_sqlite_3_24_0.zip

**Test results on custom build:**
```
[2018-07-23 05:13:15] ====================================================================
[2018-07-23 05:13:15] Executing [42] v1 tests at [2018-07-23 05:13:15] on [:/test_sqlite_3_24_0_v1.db] file in [test_users_table] table
[2018-07-23 05:13:15] ====================================================================
[2018-07-23 05:13:15] connectToSQLiteDatabaseFileUsingGlobalDatabaseDirectory: success
[2018-07-23 05:13:15] connectToSQLiteDatabaseFileUsingThisResourceDirectory: success
[2018-07-23 05:13:15] createTableIfNotExistsUsingDbExec: success
[2018-07-23 05:13:15] insertValueUsingDbExec: success
[2018-07-23 05:13:15] selectRowUsingDbExec: success
[2018-07-23 05:13:15] insertValueUsingDbExec2: success
[2018-07-23 05:13:15] selectAllUsingDbExec: success
[2018-07-23 05:13:15] updateRowUsingDbExec: success
[2018-07-23 05:13:15] selectRowUsingDbExec: success
[2018-07-23 05:13:15] selectRowUsingDbExec1: success
[2018-07-23 05:13:15] deleteAllUsingDbExec: success
[2018-07-23 05:13:15] dropTableIfItExistsUsingDbExec: success
[2018-07-23 05:13:15] createTableIfNotExistsUsingDbQueryAndDbPoll: success
[2018-07-23 05:13:15] insertValueUsingDbQueryAndDbPoll: success
[2018-07-23 05:13:15] selectRowUsingDbQueryAndDbPoll: success
[2018-07-23 05:13:15] insertValueUsingDbQueryAndDbPoll2: success
[2018-07-23 05:13:15] selectAllUsingDbQueryAndDbPoll: success
[2018-07-23 05:13:15] updateRowUsingDbQueryAndDbPoll: success
[2018-07-23 05:13:15] selectRowUsingDbQueryAndDbPoll: success
[2018-07-23 05:13:15] selectRowUsingDbQueryAndDbPoll1: success
[2018-07-23 05:13:15] deleteAllUsingDbQueryAndDbPoll: success
[2018-07-23 05:13:15] dropTableIfItExistsUsingDbQueryAndDbPoll: success
[2018-07-23 05:13:15] createTableIfNotExistsUsingDbQueryAndDbFree: success
[2018-07-23 05:13:15] insertValueUsingDbQueryAndDbFree: success
[2018-07-23 05:13:15] selectRowUsingDbQueryAndDbFree: success
[2018-07-23 05:13:15] insertValueUsingDbQueryAndDbFree2: success
[2018-07-23 05:13:15] selectAllUsingDbQueryAndDbFree: success
[2018-07-23 05:13:15] updateRowUsingDbQueryAndDbFree: success
[2018-07-23 05:13:15] selectRowUsingDbQueryAndDbFree: success
[2018-07-23 05:13:15] selectRowUsingDbQueryAndDbFree1: success
[2018-07-23 05:13:15] deleteAllUsingDbQueryAndDbFree: success
[2018-07-23 05:13:15] dropTableIfItExistsUsingDbQueryAndDbFree: success
[2018-07-23 05:13:15] createTableIfNotExistsUsingExecuteSQLQuery: success
[2018-07-23 05:13:15] insertValueUsingExecuteSQLQuery: success
[2018-07-23 05:13:15] selectRowUsingExecuteSQLQuery: success
[2018-07-23 05:13:15] insertValueUsingExecuteSQLQuery2: success
[2018-07-23 05:13:15] selectAllUsingExecuteSQLQuery: success
[2018-07-23 05:13:15] updateRowUsingExecuteSQLQuery: success
[2018-07-23 05:13:15] selectRowUsingExecuteSQLQuery: success
[2018-07-23 05:13:15] selectRowUsingExecuteSQLQuery1: success
[2018-07-23 05:13:15] deleteAllUsingExecuteSQLQuery: success
[2018-07-23 05:13:15] dropTableIfItExistsUsingExecuteSQLQuery: success
[2018-07-23 05:13:15] ====================================================================
[2018-07-23 05:13:15] Passed tests: [42]; Failed tests: [0]
[2018-07-23 05:13:15] ====================================================================
```

**Test results on MTA:SA Server v1.5.5-release-13192:**
```
[2018-07-23 05:14:45] ====================================================================
[2018-07-23 05:14:45] Executing [42] v1 tests at [2018-07-23 05:14:45] on [:/test_sqlite_3_24_0_v1.db] file in [test_users_table] table
[2018-07-23 05:14:45] ====================================================================
[2018-07-23 05:14:45] connectToSQLiteDatabaseFileUsingGlobalDatabaseDirectory: success
[2018-07-23 05:14:45] connectToSQLiteDatabaseFileUsingThisResourceDirectory: success
[2018-07-23 05:14:45] createTableIfNotExistsUsingDbExec: success
[2018-07-23 05:14:45] insertValueUsingDbExec: success
[2018-07-23 05:14:45] selectRowUsingDbExec: success
[2018-07-23 05:14:45] insertValueUsingDbExec2: success
[2018-07-23 05:14:45] selectAllUsingDbExec: success
[2018-07-23 05:14:45] updateRowUsingDbExec: success
[2018-07-23 05:14:45] selectRowUsingDbExec: success
[2018-07-23 05:14:45] selectRowUsingDbExec1: success
[2018-07-23 05:14:45] deleteAllUsingDbExec: success
[2018-07-23 05:14:45] dropTableIfItExistsUsingDbExec: success
[2018-07-23 05:14:45] createTableIfNotExistsUsingDbQueryAndDbPoll: success
[2018-07-23 05:14:45] insertValueUsingDbQueryAndDbPoll: success
[2018-07-23 05:14:45] selectRowUsingDbQueryAndDbPoll: success
[2018-07-23 05:14:45] insertValueUsingDbQueryAndDbPoll2: success
[2018-07-23 05:14:45] selectAllUsingDbQueryAndDbPoll: success
[2018-07-23 05:14:45] updateRowUsingDbQueryAndDbPoll: success
[2018-07-23 05:14:45] selectRowUsingDbQueryAndDbPoll: success
[2018-07-23 05:14:45] selectRowUsingDbQueryAndDbPoll1: success
[2018-07-23 05:14:45] deleteAllUsingDbQueryAndDbPoll: success
[2018-07-23 05:14:45] dropTableIfItExistsUsingDbQueryAndDbPoll: success
[2018-07-23 05:14:45] createTableIfNotExistsUsingDbQueryAndDbFree: success
[2018-07-23 05:14:45] insertValueUsingDbQueryAndDbFree: success
[2018-07-23 05:14:45] selectRowUsingDbQueryAndDbFree: success
[2018-07-23 05:14:45] insertValueUsingDbQueryAndDbFree2: success
[2018-07-23 05:14:45] selectAllUsingDbQueryAndDbFree: success
[2018-07-23 05:14:45] updateRowUsingDbQueryAndDbFree: success
[2018-07-23 05:14:45] selectRowUsingDbQueryAndDbFree: success
[2018-07-23 05:14:45] selectRowUsingDbQueryAndDbFree1: success
[2018-07-23 05:14:45] deleteAllUsingDbQueryAndDbFree: success
[2018-07-23 05:14:45] dropTableIfItExistsUsingDbQueryAndDbFree: success
[2018-07-23 05:14:45] createTableIfNotExistsUsingExecuteSQLQuery: success
[2018-07-23 05:14:45] insertValueUsingExecuteSQLQuery: success
[2018-07-23 05:14:45] selectRowUsingExecuteSQLQuery: success
[2018-07-23 05:14:45] insertValueUsingExecuteSQLQuery2: success
[2018-07-23 05:14:45] selectAllUsingExecuteSQLQuery: success
[2018-07-23 05:14:45] updateRowUsingExecuteSQLQuery: success
[2018-07-23 05:14:45] selectRowUsingExecuteSQLQuery: success
[2018-07-23 05:14:45] selectRowUsingExecuteSQLQuery1: success
[2018-07-23 05:14:45] deleteAllUsingExecuteSQLQuery: success
[2018-07-23 05:14:45] dropTableIfItExistsUsingExecuteSQLQuery: success
[2018-07-23 05:14:45] ====================================================================
[2018-07-23 05:14:45] Passed tests: [42]; Failed tests: [0]
[2018-07-23 05:14:45] ====================================================================
```

**Review by Dutchman101 — APPROVED** [review]
Tested and stable, ready for merge I'd say. Thanks @patrikjuvonen

**Comment by qaisjp** [comment]
Excellent. Thanks @dutchman101.

**Pull request merged**
