### PR TITLE
Bring back Discord (updated discord-rpc)

### PR DESCRIPTION
**Pull request by 0x416c69**
I think join system is no longer working (The game won't launch), if you guys can test it I would appreciate it.

I think I will have to RE discord game sdk to find the new method of registering game for join feature. I will implement it under https://github.com/0x416c69/discord-rpc and will update the project here.

Everything else seems to have worked fine. That discord rpc repository is tested by my users (about ~2000-3000 users) and there were no unhandled exceptions from discordrpc.dll.

### CODE REVIEW

**Comment by qaisjp** [comment]
Hi, thank you so much for this PR! How much of this PR reverts f6d1ffe35e1292651043bfc709f4aa577ffcdc83?

If it is based on code pre f6d1ffe35e1292651043bfc709f4aa577ffcdc83, it would be super useful if you force push your branch with a commit tree that starts with a revert of f6d1ffe35e1292651043bfc709f4aa577ffcdc83, that way we don't need to review stuff that we have already approved.

If you're not sure how to do this, I can provide instructions or do it for you.

**Comment by Sobhanhaerizadeh** [comment]
Nice

**Comment by patrikjuvonen** [comment]
This PR should implement https://github.com/multitheftauto/mtasa-blue/issues/1333

**Comment by Dutchman101** [comment]
For a small update on the status of this PR and why it's stuck here, see these posts:

1) [https://github.com/multitheftauto/mtasa-blue/pull/2499#issuecomment-1006022080](https://github.com/multitheftauto/mtasa-blue/pull/2499#issuecomment-1006022080)
2) [https://github.com/multitheftauto/mtasa-blue/pull/2499#issuecomment-1006010375](https://github.com/multitheftauto/mtasa-blue/pull/2499#issuecomment-1006010375) (author's perspective)

**Pull request closed without merging**
