### PR TITLE
Remove unused CText

### PR DESCRIPTION
**Pull request by Pirulax**
As a part of [this list](https://gist.github.com/qaisjp/50b0d8ab4833b77c5b9e0305f974f756) was a function in this class. I figured out this class in unused, so...

### CODE REVIEW

**Review by qaisjp — APPROVED** [review]

**Comment by qaisjp** [comment]
Build doesn't pass because it's still being included in a StdInc.h somewhere

**Comment by Pirulax** [comment]
I usually push it here, and wait for it to compile, as it's barely slower than my PC.

**Comment by qaisjp** [comment]
If you do that please open as a draft or wait until it has built in your branch (https://github.com/Pirulax/mtasa-blue/commits/clangmig/remove-cteXXXt) before creating a pull request. It can be time consuming for a collaborator to look at a pull request that is not actually ready for review.

**Comment by Pirulax** [comment]
Well, with this one I've expected it to be just fine.

**Comment by Pirulax** [comment]
Ready for review

**Review by sbx320 — APPROVED** [review]

**Comment by TheNormalnij** [comment]
Can we use this class to add name for new allocated vehicle? Anyway i will save this code in separate branch

**Comment by Pirulax** [comment]
I dont know, but it says in the code that 
> it's slow

**Comment by TheNormalnij** [comment]
Because it make `strcmp` 512 times for every text

**Pull request merged**
