### PR TITLE
Replace speex with opus

### PR DESCRIPTION
**Pull request by jushar**
Speex was deprecated years ago because opus is in all respects better.

Since this change introduces breaking changes (voice packets are totally different), we have to merge this in a major version.

- [x] Replace portaudio in favour of using BASS for recording
- [ ] Use opus

If anyone has interest in finishing this, feel free to do so!

### CODE REVIEW

**Comment by patrikjuvonen** [comment]
I started working on finishing this a while back at https://github.com/patrikjuvonen/mtasa-blue/tree/libopus but had some memory related crashes at the time, I'll try to look at this one again.

**Comment by prnxdev** [comment]
Can't wait to see this working

**Comment by Dutchman101** [comment]
> Since this change introduces breaking changes (voice packets are totally different), we have to merge this in a major version.

Do you think we can get this ready for 1.6?

**Comment by Wannacry-ops** [comment]
Opus Opus

**Comment by Fernando-A-Rocha** [comment]
🧐

**Comment by botder** [comment]
I am going to close this pull request because it's not being maintained and probably requires a fresh start anyway. Anyone can feel free to pick up the effort and create a new pull request.

**Pull request closed without merging**
