### PR TITLE
Fix CEF crashing on wine

### PR DESCRIPTION
**Pull request by vahook**
See https://github.com/multitheftauto/mtasa-blue/issues/2411 (and also the original issue https://github.com/multitheftauto/mtasa-blue/issues/1000 )

Currently, `CEFLauncher_DLL.dll` is linked against `libcef.dll` **implicitly**. Therefore, `libcef.dll` must be available at the time of loading `CEFLauncher_DLL.dll`. However, contrary to what the implementation in `CEFLauncher_DLL` might suggest, this is achieved by calling `SetDllDirectory` **in the MTA process**, as on Windows `SetDllDirectory` also [affects the children](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setdlldirectorya#:~:text=for%20win32%20processes%20that%20are%20not%20running%20a%20packaged%20or%20protected%20process%2C%20calling%20this%20function%20will%20also%20affect%20the%20dll%20search%20order%20of%20the%20children%20processes%20started%20from%20the%20process%20that%20has%20called%20the%20function.) (and [implicit linking](https://pretentiousname.com/setdlldirectory_inheritance/index.html)). Sadly, wine does not implement this at the moment, hence `CEFLauncher.exe` crashes.

This PR introduces [delay-loading](https://learn.microsoft.com/en-us/cpp/build/reference/delayload-delay-load-import?view=msvc-170), which is a possible solution to the issue. Alternatively, we could wait for a fix in wine.

Also, feedback from other wine players would be appreciated.

### CODE REVIEW

**Comment by jason3855** [comment]
Could you describe how to do that? I don't quite know how to do this loading delay

**Comment by Lpsd** [comment]
This is a pull request to resolve the issue in core code. If you're unsure what this means, then you don't need to worry. It _may_ be available as a fix at some point. Until then, you'll just need to wait @jason3855

**Comment by jason3855** [comment]
Ok!

**Comment by Pirulax** [comment]
We need someone to test this and it can be merged.
@jason3855 If you have a Wine installation to test, you can download it from [here](https://github.com/multitheftauto/mtasa-blue/suites/10407663185/artifacts/514868749)
It's not an official build, so you won't be able to connect to public servers, just a local one.

**Comment by gamelaster** [comment]
@Pirulax I'm playing on Wine, so I will test it within today / tomorrow (I will delete the CEF files which are used as workaround right now).

**Comment by gamelaster** [comment]
Hey @Pirulax , I tried the CI build, sadly, it seems there are some issues, some related to Wine, some seems to be build misconfiguration:
1) loader.dll built by CI can't find `WSCAPI.dll` and fails on it (release loader.dll works fine)
```
0104:err:module:import_dll Library WSCAPI.dll (which is needed by L"C:\\MTA-Test\\mta\\loader.dll") not found
0104:err:module:import_dll Library WSCAPI.dll (which is needed by L"C:\\MTA-Test\\mta\\loader.dll") not found
```
2) After using release loader.dll and ignoring integrity errors, local server is not working.
```
[2023-02-19 15:56:05] [Output] : Error: Could not start local server. [Could not load network library]
```
3) Running MTA Server.exe throws following error:
```
MTA:BLUE Server for MTA:SA

ERROR: 'net.dll' library version is '1.5.9-5.21530.0' (Expected '1.5.9-5.00000.0')

(If this is a custom build,
 1. Set MTASA_VERSION_BUILD in version.h to 21530
 2. Rebuild)


ERROR: Loading network library (net.dll) failed!
Press Q to shut down the server!
```

3) and probably 2) would be possible to fix by building it by myself and configuring it as error says, but 1), I'm clueless how is possible that it works on release, but not on CI build.

**Comment by botder** [comment]
Loader shouldn't depend on wscapi.dll since https://github.com/multitheftauto/mtasa-blue/commit/44ac68b2931e0298b8616f389ba0d4099c746833

**Comment by gamelaster** [comment]
With the help of @botder , the CI build is now working, and can confirm, that this PR works perfectly on my setup with wine8.1-staging in 32-bit bottle.
image

**Comment by gamelaster** [comment]
@botder @Pirulax anything else needed to test before merge? Would be really nice to have this :blush:

**Review by botder — APPROVED** [review]

**Pull request merged**
