### PR TITLE
Radar area very large size is not visible

### PR DESCRIPTION
**Pull request by ZReC**
In answer to:
https://bugs.mtasa.com/view.php?id=8930

See this:
https://drive.google.com/open?id=0BxjQi6_IK2docXFkWkhSOG9FWHM

### CODE REVIEW

**Comment by qaisjp** [comment]
We try not to merge changes like these without understanding what the change does. Can you explain what the boolean represents? And thanks for the PR :)

**Comment by sbx320** [comment]
The flag overrides the check whether the rectangle to draw is within the rectangle with the vertices (1000000.0, 1000000.0) and (-1000000.0, -1000000.0).

**Comment by ZReC** [comment]
So, this boolean is used in the original game executable to draw all the areas revealed in the menu map. Similarly works with the mini map, and not, as might be expected, does not yield poor performance with many charged areas.
Test it.

**Comment by qaisjp** [comment]
Thanks again for the pull request :)

**Pull request merged**
