### PR TITLE
Fix #294: make callRemote return 0 as errno upon successful request

### LINKED ISSUE #294: callRemote will always return a nil errno even if successful
**Describe the bug**
[callRemote](https://wiki.multitheftauto.com/wiki/CallRemote) returns a nil errno although the request was successful. This behavior is not consistent with [fetchRemote](https://wiki.multitheftauto.com/wiki/FetchRemote).

**To Reproduce**
1. Send a request with [callRemote](https://wiki.multitheftauto.com/wiki/CallRemote).
2. Inspect the _errno_ argument provided by the callback function.

**Expected behavior**
CURLE_OK (0) as the errno if the request went through okay (see [error codes](https://wiki.multitheftauto.com/wiki/Template:Error_codes_for_callRemote_and_fetchRemote) on Wiki). If the request did not go through alright then it should return the corresponding error code for that error.

**MTA Client & Server:**
- Multi Theft Auto v1.5.5-release-13959
- Windows 10.0.17134.165

**Additional context**
Initially committed here: https://github.com/multitheftauto/mtasa-blue/pull/271#issuecomment-408574297
Will create a new PR for this.

### PR DESCRIPTION
**Pull request by patrikjuvonen**
**GitHub issue:**
This PR closes #294 

**Summary:**
- Update [callRemote](https://wiki.multitheftauto.com/wiki/CallRemote) to return errno **0** instead of **nil**. Improves consistency between [fetchRemote](https://wiki.multitheftauto.com/wiki/FetchRemote) and [callRemote](https://wiki.multitheftauto.com/wiki/CallRemote).
- Main question is about backwards compatibility. What should we do about it?

### CODE REVIEW

**Comment by qaisjp** [comment]
Dropping from 1.5.6 as this is something we will want to put in a nightly for testing

**Comment by qaisjp** [comment]
Requesting feedback from @Jusonex as I believe you've mentioned something about this once? (?)

**Review by qaisjp — APPROVED** [review]

**Comment by jushar** [comment]
As my feedback was requested:
I cannot estimate the risk of breaking scripts. I'd be fine by merging it and checking whether or not people complain about problems. At the utmost there are maybe a handful of people affected by this, maybe not.

Perhaps it makes sense to announce the possible incompatibility on Discord, if we decide to merge it.

**Comment by qaisjp** [comment]
Proposal:
- announce change in return value during 1.5.7 release
- include some other INFO message in scripts?
- merge this after 1.5.7 has released and observe complaints amongst nightly users
- release change in 1.6

**Comment by patrikjuvonen** [comment]
> Proposal:
> 
> * announce change in return value during 1.5.7 release
> * include some other INFO message in scripts?
> * merge this after 1.5.7 has released and observe complaints amongst nightly users
> * release change in 1.6

I think this sounds fine.

**Comment by qaisjp** [comment]
Ok, unless anyone else feels differently, let's go with that.

I've set the milestone to 1.5.7 so that we don't forget to announce the change / consider the INFO message before we release 1.5.7. 

**DO NOT MERGE THIS PR IN 1.5.7!**

(maybe we should move this proposal to #294 & milestone that instead?)

----

Edit 8th August: I've milestoned this as 1.6 now that we have the "Early announcement of 1.6 changes" issue

**Pull request merged**
