### PR TITLE
Hide encode function's secret key in debughooks

### PR DESCRIPTION
**Pull request by gptrk0**
Prevent to catch secret key, what passed to encode function.
- encodeString
- decodeString
- teaEncode
- teaDecode

### CODE REVIEW

**Review by ccw808 — APPROVED** [review]

**Review by patrikjuvonen — APPROVED** [review]

**Comment by qaisjp** [comment]
Other comments start from arg 0, how come these start from 1 or 2?

**Comment by gptrk0** [comment]
> Other comments start from arg 0, how come these start from 1 or 2?

It's the index of the argument list. Secret key at the 3rd place in encodeString. (index 2, because counts from 0)

**Comment by qaisjp** [comment]
My point is that the other comments include details about the previous parameters, whereas yours skips and starts from the secret parameter. E.g. this exists:

```
{"logIn", {{EArgType::Password, 2}}},                           // player, account, 2=PASSWORD
```

But yours is:

```cpp
{"encodeString", {{EArgType::MaxArgs, 2}}},                     // 2=SECRETKEY, CALLBACK
```

I think it should be something like:

```cpp
{"encodeString", {{EArgType::MaxArgs, 2}}},                     // algorithm, input, 2=SECRETKEY, ...
```

**Review by qaisjp — APPROVED** [review]

**Review by StrixG — APPROVED** [review]

**Comment by patrikjuvonen** [comment]
Thank you for the pull request!

**Pull request merged**
