### PR TITLE
Replace splash.bmp with new image

### PR DESCRIPTION
**Pull request by Fernando-A-Rocha**
Modernizes the splash.bmp image
Wip

### CODE REVIEW

**Comment by Fernando-A-Rocha** [comment]
Draft bcoz this is WIP. Ideas and propositions are welcome :D

**Comment by nekjutsu** [comment]
> Draft bcoz this is WIP. Ideas and propositions are welcome :D

New tiles are too small, hard to see image content. I suggest make the tiles like the original or replace the image inside with something larger in content

UPD: Also the image inside new tiles is low quality, is that 144p lol?

UPD 2: Also the image is mirrored, it's just ugly for me

**Comment by Fernando-A-Rocha** [comment]
> > Draft bcoz this is WIP. Ideas and propositions are welcome :D
> 
> New tiles are too small, hard to see image content. I suggest make the tiles like the original or replace the image inside with something larger in content
> 
> UPD: Also the image inside new tiles is low quality, is that 144p lol?
> 
> UPD 2: Also the image is mirrored, it's just ugly for me

yea the background turned out to be pixelated oops, will find a solution

**Comment by T-MaxWiese-T** [comment]
I like the fact that the new image has more of a 3D effect and the reflections. If the main menu were also designed in this style at some point in the future, it would be consistent.
Whether it should be colored or black and white is a question of style. I would say black and white also goes well with MTA, but in the main menu it is also colored so it is consistent. Then the images in the tiles are of poor quality and overall you can't see much or anything exciting. 
I think the font is fine. Maybe the font should be highlighted with a background color like the old image.

**Comment by Fernando-A-Rocha** [comment]
Drafted a new version @T-MaxWiese-T @nekjutsu @Proxy-99 

what do you guys think about this concept? (see main post)

I know it's a bit ugly, gonna talk with people who understand design

**Comment by nekjutsu** [comment]
> Drafted a new version @T-MaxWiese-T @nekjutsu @Proxy-99
> 
> what do you guys think about this concept? (see main post)
> 
> I know it's a bit ugly, gonna talk with people who understand design

It looks ugly for me (sorry)
I like the original, you can feel the "designer's hand" in it

**Pull request closed without merging**
