### PR TITLE
Increase main menu FPS limit

### PR DESCRIPTION
**Pull request by lopezloo**
Increases main menu (when not connected to any server) FPS limit from 88 to 240. GUI is a lot smoother on higher framerates.

### CODE REVIEW

**Review by Dutchman101 — CHANGES_REQUESTED** [review]
Please record 3 video's of how it looks on different refresh rates: 60Hz, 144Hz and if you can also 240Hz. Move around a few menu's, scroll them and change the position of a few main interfaces like settings GUI and server list, also play the credits slideshow. Now we can do a side by side comparison.

Take them with a physical camera instead of software, we will be looking for adverse effects such as artifacts or excessive blurring. 

Either way i dont think this PR can be merged until weeks after the release of 1.6, because we'll need to have others test the results on older monitors (like actual bricks, not one where you can easily configure refresh rates) in a nightly.

**Comment by lopezloo** [comment]
Thinking about it now, we actually could limit it to monitor Hz and apply higher than 88 FPS limit only if it would make sense.

**Comment by Dutchman101** [comment]
> Thinking about it now, we actually could limit it to monitor Hz and apply higher than 88 FPS limit only if it would make sense.

yes, I agree that's the best approach

**Comment by Olya-Marinova** [comment]
I think this can be implemented in CMainMenu.cpp

**Comment by Dutchman101** [comment]
> Thinking about it now, we actually could limit it to monitor Hz and apply higher than 88 FPS limit only if it would make sense.

@lopezloo If you are ready to do that, please open a new PR

**Pull request closed without merging**
