### PR TITLE
Extending the ColShape class with point checking functionality

### PR DESCRIPTION
**Pull request by tederis**
This commit brings a function _isInsideColShape(colshape theColShape, float x, float y, float z)_ that checks if a 3D point is inside a colshape or not.

### CODE REVIEW

**Comment by CrosRoad95** [comment]
Cool, you should add option to disable collision detection ( for specified colshape or for every colshape `setColshapeDetectionEnabled(bool enable)` will turn on/off collision detection ). And i think there is missing interior and dimension argument.

**Comment by tederis** [comment]
I will add the interior and dimension arguments. But the enabling option is some more difficult because there is new function necessity. The function setElementEnabled(element theElement, bool enabled) is can be more usefull(and more common) for not only colshape purposes, but also it can be a excessively radical novation that the MTA Team will not approve. I'll think about it.

**Comment by prnxdev** [comment]
I'm not sure but is there any alternative to make this working today? Something like creating empty element (via createElement) on position x,y,z and use isElementWithinColshape and after that destroy created element.

**Comment by 4O4** [comment]
Yes, there are workarounds like that but they are very buggy and behaviour
differs between client and server side implementations. I've hit this wall
myself some time ago.

**Comment by WhileAGO** [comment]
I'm creating something which if a object been placed on the map but not inside the ColShape it will get Auto-removed But as they said to me you can't check a static object inside a ColShape and this function isInsideColShape(colshape theColShape, float x, float y, float z) will really help to many code writers.

**Comment by Dezash** [comment]
@CrosRoad95 this can be easily done using the currently available functions. This pull request is good the way it is now.

**Pull request merged**
