### PR TITLE
Refactoring MTA code - Part 1

### PR DESCRIPTION
**Pull request by TracerDS**
Currently most mta's code uses generic `unsigned` types which are platform dependent. `cstdint` header however is (_should_ be) platform independent.
This PR focuses on that irregularity and replaces all `unsigned` (and somewhere `long long`) into the `cstdint` types.

MTA's source code is **huuge**. So there is a gigantic number of changes
Splitting the PR into multiple PR's with the same changes would bring too much troubles

### CODE REVIEW

**Comment by Lpsd** [comment]
Did you manage to compile these changes successfully on any platform, or have you just done a find and replace then submitted a PR?

**Comment by TracerDS** [comment]
> Did you manage to compile these changes successfully on any platform, or have you just done a find and replace then submitted a PR?

Its compiling but Im having some memory violation issues

**Comment by botder** [comment]
Please make these refactorings smaller or concentrate on a single refactoring aspect. Then it's easier to review, merge and test.

**Comment by botder** [comment]
Am going to close this one. You can make refactor PRs, but just make them smaller or more concentrated.

**Comment by TracerDS** [comment]
> Am going to close this one. You can make refactor PRs, but just make them smaller or more concentrated.

Understood

**Pull request closed without merging**
