### PR TITLE
Allow setSoundPosition to be used with file streams

### PR DESCRIPTION
**Pull request by StrixG**
The setSoundPosition function can now be used with file streams and returns false if the position can't be set (e.g. the sound is a live stream or the buffer has not yet reached it).

### CODE REVIEW

**Comment by ArranTuna** [comment]
I tested this and was unable to get it to work using an mp3 file please show test code that shows this PR working.

**Comment by StrixG** [comment]
Test resource: [sounds.zip](https://github.com/multitheftauto/mtasa-blue/files/2729230/sounds.zip)

Video of the test: https://www.youtube.com/watch?v=uup8snl5UQk
Enter `splayurl https://yamamichi.me/1.mp3`, wait until the sound is downloaded and use `spos 100`.
Or just use this code:
```lua
local s = playSound("https://yamamichi.me/1.mp3")
print(setSoundPosition(s, 100)) -- false

setTimer(function ()
    print(setSoundPosition(s, 3)) -- true or false (depends on your internet connection)
end, 3000, 1)

addEventHandler("onClientSoundFinishedDownload", root, function (length)
    print(setSoundPosition(s, 120)) -- true
end)
```

**Review by qaisjp — APPROVED** [review]
Thanks for this @StrixG - your test resource works perfectly. @ArranTuna - if you can sign-off that this works for you now, we can go ahead and merge this.

**Comment by qaisjp** [comment]
@ArranTuna any updates?

**Comment by ArranTuna** [comment]
Works.

**Pull request merged**
