### PR TITLE
Fix swimming speed on higher FPS

### PR DESCRIPTION
**Pull request by ghost**
This patch was authored by nonamenoname. It fixes the problem with swimming speed. I tested it on higher and lower fps, works like a charm.

### CODE REVIEW

**Comment by qaisjp** [comment]
does nonamenoname have a git email / name?

**Comment by ghost** [comment]
He is registered on bugs.mtasa.com. The patch was submitted here: https://bugs.mtasa.com/view.php?id=6125

**Comment by qaisjp** [comment]
Worth mentioning that this is not a full fix: "You still can't swim deep into water in Z coordinate"

**Comment by ghost** [comment]
@qaisjp I'll fix that.

**Pull request merged**
