### PR TITLE
Refactor menu images of ZH-CN

### PR DESCRIPTION
**Pull request by thisdp**
Remove the annoying red outline of the menu images of ZH-CN.
Old:
image

New:
image

### CODE REVIEW

**Comment by Pirulax** [comment]
Why was it there in the first place lol

**Review by Pirulax — APPROVED** [review]
LGTM, but I'll leave it up to someone else to merge.

**Comment by qaisjp** [comment]
these need to be submitted using pootle otherwise the images will get overwritten the next time a translation update happens

**Comment by Lpsd** [comment]
@thisdp Please re-upload via https://pootle.mtasa.com/

**Comment by turret001** [comment]
@thisdp how did you fix this? I just noticed there are red outlines on Turkish menu buttons as well

**Comment by thisdp** [comment]
> @thisdp how did you fix this? I just noticed there are red outlines on Turkish menu buttons as well

just make new ones with the same font

**Comment by turret001** [comment]
ah cool, so the red lines don't matter then, eh?

**Comment by thisdp** [comment]
> ah cool, so the red lines don't matter then, eh?

not a big problem, but it isn't pleasant to eyes

**Pull request closed without merging**
