### PR TITLE
Add support for Pop<const char*> in new parser

### PR DESCRIPTION
**Pull request by Pirulax**
Add support for const char* as argument.

### CODE REVIEW

**Comment by sbx320** [comment]
When would we use this over `std::string_view`/´std::string`?

**Comment by Pirulax** [comment]
Well, rarely, but there are `CStaticFuncDef` functions  / class `methods` that take `const char*`.

**Comment by sbx320** [comment]
Those should be changed then ;). 

`PopPrimitive<const char*>` seems like a bad idea in general, since it does not carry length information.

**Comment by Pirulax** [comment]
That would have to be a general refactor of code to use std::string_view / string where possible.
But I'm not quite sure how that would work out, as game_sa is c++14.

**Pull request closed without merging**
