### PR TITLE
Updated BASS library

### PR DESCRIPTION
**Pull request by Dutchman101**
As recommended by Un4seen studios, as they developed the new release based on some issues we brought forward. Odd sound device states (WASAPI) that have ever plagued MTA with crashes are now (although much less than before we did any previous updating) the only crash figures left, and this is yet another attempt to fix or reduce it.

Also brings some new possibilities as you can see from bass.h diff

### CODE REVIEW

**Comment by qaisjp** [comment]
Do you have a link to the file on un4seen's website?

**Comment by Dutchman101** [comment]
http://www.un4seen.com/stuff/bass.zip
@qaisjp

**Comment by qaisjp** [comment]
The md5sum for bass.dll doesn't seem to match

**Comment by qaisjp** [comment]
it should be `4783e7c0d0005b80673a972e4231a230`.. I think?

**Comment by Dutchman101** [comment]
yeah true, onlinemd5.com is malfunctioning (it never did before). won't use that again in this kind of setting, I know.
will add the change now

**Pull request merged**
