### PR TITLE
setWaterLevel: added bIncludeWorldSeaLevel and bIncludeOutsideWorldLevel

### PR DESCRIPTION
**Pull request by TheNormalnij**
This makes it possible to change the water level outside the game world.

### CODE REVIEW

**Comment by sbx320** [comment]
Is there any particular reason why we'd not just apply it to everything anyway? I think setWaterLevel not applying outside world boundaries is more of a bug rather than a feature.

**Comment by TheNormalnij** [comment]
It makes it possible to replace the whole world with custom water. I would like to make my custom world in height level. This is solution for bugs:
1) "Ghost" world objects after 2 replace.
2) World 2dfx can't be removed. (Like fire at pirates in men's pants)

**Comment by TheNormalnij** [comment]
Can it be added in 1.5.7?
Some issues are fixed. I don't need to drown the world (probably). But setWaterLevel is nice with this.

**Comment by qaisjp** [comment]
Sorry, I accidentally pushed the wrong branch. Using `master` in your fork confused me.

I can't push the fix because now that the PR is closed I don't have perms to access your fork 🤦‍♂ 

There is a copy of your branch here: https://github.com/qaisjp/mtasa-blue/tree/TheNormalnij/master

**Pull request closed without merging**
