### PR TITLE
fix: update col position on attach

### PR DESCRIPTION
**Pull request by Viger74**
Update colshape position on client when it was attached

### CODE REVIEW

**Comment by Necktrox** [comment]
You forgot to add spaces around brackets etc. look at the code above/below your lines.

**Comment by ccw808** [comment]
How does this commit impact on current behaviour?

**Comment by darkdreamingdan** [comment]
I can't see how this would work.  It just sets the position once, and I can't see how it would work when colshapes are attached to moving elements.  Moreover, there's no math here so it wont work correctly with rotating objects (e.g. trying to attach a colshape to the wheels of a car) - offsets are always absolute

**Comment by qaisjp** [comment]
Closing since PR author has not replied within two months.

**Pull request closed without merging**
