### PR TITLE
Remove ref & deref functions

### PR DESCRIPTION
**Pull request by ghost**
This PR removes the `ref` and `deref` lua functions.

I doubt that the function was ever useful and i also think that it's no big deal in removing it entirely as they were never documented on the wiki.

Luxy.c

### CODE REVIEW

**Comment by Pirulax** [comment]
I agree.

**Comment by botder** [comment]
I would prefer a deprecation warning and then substitute the functions with no-op functions.

**Comment by ghost** [comment]
> I would prefer a deprecation warning and then substitute the functions with no-op functions.

~~i thought the same but then i've seen that lua_ref is throwing an error anyway:~~
https://github.com/multitheftauto/mtasa-blue/blob/master/vendor/lua/src/lauxlib.h#L162

**Comment by qaisjp** [comment]
My thought was "But why?" but reading over this, there's probably no reason for it to be exposed.

No default resource uses `ref` or `deref`. I will take a look at community resources.

> i also think that it's no big deal in removing it entirely as they were never documented on the wiki

I like this approach of backwards compatibility — if it's not documented, or if the documentation does not promise certain behaviour, we should be more willing to "break compatibility".

> I would prefer a deprecation warning and then substitute the functions with no-op functions.

Agreed.

**Comment by TheNormalnij** [comment]
Can be used for some hacks between resources, i think.

**Comment by qaisjp** [comment]
> Can be used for some hacks between resources, i think.

Hmm, yes, if you need to refer to a coroutine from another resource you could use `ref` and pass it around (instead of managing your own table).

It seems like a reasonable use case. In that case, I think we should only remove these functions if (future versions of) Lua has them marked as deprecated.

**Comment by ghost** [comment]
Well, sorry for the late reply but how would you for example get that reference back in lua ? I mean you get a number (ref) back from `ref` but how would you actually get for example the table or function holding that ID in LUA ?

Example:

**Resource 1**
```lua
local refID = false

-- exported
function doSomething(func)
	refID = ref(func)
end

function getRef()
	return refID
end
```

**Resource 2**
```lua
addEventHandler("onResourceStart", resourceRoot, function()
	local funcRef = exports.resource1:getRef()
	
	-- how would get the function from refID ?
	
	funcRef()
end)
```

**Comment by qaisjp** [comment]
In your example it would not be possible. The ref can only be deref'd in resource 1.

**Comment by TheNormalnij** [comment]
Interfeace between resources.
[ref_test.zip](https://github.com/multitheftauto/mtasa-blue/files/3638984/ref_test.zip)

**Pull request closed without merging**
