### PR TITLE
Update mtaserver.conf.template

### PR DESCRIPTION
**Pull request by efexc**
I've edited it, including the recent changes (pr #3078) and also added scripts that will start automatically.

### CODE REVIEW

**Comment by sbx320** [comment]
The template is used to fill missing defaults in existing server configs (please don't ask me why this is done in such an odd manner...). 

However resources shouldn't be automatically added to a server config, as those resources might not even be present in the local server installation.

**Comment by TracerDS** [comment]
> However resources shouldn't be automatically added to a server config, as those resources might not even be present in the local server installation.

Not true. All default resources are present if you install mta server. They are also added to server's config regardless if you chose to install them or not.

**Comment by sbx320** [comment]
Yes. However a server owner may decide to not install any resources or remove default resources (and remove them from the mtaserver.conf as well). 

With the change from this PR, the resources would be readded to the mtaserver.conf, which would cause the server to fail.

**Comment by TracerDS** [comment]
Adding resources to config doesnt cause the server to crash or shutdown. It only alerts about lack of resources but you can continue with it.
And the only way to not include resources during install is by building server from source and running property bat file. But thats obviously out of scope.
If the owner doesnt want any resources then there is no issue with removing lines from mtaserver.conf file, if he cares about the messages that is

**Pull request closed without merging**
