### PR TITLE
Add engineResetModelLODDistance function

### PR DESCRIPTION
**Pull request by StrixG**
This function resets the model LOD distance to the default value.

### CODE REVIEW

**Comment by CrosRoad95** [comment]
Please get rid of all changes related to formatting eg.:
image

**Comment by Lpsd** [comment]
I already made a pull request for this a long time ago. I just need to make a quick change as it was waiting on the Lua error issue. See #971

**Comment by StrixG** [comment]
Oh. I didn't notice it, sorry.

**Comment by qaisjp** [comment]
Duplicate of #971

**Pull request closed without merging**
