### PR TITLE
Zoom In/Out key binding fixes

### LINKED ISSUE #524: Zoom in/out binds are inverted
**Describe the bug**
Well, basically in the 'Bindings' tab in 'Settings' the 'Zoom in' and 'Zoom out' bindings are named incorrectly, they should be switched.

Apparently 'Zoom in' is meant to decrease the field of view, whilst 'Zoom out' is meant to increase the field of view, it is like this in Single Player.

**To Reproduce**
Get sniper rifle, aim it, use zoom stuff.

**Expected behavior**
To zoom the right way.

**Screenshots**

**MTA Client (please complete the following information):**
Unstated.

**MTA Server (please complete the following information):**
Unstated.

**Additional context**
From https://bugs.mtasa.com/view.php?id=4781

### PR DESCRIPTION
**Pull request by darkdrifter**
Resolves #524

Hello,

This is my first contribution to any open source project, tried to follow the guidelines and coding style but I may have missed some things. Don't hesitate to tell me if I did.

Threes fixes are included in this pull request:
- Fix for the inverted zoom in/out bindings. For some reason, _CControllerState RightShoulder2_ controls Zoom Out, while the _CControllerState LeftShoulder2_ controls the Zoom In, I don't know if it's the game behavior on PS2.
- Fix for the Zoom In/Out behavior being also controlled by the Weapon Previous/Next key binds. This behavior isn't present in the base game so it shouldn't be in MTA.
- ~~Thanks to the fix just above, we can remove a hack that disconnected Zoom In/Out behavior using mouse wheel to try and fix zoom being applied twice. I think it was actually due to the fact that _Weapon Previous/Next_ was applied first (if bound on the scroll wheel) and them _Zoom In/Out_ gets applied and adds another zoom on top of it. With that hack removed, we can now bind mouse scroll wheel for the zoom. On master if you try to bind the scroll wheel only on the zoom in/out, you'll observe that the zoom isn't working.~~ (moved into #2769)

Don't mind the first two commits, it was a first try to fix the issue that I reverted after I dug up further and found what I think is a better fix.

### CODE REVIEW

**Comment by lopezloo** [comment]
> I think it was actually due to the fact that Weapon Previous/Next was applied first (if bound on the scroll wheel) and them Zoom In/Out gets applied and adds another zoom on top of it.

I haven't tested your PR yet but I have unbinded all keys (via `unbind all` command) except `aim_weapon` and I'm still being able to zoom in/out sniper using scroll wheel. (tested on `v1.5.9-release-21326`)

**Comment by darkdrifter** [comment]
I tried with `unbind all` on `v1.5.9-release-21331` and I can't zoom using mouse scroll until I bind mouse scrolling to `Weapon Next` and `Weapon Previous`
I'm testing in Map Editor in "Full Test" BTW
EDIT: Tried in a online server, same behavior.

**Comment by lopezloo** [comment]
Looks like it actually depends on single player control settings. I have unbinded it in single player and it doesn't work anymore. It shouldn't work like that.

single_player

**Comment by darkdrifter** [comment]
Yeah indeed when I set the mouse scrolling in single player I get a smooth zoom in/out even with everything unbound in MTA. And if I bind mouse scrolling in MTA I get a jerky "double zoom", probably the thing that the hack tried to fix. 
I'll tried on my build with this PR, I don't have the said "double zoom" if I bind the mouse scroll on solo and MTA, though I still have mouse scrolling when I `unbind all` if I have it set in solo. So it's an improvement but there is still something weird going on.

**Comment by darkdrifter** [comment]
I found the issue with the scrolling that caused it to be affected by single player. It seems that GTA SA uses Direct Input to get the scroll wheel value when using mouse scroll wheel on zoom. It's probably to have smoother zoom, as now that I have hooked the zoom value on direct input, the single player no longer affects MTA but the scrolling is a bit harsh.
As I described in the comment where I placed the hook, a better option could be to instead give this data only when we want it (when zoom is bound to scroll wheel in MTA) to retain the proper smooth zoom, but it would require also successfully forcing the game to use this data even when it is not bound in single player, but I haven't looked closely at this option yet.

**Comment by lopezloo** [comment]
That mouse wheel zoom logic is defined in `CCam::Process_M16_1stPerson()`. It calls `CControllerConfigManager::GetMouseButtonAssociatedWithAction(&ControlsManager, PED_SNIPER_ZOOM_IN)`. The question is - why does it seems to be returning something if it's not defined in MTA binds? We need to investigate it more since it would be nice to have smooth zoom.

**Comment by lopezloo** [comment]
I suggest to remove that mouse wheel zoom fix and create seperate PR for that instead.

Related issues:
- #2275 
- #2570
- #515 

Jump bind also triggers zoom in (it doesn't happen in single player).

**Comment by bum8hj** [comment]
> Jump bind also triggers zoom in (it doesn't happen in single player).

This is slightly off-topic, but I believe jumping also forcefully re-enables `aim_weapon` when it's disabled with `toggleControl`.

**Comment by darkdrifter** [comment]
Hello, I reverted the last commit that I will move into a WIP PR that will look into the whole zoom behavior issues (to the best of my abilities).
I don't know how to quickly reproduce issue #2275 or #2570 to see if it's still present with this PR, but it would be nice to know if it fixes them indirectly.
@lopezloo we stop this PR with only this fix then and integrate it with its improvements even if some flaws are still present ?

**Comment by lopezloo** [comment]
> @lopezloo we stop this PR with only this fix then and integrate it with its improvements even if some flaws are still present ?

I just would like to merge fix for inverted controls first. Please restore that zoom check which MTA used to have (and then remove this condition in your other PR).

> This is slightly off-topic, but I believe jumping also forcefully re-enables aim_weapon when it's disabled with toggleControl.

Unable to reproduce that.

**Comment by darkdrifter** [comment]
> Please restore that zoom check which MTA used to have (and then remove this condition in your other PR).

Done ;)

**Review by lopezloo — APPROVED** [review]
Looks good to me. Thank you.

I have slighty edited first post.

**Pull request merged**
