### PR TITLE
Fix SetBuildingPoolSize resets RemoveAllBuildings

### PR DESCRIPTION
**Pull request by TheNormalnij**

### CODE REVIEW

**Review by Fernando-A-Rocha — APPROVED** [review]
Logic LGTM

**Review by ghost — APPROVED** [review]
Looks good 🎉

**Review by tederis — DISMISSED** [review]
LGTM

**Comment by TheNormalnij** [comment]
> LGTM

PR requests review after resolving merge conflicts

**Review by tederis — APPROVED** [review]
It still looks good

**Pull request merged**
