### PR TITLE
Convert CStreaming to use fn pointers instead of asm

### PR DESCRIPTION
**Pull request by Pirulax**

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by fastman92** [comment]
I've taken a look into this.
This pull request puts new bugs to the MTA.
__fastcall calling convention used, where __cdecl should have been used.

By the way, please change  CStreamingSA::GetStreamingInfoFromModelId(ushort id) into this:

CStreamingSA::GetStreamingInfoFromModelId(uint32 id)

**Comment by ghost** [comment]
> __fastcall calling convention used, where __cdecl should have been used.

Yes, it should be __cdecl.

**Comment by Pirulax** [comment]
In my IDB `CStreaming::RequestSpecialModel` uses `__fastcall`.
I won't change `GetStreamingInfoFromModelId` to use `uint`, because it requires quite a few changes which aren't related to this PR.

**Comment by forkerer** [comment]
IDA guesses the calling convention, it often assumes wrong one.

**Pull request closed without merging**
