### PR TITLE
Disable addDebugHook so cheaters have to use brain to hack the server

### PR DESCRIPTION
**Pull request by CrosRoad95**
Removes a goldmine for cheaters, make their life harder.
I know it breaks backwards compatibility with already existing cheats but we can deal with it. 😘

### CODE REVIEW

**Comment by Fernando-A-Rocha** [comment]
Tbh i agree. There's no real legitimate reason to use debug hook on a production server

**Comment by TheNormalnij** [comment]
We can allow `addDebugHook` only in debug builds

**Comment by TracerDS** [comment]
what about lua anticheat with `addDebugHook` used as a core function?

**Comment by Lpsd** [comment]
So, you force cheaters to implement this functionality on their own (or similar alternatives) then what?

**Comment by Xyrusek** [comment]
MTA should give an option to just disable debug hooks and loadstrings in server configuration file, cause in most cases it shouldn't be used on production servers.

**Comment by TracerDS** [comment]
> MTA should give an option to just disable debug hooks and loadstrings in server configuration file, cause in most cases it shouldn't be used on production servers.

Loadstring and debug hooks dont make sense on the server either way. And you cannot disable loadstring on client.

**Comment by Dutchman101** [comment]
Thanks for your suggestion, but it's denied. There are too many custom security solutions that rely on it for the opposite of cheating. We also know that for cheaters themselves, it's not so important to be able to use this; it doesn't offset the legitimate uses of debug hooks at all.

**Pull request closed without merging**
