### PR TITLE
Revert "Add final to all public CPacket inheriting classes (#1790)"

### PR DESCRIPTION
**Pull request by ghost**
There's a new packet crash in nightly. Reverting this commit might fix it.

image

### CODE REVIEW

**Review by qaisjp — APPROVED** [review]

**Comment by Pirulax** [comment]
Can I debug the dump?
I presume I'd need the release symbols which I dont have.

**Comment by ghost** [comment]
> 
> 
> Can I debug the dump?
> I presume I'd need the release symbols which I dont have.

Crash dumps only contain the relevant info regarding the crash. You can see everything you need in the screenshot. If you still need more info, you can ask me.

**Comment by Pirulax** [comment]
Yeah, um I wonder what the other values are?
That is, local variables.

**Comment by ghost** [comment]
> 
> 
> Yeah, um I wonder what the other values are?
> That is, local variables.

In crash dumps from release builds, you can't see all local variables. They get optimized away.

**Pull request merged**
