### PR TITLE
Add clearDebugBox

### LINKED ISSUE #2059: Add clearDebugBox function
**Is your feature request related to a problem? Please describe.**
As I'm restarting my local server very often to test the changes made, my debug box gets filled with informations that I want cleared out at restart. Example: At every restart, the server outputs "Connected to the MySQL database server." to let me know if the server successfully connects to the MySQL. It gets "spammed" if I can say like that.

It will be nice if we can have a function like **clearDebugBox** to clear the debug logs like we have clearChatBox for the chat. This way, we can call the function whenever we want (especially for me in the onResourceStart event).

**Describe the solution you'd like**
Add **clearDebugBox** serverside.

**Describe alternatives you've considered**
We can use **/cleardebug** to clear the debug box but it's annoying to do that on every resource restart.

**Additional context**
Nothing.

### PR DESCRIPTION
**Pull request by fresholia**
Fixes #2059

### CODE REVIEW

**Comment by LVRENT** [comment]
As I understand from there, the **clearDebug** clears the _entire debug box_. So, why not rename the **clearDebug** function to **clearDebugBox**? It will also be good for consistency as there is a **clearChatBox** function for clearing the **entire chat box**.

**Comment by Pirulax** [comment]
There was once a discussion about clearing the console, see [here](https://github.com/multitheftauto/mtasa-blue/pull/215#issuecomment-402567634).
Also, if you look at the code of `CConsole::Clear()`
```cpp
    // Clear the history buffer.
    // This crashes if there is more than one line in the console
    if (m_pHistory)
    {
        m_pHistory->SetText("");
        m_strPendingAdd.clear();
        m_strSavedInputText.clear();
    }
```

**Comment by fresholia** [comment]
I revert the clearConsoleHistory function, I'll open it as a separate PR.

Ready to review.

**Review by Pirulax — APPROVED** [review]
LGTM. Perhaps in some PR you could add this function server-side? Just for consistency.

**Comment by fresholia** [comment]
I'll do.

**Pull request merged**
