### PR TITLE
Add final to all CPacket inheriting classes

### PR DESCRIPTION
**Pull request by Pirulax**
Adding the `final` keyword allows the compiler to "devirtualize" (virtual) calls, aka inline them. 

This is a separate PR, because I'm pretty sure the other PR will blow something up xD

### CODE REVIEW

**Comment by ghost** [comment]
This is really nice.

**Review by ghost — APPROVED** [review]

**Comment by Pirulax** [comment]
Note that I didnt do this manually, but with a simple `ctrl f, alt a`. In theory the compiler should throw an error if I've added a final somewhere I shoudnt have.

**Review by qaisjp — APPROVED** [review]
Thanks

**Comment by Pirulax** [comment]
You're welcome!

**Pull request merged**
