### PR TITLE
Fix getModuleInfo

### PR DESCRIPTION
**Pull request by qaisjp**
It would just complain about giving it a bad type as an argument, even
though you were giving it a perfectly valid string.

### CODE REVIEW

**Comment by ghost** [comment]
Is it possible to use the new argument parser for this function?

**Comment by qaisjp** [comment]
CLuaFunctionDefs needs to inherit CLuaDefs to use the new parser. Should I do that?

**Comment by ghost** [comment]
> 
> 
> CLuaFunctionDefs needs to inherit CLuaDefs to use the new parser. Should I do that?

I don't see any problem with that. Yes. :)

**Comment by qaisjp** [comment]
I've given it a go but it's a too complicated refactor that I think we should not do for 1.5.8.

**Comment by ghost** [comment]
I see. Sure, it can be done after 1.5.8 release.

**Review by ghost — APPROVED** [review]

**Pull request merged**
