### PR TITLE
Fix #521: Network trouble if falling into water while attempting to enter a vehicle

### LINKED ISSUE #521: Network trouble if falling into water while attempting to enter a vehicle
**Describe the bug**
If you fall in water whilst attempting to enter a vehicle, when you reach land again you'll get a short Network Trouble message. This is followed by a warp back to your original position when you first pressed the enter key.

**To Reproduce**
- put a vehicle near a cliff over some water
- attempt to enter it (make sure the auto route will let you fall down in the water)
- swim to the closest land you can stand on

**Expected behaviour**
Not to get network trouble.

**Additional context**
From https://bugs.mtasa.com/view.php?id=7951

### PR DESCRIPTION
**Pull request by Zangomangu**
Fixes #521, abort entering if in water

### CODE REVIEW

**Comment by botder** [comment]
I have investigated the issue and the player doesn't actually stop the task to enter the vehicle when fallen into water.
This patch might cause another issue.

**Comment by Zangomangu** [comment]
The problem is GTA doesnt interrupt the entering task when the player is in water, so this fix aborts it manually like the task is cancelled. What issue are you thinking this could cause?

**Comment by botder** [comment]
Nevermind, I missed the task cancellation in `RemoveFromVehicle`

**Review by botder — APPROVED** [review]

**Comment by botder** [comment]
Thanks for the pull request! I have tested it briefly and it works as intended.

**Pull request merged**
