### PR TITLE
getSoundBufferLength function

### PR DESCRIPTION
**Pull request by StrixG**
Added new function **getSoundBufferLength(sound)** that returns the buffer length (playback length of the downloaded part) of the streamed sound file.

Test resource:
[sounds.zip](https://github.com/multitheftauto/mtasa-blue/files/2527220/sounds.zip)

### CODE REVIEW

**Comment by StrixG** [comment]
Demo video: https://youtu.be/Hag_pmg6ozw

**Comment by qaisjp** [comment]
Do both changes depend on each other?

**Comment by StrixG** [comment]
Not really. I'll move the fix into another PR.

**Review by qaisjp — APPROVED** [review]
Looks good! Thanks for this.

**Pull request merged**
