### PR TITLE
Fix typo in update error message

### PR DESCRIPTION
**Pull request by Xenius97**

### CODE REVIEW

**Comment by botder** [comment]
Can you change it to `An update is currently not available.\n\nPlease check www.mtasa.com` ?

**Comment by Xenius97** [comment]
> Can you change it to `An update is currently not available.\n\nPlease check www.mtasa.com` ?

done

**Review by botder — APPROVED** [review]

**Comment by Fernando-A-Rocha** [comment]
@botder isnt mtasa.com gonna be discontinued and replaced with multitheftauto.com ?

**Comment by botder** [comment]
> @botder isnt mtasa.com gonna be discontinued and replaced with multitheftauto.com ?

Yes, but it doesn't really matter ingame (no SEO there, lol), and it's easier to remember and to type "mtasa.com" for a person

**Comment by Fernando-A-Rocha** [comment]
> > @botder isnt mtasa.com gonna be discontinued and replaced with multitheftauto.com ?
> 
> Yes, but it doesn't really matter ingame (no SEO there, lol), and it's easier to remember and to type "mtasa.com" for a person

ok cool so mtasa.com will still work? :D

**Pull request merged**
