### PR TITLE
Fixed a bug with desynchronization of the values of some fields of the CTickRateSettings structure.

### PR DESCRIPTION
**Pull request by nweb**
Fixes a bug where server configuration fields (ped_syncer_distance and unoccupied_vehicle_syncer_distance) did not affect the game in any way, i.e. the client side used its default values ​​(easy to check with the /sinfo command).

### CODE REVIEW

**Comment by Fernando-A-Rocha** [comment]
Ped syncer distance and unoccupied vehicle syncer distance were not being synced server<->client at all !? 😮

**Review by TracerDS — APPROVED** [review]

**Comment by Proxy-99** [comment]
maybe this related to #375

**Comment by Dutchman101** [comment]
That's quite a big oversight, thanks for the fix!

**Comment by theSarrum** [comment]
> Ped syncer distance and unoccupied vehicle syncer distance were not being synced server<->client at all !? 😮

On the client side this is only used by the /sinfo command.

**Comment by nweb** [comment]
> > Ped syncer distance and unoccupied vehicle syncer distance were not being synced server<->client at all !? 😮
> 
> On the client side this is only used by the /sinfo command.

It cannot be said that these parameters are not used in the private netc.dll

**Pull request merged**
