### PR TITLE
Add dxGetTextSize function

### PR DESCRIPTION
**Pull request by StrixG**
This function retrieves the width and height of a certain piece of text.

Syntax:
```lua
float, float dxGetTextSize ( string text, [float width=0, float scaleXY=1.0, float scaleY=1.0, mixed font="default", bool wordBreak=false, bool colorCoded=false] )
vector2 DxFont:getTextSize ( string text, [float width=0, float scaleXY=1.0, float scaleY=1.0, bool wordBreak=false, bool colorCoded=false] )
```

### TODO
- [x] Fix scaling

### CODE REVIEW

**Comment by Pirulax** [comment]
So we basically draw a freaking string to get it's height? Thats waste of drawcalls which are expensive in dx9

**Comment by StrixG** [comment]
@Pirulax dxGetTextWidth works the same way. I don't know how we can do this another way.
Maybe we should add dxGetTextSize/BoundingBox to reduce drawcalls.

**Comment by ccw808** [comment]
As DT_CALCRECT is specified, only bounds are calculated and there should be no draw calls
https://docs.microsoft.com/en-us/windows/desktop/direct3d9/id3dxfont--drawtext

**Comment by ccw808** [comment]
What is the advantage of dxGetTextHeight over dxGetFontHeight?

**Comment by StrixG** [comment]
@ccw808 dxGetTextHeight can calculate height of dxDrawText with wordBreak = true.

**Comment by qaisjp** [comment]
(What if we did dxGetTextSize and returned a vec?)

**Review by qaisjp — DISMISSED** [review]
Unintended line ending changes must be removed before merge.

**Comment by StrixG** [comment]
dxGetTextWidth counts trailing space characters when calculating the width. dxGetTextSize doesn't do that, cause it's not possible when word wrapping is enabled.
Should we count space characters when using dxGetTextSize without word wrapping?

**Comment by qaisjp** [comment]
we should put a note on dxGetTextWidth saying "this assumes word break is off. Use dxGetTextSize instead"

then the difference (with wordBreak true) is fine

**Comment by dmi7ry** [comment]
Still not merged?

**Review by qaisjp — APPROVED** [review]

**Pull request merged**
