### PR TITLE
Cleanup redundant checks

### PR DESCRIPTION
**Pull request by ArranTuna**
Removed all the redundant checks such as if ( pVehicle ) { .... } else m_pScriptDebugging->LogBadPointer ( luaVM, "vehicle", 1 );

### CODE REVIEW

**Comment by ArranTuna** [comment]
Hmm I don't understand why my setPedStat commits are in this when I created a cleanup branch specifically for the redundant checks.

**Comment by 4O4** [comment]
It is because you commited it to master branch in your previous pull request #106 and you haven't synced your fork's master with upstream (it is recommended to do it before starting any bigger work, details here: https://help.github.com/articles/syncing-a-fork/). The simplest way to fix it is to do interactive rebase in order to drop this single commit from your branch, and then do force push. Pull request should be automatically updated after that. To avoid this complication in the future just remember not to commit to master :)

Good job BTW

**Comment by qaisjp** [comment]
Please remove the other commits from this PR.

**Comment by ArranTuna** [comment]
I don't understand how to delete those commits from this PR.

**Comment by qaisjp** [comment]
Type `git rebase -i HEAD~7` and change the word in front of the commits you want to remove to `drop`.

Then do `git push force`

**Comment by ArranTuna** [comment]
Wow, that actually worked, thank you.

**Comment by qaisjp** [comment]
Thank you! For future commits please write your messages [in good form](http://chris.beams.io/posts/git-commit/#imperative).

**Pull request merged**
