### PR TITLE
Fix for issue #377 (many collisionless objects)

### LINKED ISSUE #377: Many collisionless objects - no way to fix
**Describe the bug**
I'm experiencing a problem with many objects on my server.

I create objects using `createObject`. Some objects have their col/dff/txd replaced, and this works fine.

There are some typical objects which frequently simple don't have any collisions.

**To Reproduce: Test 1**
I found another object that after being replaced with a custom col, loses it's collisions. 

[TestResource.zip](https://github.com/multitheftauto/mtasa-blue/files/2343674/TestResource.zip)

The resource above changes model ID **5323** (wires object) and applies custom files in the order suggested by ccw. Though, after starting the resource and restarting MTA, object ID 5403 loses its collisions.

I added a fix for collisions to object ID 5403 and later the whole Glen Park area became collisionless. If I disable `engineLoadCOL` and `engineReplaceCOL`, said bugs do not appear.

**To Reproduce: Test 2**

[TestResourceBug2.zip](https://github.com/multitheftauto/mtasa-blue/files/2343675/TestResourceBug2.zip)

I've made another test resource, this time it replaces a common building in Idlewood, the Pizza Shop. After starting the resource, do

```
crun setElementPosition(localPlayer, 1849.2609, -1402.8617, 13.3906)
```

You will fall through the road. The 2 objects aren't even related as they are far away. (World model ID of the bugged road: `5498`)

Using `testresourcebug2` I was wondering if there was pattern between model ID that is applied to and model ID that gets bugged, and it turns out that there is.

That resource applies a mod to `5418` and then `5498` becomes collisionless. That's a `+80` model ID difference.

So then I tried applying the same mod to `5419` and then... `5499` became collisionless. That's `+80` model ID difference again.

Then I tried `1257` to see if `1337` was bugged. It wasn't, this could be because `1257` is a destroyable bus stop, so I will check a solid object.

Tried a mod on `10308` and `10388` (both were buildings) didn't become bugged.

Tried `5400` and `5480` became bugged, so 3 times out of 5 it was `+80` model ID that became bugged.

**Expected behavior**
All replaced collisions should work.

**Additional context**
It's not a script problem, when I go join another server, it still occurs.

Typically about 30% of players have the 'problematic' collisionless objects. Other players can play without any problems. When this starts to happen, it keeps bugging until you restart MTA.

From https://bugs.mtasa.com/view.php?id=8012. Lots of discussion there.

### PR DESCRIPTION
**Pull request by samr46**
I also suffering from this issue #377 for a few years now (dozens collisionless objects due replacement of some models in game).

It looks like CFileLoader_LoadCollisionFile_Mid hook causing this problem. We don't need to skip loading GTA collision model if we have replaced it. It's unnecessary because SetColModel is called.

I didn't remove this hook for now (just commented installation). It needs some testing. It would be really good if somebody else with these problems could confirm the fix and that collision replacement works properly.

Also TestResourceBug2.zip (object: 5418) from Issue description always causes this problem (at least for me).

This PR closes #377

### CODE REVIEW

**Comment by ccw808** [comment]
[CFileLoader_LoadCollisionFile_Mid was added here](https://github.com/multitheftauto/mtasa-blue/commit/45905e202ff4da2275a66d818f0f2d1c6420f644) to 'Fix custom object collisions getting randomly reset'
Will that problem not happen now?

**Comment by samr46** [comment]
I tested it with custom objects too and never noticed any problem. But if it's random issue and it was a fix then technically problem should return. This is why it needs more testing.

CFileLoader_LoadCollisionFile_Mid calls on object streamIn. First i thought that it would reset model to original so i tried to stream out / in and it worked fine in all cases (different custom and world objects). 
Maybe there is some specific way to reproduce this old bug?

**Comment by Einheit-101** [comment]
I suggest implementing it in the latest nightly and i will test if any collision issue appears until i die. Because i suffer a lot.

**Comment by ArranTuna** [comment]
The bug that has caused us such grief, can be fixed by "//"? :/

Same as Einheit, put in latest nightly and it will be tested thoroughly.

This bug has prevented us from adding many new objects that we have wanted to add, so as well as fixing a bug that causes problems for players every day this will open up whole new possibilites.

**Comment by samr46** [comment]
Well i don't want to remove this hook and dependencies completely for now. "//" should be enough for testing.
On my servers i added fake collisions to cover these holes. But this is really annoying and doesn't solve all problems.

Like @ccw808 mentioned this hook was added for a reason. I can't reproduce this old bug to test everything properly so there is a chance that the old problem can come up due this solution.
Anyway i think it's worth a try. I already tired of reports about collisionless objects.

**Comment by ccw808** [comment]
How to check old bug fix:
Code: 
- Change `OnMY_CFileLoader_LoadCollisionFile_Mid` to return false and also print a message showing which collision model is being loaded

In game:
- Replace a collision model with something vastly different (to make it easier to tell if the collision has been reset back to the original)
- Move about until the message saying GTA has reloaded the collision model
- Check collision has not been reset

**Comment by ccw808** [comment]
How to check old bug fix:
Code: 
- Change `OnMY_CFileLoader_LoadCollisionFile_Mid` to return **TRUE** and also print a message showing which collision model is being loaded

In game:
- Replace a collision model with something vastly different (to make it easier to tell if the collision has been reset back to the original)
- Move about until the message saying GTA has reloaded the collision model
- Check collision has not been reset

**Comment by ccw808** [comment]
If the old bug can't be reproduced, then we should merge this for general testing

**Comment by samr46** [comment]
I re-checked it several times. Everything looks good.
Hook and all relevant code is removed. We can merge this for general testing.

**Review by ccw808 — APPROVED** [review]
Looks good to merge

**Comment by Brian9221** [comment]
I've tested this bug fix this morning, seems that everything is fine and without bugs, finally! :)

Stream in/out: Works extremely well, no collisions bugs on replaced models
Restarting resource with obj streamed in: It is replaced without bugs

I hope this important fix is implemented as soon as possible.

**Comment by Einheit-101** [comment]
I am very sorry to say this, but i have discovered random collisionless objects after testing this for a while now, the difference is that we cannot reproduce it anymore with the test resource. Can someone else confirm? 

https://i.imgur.com/SLpeuJW.png

**Comment by Brian9221** [comment]
I have tested that object on an heavily modded server and it doesn't appear as bugged. Maybe it's your script interfering?

**Comment by Einheit-101** [comment]
No, it appears random, you cannot reproduce it. On another day some other objects will be bugged. I replaced many collisions on my server and the more you replace, the higher the chance for a bug.
BUT it is not as bad as before, it seems a lot better.

**Comment by samr46** [comment]
I can't confirm this. I use this object for different elevators for a long time. Players use it every day.

Some statistics from my servers:
~400 replaced collisions in the gamemode.
Before the fix: 2-7 reports about collisionless objects on the map per day.
After the fix: 0 reports.

**Comment by Wolfee-J** [comment]
Does this fix the bug with SA objects loosing collisions?

**Comment by ccw808** [comment]
@Einheit-101 Set **Advanced->Streaming** memory to **Min** and see how that affects this issue

**Comment by ccw808** [comment]
@Einheit-101 Set **Advanced->Streaming** memory to **Min** and see how that affects this issue

**Pull request merged**
