### PR TITLE
Add compact argument for toJSON from ID 0008848

### PR DESCRIPTION
**Pull request by Audifire**
Edits the following function server-/client-side:
string toJSON ( var value[, bool compact = false] )

compact : A boolean representing whether the json string will be output without white spaces. To remove white spaces, use true. White spaces will be inserted per default.

Screenshot:
http://1drv.ms/1Is2IGF

### CODE REVIEW

**Comment by qaisjp** [comment]
Haven't tested this yet, but could you add error logging? The second argument, theoretically, could take any value right now.

**Comment by Audifire** [comment]
I tested, with any argument and MTA didn't care about it. But now it's more beautiful with error logging and I fixed it.

**Comment by qaisjp** [comment]
Please fix the author of your latest commit using a rebase and **force push** (sorry, just a personal pet peeve of mine).

I think `git commit --amend --reset-author` will work, if you're using the command line.

**Comment by Audifire** [comment]
Done ;) Don't know, why that happened

**Comment by qaisjp** [comment]
nice work, sorry for the late merge, was too busy to test :)

**Comment by Audifire** [comment]
No problem. Better testing it before merging. :D Thank you.

**Pull request merged**
