### PR TITLE
Added isResourceArchived function serverside

### PR DESCRIPTION
**Pull request by Gothem**
Added isResourceZip function:

bool isResourceZip ( resource )

also works with OOP:

method: isZip()
variable: .zip

### CODE REVIEW

**Comment by qaisjp** [comment]
Please rename to `isResourceArchived`

**Comment by Gothem** [comment]
done

**Comment by qaisjp** [comment]
Thank you for your pull request :)

**Review by qaisjp — APPROVED** [review]

**Review by jushar — APPROVED** [review]
Looks good to me too.

What use cases do you imagine for this function?

**Comment by Gothem** [comment]
I have some problems with achieved resources when trying to edit some files. so it could help me to check if the problem is going to happen beforehand.

**Pull request merged**
