### PR TITLE
Fixed #3363 - added `resourceName` as global variable

### PR DESCRIPTION
**Pull request by TracerDS**

### CODE REVIEW

**Comment by Dutchman101** [comment]
Nice, please describe what the problem was, though

**Comment by Dutchman101** [comment]
Both you and Nico submitted a fixed PR at the exact same time (lol)

Code reviews and (self-)feedback should determine which of the 2 PR's is ideal, and to save us time, also please add details on what the problem was and how you fixed it; there's no specific "fix" commit.

Tracer's PR: https://github.com/multitheftauto/mtasa-blue/pull/3530
Nico's PR: https://github.com/multitheftauto/mtasa-blue/pull/3531

**Comment by ghost** [comment]
This pull request does not restore the intended functionality of the original pull request, there are now two open and mine includes the rest.

**Comment by TracerDS** [comment]
@Nico8340 You are the original owner of the PR. You may be the honoured one to fix it :)

**Comment by ghost** [comment]
> You are the original owner of the PR. You may be the honoured one to fix it :)

I'm okay with it, thanks.
I wrote the previous comment just fyi.

**Pull request closed without merging**
