### PR TITLE
Fix ability to move server-side vehicles that are far away from the player

### LINKED ISSUE #3389: Client-side setElementPosition syncs for server-side vehicles
### Describe the bug

As in title, it doesn't happen for other element types. It doesn't account whether player is syncer of vehicle. The way to prevent it is to use:
```lua
setElementSyncer(vehicleElement, false, true)
```
And set syncer manually when needed.

### Steps to reproduce

```lua
-- server

local vehicleElement = createVehicle(434, 0, 0, 3)

setElementID(vehicleElement, "testVeh")

function checkVehiclePosition()
	local vehX, vehY, vehZ = getElementPosition(vehicleElement)

	iprint(vehX, vehY, vehZ)
end
setTimer(checkVehiclePosition, 500, 0)

-- client

local playerX, playerY, playerZ = getElementPosition(localPlayer)
local vehicleElement = getElementByID("testVeh")

setElementPosition(vehicleElement, playerX, playerY, playerZ)
```

### Version

Multi Theft Auto v1.6-release-22390

### Additional context

Ideally, it shouldn't affect server created vehicles at all. At the very least it should be limited to syncer only.

### Relevant log output

_No response_

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by MegadreamsBE**
fixes https://github.com/multitheftauto/mtasa-blue/issues/3389

Adds extra checks to ensure that players cannot use setElementPosition client-side to move vehicles that are far away from them. Essentially closes loopholes that made it possible for players to become the syncer of said vehicles.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good to me 🚀

**Comment by Lpsd** [comment]
I think it would be good to make `MAX_CONTACT_SYNC_RADIUS` value configurable via the Lua API

**Comment by MegadreamsBE** [comment]
> I think it would be good to make `MAX_CONTACT_SYNC_RADIUS` value configurable via the Lua API

In that case it'd probably be better to link it with the syncer radius and make them configurable together. On its own there's not much of a reason to be able to configure this radius

EDIT: Adds the ability to disable it which is actually pretty useful, I stand corrected and thus implemented it

**Review by ghost — APPROVED** [review]
Looks good 🎉

**Comment by MegadreamsBE** [comment]
> I think it would be good to make `MAX_CONTACT_SYNC_RADIUS` value configurable via the Lua API

Added a configurable server setting for it. You can configure it as follows during runtime:
`setServerConfigSetting('vehicle_contact_sync_radius', 30)`

Which should satisfy this.

**Comment by haron4igg** [comment]
Just to be sure...

If client will set position for vehicle locally - will car appear locally to him?
If so - when player will enter the car - it will be forcely synced to new location anyway?

**Comment by MegadreamsBE** [comment]
> Just to be sure...
> 
> If client will set position for vehicle locally - will car appear locally to him? If so - when player will enter the car - it will be forcely synced to new location anyway?

If you're not the syncer, even if the vehicle appears to be near you on your client, you cannot enter it. Instead attempting to the enter the vehicle will reset its position to the position stored on the server. It has always been like this and the PR does not change that.

**Review by Lpsd — APPROVED** [review]
LGTM!

**Comment by Lpsd** [comment]
Thanks for this PR, please update https://wiki.multitheftauto.com/wiki/SetServerConfigSetting and https://wiki.multitheftauto.com/wiki/Server_mtaserver.conf where necessary.

**Pull request merged**
