### PR TITLE
Add getAccountID & getAccountByID

### PR DESCRIPTION
**Pull request by emre1702**
Add getAccountID & getAccountByID for the creator of this feature-request:
https://bugs.mtasa.com/view.php?id=9562

int getAccountID ( account theAccount )
Account getAccountByID ( int ID )

### CODE REVIEW

**Comment by Jusonex** [comment]
In what contexts would you need this function?

**Comment by jushar** [comment]
Could you please fix the merge conflicts (launching `utils/win-apply-clang-format.bat` once might fix it)?
I'll merge it then.

**Comment by Dezash** [comment]
@Jusonex I need this function to be able to reference accounts in other databases. Doing this by username is inconvenient due to the fact that account names are sometimes changed.

**Comment by emre1702** [comment]
@Jusonex Fixed it manually

**Comment by Dezash** [comment]
@Jusonex you didn't forget about this, did you?

**Comment by jushar** [comment]
Thanks for the patch!

Squash-merged in https://github.com/multitheftauto/mtasa-blue/commit/6331f547bab5253446dd96a70ea752a951854d76

**Pull request closed without merging**
