### PR TITLE
Implement #1916: Make client-side setVehicleHandling to work on vehicles created server-side

### PR DESCRIPTION
**Pull request by Grafu**

### CODE REVIEW

**Comment by Dutchman101** [comment]
This PR probably needs to be closed as per the below comment:


"I agree with you but this is too much effort for me. So I give up at this point. Good luck"

_Originally posted by @Grafu in https://github.com/multitheftauto/mtasa-blue/discussions/1916#discussioncomment-230443_

.. in response to a discussion about the desyncs this would bring

Will close if there's no other feedback (or more opinions regarding the 'desync' discussion) soon

**Comment by LosFaul** [comment]
i think we should handle it diplomaticly

i could open a new issue based on this PR after it would be merged
which would be about extending setVehicleHandling for localPlayer controlled vehicle with sync option

what you guys think?

**Comment by botder** [comment]
Adding sync to that would require a server trip to avoid desync and at that point you could've used the serverside function in the first place. I am against this pull request unless somebody has a better idea.

**Comment by Fernando-A-Rocha** [comment]
> Adding sync to that would require a server trip to avoid desync and at that point you could've used the serverside function in the first place. I am against this pull request unless somebody has a better idea.

As I mentioned on the #custom-model-ids channel, intentional desync is not a problem, it is up to the developer and you can easily make "sync" by having all clients set the same handling on X vehicle. This usecase is necessary for engineRequestModel vehicles to work properly with custom handling as their model is changed (setElementModel) clientside and this already causes desync.

Thank you for the additional considerations.

**Comment by Fernando-A-Rocha** [comment]
> Adding sync to that would require a server trip to avoid desync and at that point you could've used the serverside function in the first place. I am against this pull request unless somebody has a better idea.

@botder 
Please re open this PR and consider merging it. There is no need for sync here, for the same reason as there is no sync in setElementModel when it changes a server-created element's model on a client.

**Comment by PlatinMTA** [comment]
>
> @botder 
> Please re open this PR and consider merging it. There is no need for sync here, for the same reason as there is no sync in setElementModel when it changes a server-created element's model on a client.
> 

The current solution is pretty bad (ask the server to set the handling after the client loads the model for example).

Having this function work like rocha asks would help quite a lot.

**Comment by Xenius97** [comment]
This could be a security issue, i don't recommend to merge it to master. With lua injection you can troll servers by modifying vehicle handling (eg. on race servers).

**Comment by botder** [comment]
With Lua injection you could also give your own vehicle more velocity/acceleration before the merge.

**Pull request merged**
