### PR TITLE
Add showCol, isShowCollisionsEnabled, showSound, isShowSoundEnabled for devs

### LINKED ISSUE #1722: Make functions for developer commands
**Is your feature request related to a problem? Please describe.**

It's always annoying having to manually type commands like /showcol, /showsound, ...

**Describe the solution you'd like**

it would be cool if there would be functions to enable this developer features as alternative to the commands
like showcol(), showsound(), ....
with counterparts like isShowcolEnabled(), ....

**Describe alternatives you've considered**

executeCommandHandler does not work since all hardcoded commands are disabled for this

### PR DESCRIPTION
**Pull request by fresholia**
Fixes #1722

### CODE REVIEW

**Review by Pirulax — CHANGES_REQUESTED** [review]
CStaticFunctionDefs shoudn't be used with the new parser. Feel free to move the implementation (from CStaticFunctionDefs) to the LuaDefs file.

**Review by Pirulax — APPROVED** [review]
lgtm.

**Comment by Pirulax** [comment]
Have u tested it?

**Comment by fresholia** [comment]
> Have u tested it?

Yes.

**Review by patrikjuvonen — APPROVED** [review]
Thanks, looks good.

**Comment by patrikjuvonen** [comment]
Please add documentation on Wiki for these functions.

**Pull request merged**
