### PR TITLE
Function setPedWearingJetpack

### PR DESCRIPTION
**Pull request by Dezash**
setPedJetPack(ped thePed, bool state)
OOP: ped:setJetPack(bool state)

Two functions for the same purpose (givePedJetPack and removePedJetPack) isn't very convenient. Devs should consider deprecating them. I didn't do that because there seems to be no proper way to /upgrade old scripts as setPedJetPack requires an extra argument.

### CODE REVIEW

**Comment by qaisjp** [comment]
Merging this will need some thought.

If you want to submit a pull request to have `ped.jetpack = bool`, I can merge that straight away.

If you would like to do that, see `ped.vehicle`:

- [variable declaration](https://github.com/multitheftauto/mtasa-blue/blob/5ca6e659d03489e23738a7e265b18e4e0984c731/Server/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp#L161)
- [implementation](https://github.com/multitheftauto/mtasa-blue/blob/5ca6e659d03489e23738a7e265b18e4e0984c731/Server/mods/deathmatch/logic/luadefs/CLuaPedDefs.cpp#L1401)

**Comment by qaisjp** [comment]
Apologies if I wasn't clear! If you can add `ped.jetpack` (and only `ped.jetpack`) to _a different_ pull request, I can merge that pull request straight away.

**Comment by Dezash** [comment]
Why? Not everyone does OOP. This PR makes it possible to control JetPack in 3 different ways.
```
addCommandHandler("jp", function(thePlayer, _, state)
	setPedJetPack(thePlayer, state == "true")
	print(doesPedHaveJetPack(thePlayer))
end)

addCommandHandler("jpvar", function(thePlayer, _, state)
	thePlayer.jetpack = (state == "true")
	print(thePlayer.jetpack)
end)

addCommandHandler("jpmethod", function(thePlayer, _, state)
	thePlayer:setJetPack(state == "true")
	print(thePlayer:doesHaveJetpack())
end)
```

**Comment by qaisjp** [comment]
The reasoning is that merging this pull request needs some thought! There is no `jetpack` variable at the moment so a pull request to add _just that variable_ is trivial to merge.

Does that make sense?

**Comment by Dezash** [comment]
Not really, would you mind sharing those thoughts? Also, this variable wouldn't work without setPedJetPack function. You can even see a commented out line attempting to add it with givePedJetPack and removePedJetPack, but it didn't seem to work out.

**Comment by qaisjp** [comment]
> Not really, would you mind sharing those thoughts?

I generally agree that replacing the current two functions with `setPedWearingJetpack` is a good idea. This would need discussion with the other devs.

I am not sure if we should merge this for 1.5.6, and if we do, it should probably be implemented in a different way (instead of creating a new packet, we should utilise the old two packets — we can replace those with one packet in 1.6).

If you are burning for this feature, I can merge the `ped.jetpack` variable change now. Otherwise the other changes and discussions need to happen. Does that help?

> Also, this variable wouldn't work without setPedJetPack function. You can even see a commented out line attempting to add it with givePedJetPack and removePedJetPack, but it didn't seem to work out.

An implementation similar to `ped.vehicle` is required, it's not a 1 line change. [See my previous comment.](https://github.com/multitheftauto/mtasa-blue/pull/243#issuecomment-406304558)

**Comment by Dezash** [comment]
I'm not burning for this feature and I think that replacing the other two packets is a great idea.

**Comment by Dezash** [comment]
Here are some of the ideas that I thought of:
1. Change setPedJetPack to use GIVE_PED_JETPACK and REMOVE_PED_JETPACK packets.
2. Change give/removePedJetPack to use SET_PED_JETPACK packet.
3. Use all 3 function and packets.
4. Scrap setPedJetPack and add OOP function like the vehicle class.
5. 3 and deprecate give/removePedJetPack in 1.5.6. Remove them completely in 1.6 to get rid of the extra packets.
6. ???

**Comment by qaisjp** [comment]
Let's do this:

Now:

- Rename this function to `setPedWearingJetpack` (the different capitalisation of `Jetpack` is deliberate)
- Use the existing packets (remove your packet code)
- Mark the old two functions (give/remove) as deprecated


Later, in a different pull request, for 1.6:

- replace with a single packet

What do you think?

**Comment by Dezash** [comment]
What's the point of keeping these packets if you want to remove them in 1.6 anyway? What is going to change in 1.6?

**Comment by qaisjp** [comment]
Backwards compatibility

**Comment by patrikjuvonen** [comment]
There are netcode changes planned for 1.6, which is why some features won't be implemented yet also.

**Review by qaisjp — CHANGES_REQUESTED** [review]
The old jetpack functions need to moved to CLuaManager and then I think that's it! Thanks for this PR.

**Comment by Dezash** [comment]
What about lua_classfunction? CLuaManager doesn't contain any, should it be moved there anyway?
If you are going to merge this now, you should probably revert this commit: https://github.com/multitheftauto/mtasa-blue/pull/243/commits/d89a095d2c6f6bddf59ae676a69b50aa2e231c93 since it makes the upgrade feature replace the function name with that string.
Also, https://github.com/multitheftauto/mtasa-blue/pull/243/commits/5705e46b03a431c50dc86509df070882a61d2e42 prevents me from starting the resource with the new jetpack functions: 

> start: Resource 'test' start was requested (Not starting resource test as server has come back from the future)

Is this suppose to be happening on custom builds?

**Comment by qaisjp** [comment]
Upgrade problem: doesn't false mean it hasn't been removed yet? And so
shouldn't upgrade?

Future problem: I think it is because the revision listed doesn't exist
yet. I might have done something wrong there.

**Comment by ccw808** [comment]
Custom builds don't have a fully valid version number (build number is 0 by default), so certain version checks should probably be skipped/modified

**Comment by Dezash** [comment]
@qaisjp from what I tested, setting it to true just outputs a message saying that the function has been removed (even though it's still usable) followed by strNewName. Setting it to false attempts to replace the function name with strNewName.

**Review by qaisjp — APPROVED** [review]

**Comment by qaisjp** [comment]
be8c989 is dirty and doesn't actually revert ...

(edit: fixed in 96830bbe0)

**Pull request merged**
