### PR TITLE
Fix reset font in gridlist

### LINKED ISSUE #622: Using guiGridListSetItemText with already exists row will reset the row font to the default
**Describe the bug**
guiSetFont change the font of all rows in the grid list, however when an already exists row text changed with guiGridListSetItemText its font will reset to the default while the font of the rest of the rows will remain the same.

Also guiSetFont won't have any effect to any row afterwards.

**To reproduce**
```lua
local x, y = guiGetScreenSize()

gridList = guiCreateGridList((x-200)/2, (y-200)/2, 200, 200, false)
guiGridListAddColumn(gridList, "Test", 0.9)
guiSetFont(gridList, "default-bold-small")


for i=0, 10 do
	guiGridListSetItemText(gridList, guiGridListAddRow(gridList), 1, "#"..i, false, false )
end

addCommandHandler("xx",
function()
	for i=0, 5 do
		guiGridListSetItemText(gridList, i, 1, "#"..i, false, false)
	end
end)
```
Run that then do /xx.

**Expected behaviour**
For the font that was set on the GUI element to be used.

**Screenshots**
image

**Version**
Both v1.5.6-release-14414

**Additional context**

From https://bugs.mtasa.com/view.php?id=9080

### PR DESCRIPTION
**Pull request by FileEX**
Fixes #622 

**New syntax**
```lua
guiGridListSetItemText( element gridList, int rowIndex, int columnIndex, string text, bool section, bool number, bool changeFont)
```

***changeFont*** - If you changed gridlist font with guiSetFont, set this parameter to true, if no, set to false.

### CODE REVIEW

**Comment by CrosRoad95** [comment]
i prefer just font element instead of boolean

**Comment by FileEX** [comment]
> i prefer just font element instead of boolean

Why user have always set font to row? if user set font with guiSetFont.

**Comment by Pirulax** [comment]
Actually, you've modified some other things as well, take a look at your last commit.

**Comment by FileEX** [comment]
What do you mean? Because i don't see

**Comment by MegadreamsBE** [comment]
He means https://github.com/multitheftauto/mtasa-blue/pull/690/commits/4ac79708a4510dfc985cd126e581df2eb591c45e , your Visual Studio did some unnecessary reformatting of the code.

**Comment by FileEX** [comment]
But i fix it here https://github.com/multitheftauto/mtasa-blue/commit/d7f59cf349fe370c3fef5bed2ba411b5ff7c8685

**Review by qaisjp — COMMENTED** [review]
Please explain your thought process behind introducing an extra parameter.

**Comment by FileEX** [comment]
If user change font to e.g 'default-bold-small', and set text on existing row the font will be reset to 'default-normal'. So i don't have other idea how check if user change font or no, so user have to set parameter about this, if change font on font which him set so true, if don't he use 'guiSetFont' parameter should be false. (Sorry for my eng)

**Comment by qaisjp** [comment]
What if you set a flag to track this?

**Comment by FileEX** [comment]
Idk what u mean

**Pull request closed without merging**
