### PR TITLE
Use vector length method instead of manual distance calculation

### PR DESCRIPTION
**Pull request by NanoBob**
Simplifies distance calculation by using `.Length()` method on the `CVector` class

### CODE REVIEW

**Comment by Inder00** [comment]
That's very useful because its actually using sqrt which consuming a lot of cpu power.

**Comment by NanoBob** [comment]
> That's very useful because its actually using sqrt which consuming a lot of cpu power.

Well not really, since the actual source of the `.Length()` method is
```cpp
inline float Length() const { return sqrt((fX * fX) + (fY * fY) + (fZ * fZ)); }
```

**Comment by Pirulax** [comment]
`sqrt` isn't really all that expensive actually.
But if you really want to avoid it, square the stuff you test against, so you can just use the squared length.

**Comment by Pirulax** [comment]
`sqrt` isn't really all that expensive actually.
But if you really want to avoid it, square the stuff you test against, so you can just use the squared length.

Eg.:
```cpp
float fDistance = (vecPos - vecRemovalPos).LengthSq();

if (fDistance <= std::pow(pFind->GetRadius(), 2.0f) && (cInterior == -1 || pFind->GetInterior() == cInterior))
```

**Review by Pirulax — APPROVED** [review]

**Comment by Pirulax** [comment]
Whatever, I see the change wont be made, so I'm merging it.

**Pull request merged**
