### PR TITLE
Fix #2086: installer: Don't overwrite MTA shortcuts

### LINKED ISSUE #2086: installer: Don't overwrite MTA shortcuts
**Is your request related to a problem? Please describe.**
If you run MTA installer while MTA is already installed (in an effort to update the build, or in-place reinstall), it will overwrite the Desktop and Start Menu shortcuts regardless of them already existing. This will clear all of the shortcut properties & settings.

Some people have compatibility settings that are set to the shortcuts, rather than Multi Theft Auto.exe itself.. which are subsequently removed by the installer. For example, they might have "Run as Administrator" in the properties > advanced options of that shortcut, rather than on the main executable Multi Theft Auto.exe

This particular example (admin access) has been seen in a technical support/issue resolution context for MTA countless times, therefore you can expect some users to be manually setting "Run as Administrator", of which a part can be speculated to do it through the MTA shortcuts rather than the EXE.

While overwriting shortcuts if they already exists serves no purpose, it may adversely affect that group of users, if they ever reinstall MTA (in place upgrade).

**Describe the solution you'd like**
Add installer checks to see if the shortcut **MTA San Andreas 1.5.Ink** at respectively `C:\Users\Username\Desktop\` and `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\MTA San Andreas 1.5` already exist, and skip overwriting them if they do.

### PR DESCRIPTION
**Pull request by se16n**
Hello,

This PR fixes #2086

I've introduced check for various shortcuts if they already existing and if they are then don't overwrite them.

The thing to notice is that this is depending on current installer folder structure. It should be update if folder structure will be changed in the future.
Let's say we update MTA exe location from "$INSTDIR\Multi Theft Auto.exe" to "$INSTDIR\NewFolder\Multi Theft Auto.exe" in this case we have 2 choices on how to handle existing shortcuts:

1. Delete old shortcut and bring in a new one.
2. Replace EXE location in existing shortcut. I've briefly checked if there's such an option in NSIS and it seems with usage of [ShellLink plug-in](https://nsis.sourceforge.io/ShellLink_plug-in) it would be possible:
In pseudocode:
```
if ShellLink::GetShortCutTarget "$SMPROGRAMS\\MTA San Andreas ${0.0}\Play MTA San Andreas.lnk" !== "$INSTDIR\Multi Theft Auto.exe" then
    ShellLink::SetShortCutTarget "$SMPROGRAMS\\MTA San Andreas ${0.0}\Play MTA San Andreas.lnk" "$INSTDIR\Multi Theft Auto.exe"
```

### CODE REVIEW

**Comment by ccw808** [comment]
Checking the existing short cut target is a good idea because the user might install again to a different directory and the shortcut should always launch the last installed version

**Comment by se16n** [comment]
> Checking the existing short cut target is a good idea because the user might install again to a different directory and the shortcut should always launch the last installed version

Thank you. Then i'll close this PR and will try to explore the way with ShellLink plugin.

**Comment by se16n** [comment]
## Preface

Installation script is a bit messy and I'm intentionally tried to avoid to touch anything but shortcuts part.

## Implementation

1. Variables for all kind of shortcuts/exe names as well as paths to them were introduced. See Var at the beginning of the script.
2. All logic related to deletion of a shortcuts was removed because we don't remove them anymore.

### Algorithm

Algorithm is quite simple: we check if shortcuts with MTA standard names exist and if so update else create them.

## Testing strategy

### Prerequisites

1. Make sure following objects doesn't exist in your system:
	1. %USERPROFILE%\Desktop\Multi Theft Auto.lnk
	2. %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu
		1. %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\MTA San Andreas.lnk
		2. %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\MTA Server.lnk
		3. %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Uninstall MTA San Andreas.lnk
		
### Testing steps

#### Client installation

1. Install Client via MTA installer.
2. Verify link to MTA Client exists in desktop folder.
	1. EXPECTED: %USERPROFILE%\Desktop\Multi Theft Auto.lnk exist.
	2. EXPECTED: %USERPROFILE%\Desktop\Multi Theft Auto.lnk point to the Multi Theft Auto.exe from directory specified during installation.
3. Verify link to MTA Client exists in start menu folder.
	1. EXPECTED: %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\MTA San Andreas.lnk exist.
	2. EXPECTED: %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\MTA San Andreas.lnk point to the Multi Theft Auto.exe from directory specified during installation.
4. Verify link to MTA Server exists in start menu folder.
	1. EXPECTED: %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\MTA Server.lnk exist.
	2. EXPECTED: %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\MTA Server.lnk point to the MTA Server.exe from directory specified during installation.
5. Verify link to MTA Uninstaller exists in start menu folder.
	1. EXPECTED: %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Uninstall MTA San Andreas.lnk exist.
	2. EXPECTED: %USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Uninstall MTA San Andreas.lnk point to the Uninstall.exe from directory specified during installation.
	
### Client update (client installed in the folder where MTA already installed)

1. Add "Run as Administator" to all the shortcuts created during "Client installation" step.
2. Change target of all the shortcuts created during "Client installation" step to any exe non-related to the MTA. 
2. Install Client via MTA installer.
3. Verify link to MTA Client in desktop folder points to the Multi Theft Auto.exe from directory specified during installation.
4. Verify link to MTA Client in desktop folder preserve "Run as Administrator" setting.
5. Verify link to MTA Client in start menu folder folder points to the Multi Theft Auto.exe from directory specified during installation.
6. Verify link to MTA Client in start menu folder preserve "Run as Administrator" setting.
7. Verify link to MTA Server in start menu folder folder points to the MTA Server.exe from directory specified during installation.
8. Verify link to MTA Server in start menu folder preserve "Run as Administrator" setting.
9. Verify link to MTA Uninstaller in start menu folder folder points to the Uninstall.exe from directory specified during installation.
10. Verify link to MTA Uninstaller in start menu folder preserve "Run as Administrator" setting.

**Comment by Dutchman101** [comment]
@se16n is this still a draft, or ready for code review (removal of the draft tag)?

**Comment by se16n** [comment]
> 
> 
> @se16n is this still a draft, or ready for code review (removal of the draft tag)?

Hello. Yes, it can be reviewed.

**Review by botder — APPROVED** [review]

**Comment by Dutchman101** [comment]
Maybe the appearance of an invalid `MTA San Andreas.lnk1.5` shortcut (right below the valid one) on my desktop is caused by this PR:

image
image

The fix of issue #2086 works, though.. that valid shortcut keeps its compatibility settings

**Comment by Lpsd** [comment]
This was also reported by a user on the community Discord recently

**Comment by botder** [comment]
Fixed in 1c043468b52348589d0ae379f914e490c0630cdf

**Pull request merged**
