### PR TITLE
0009611: refactor GUIGetChatboxLayout, and add the CVar argument as advertised on Wiki

### PR DESCRIPTION
**Pull request by patrikjuvonen**
**Mantis Bug Tracker issue:**
[9611](https://bugs.multitheftauto.com/view.php?id=9611)

**Summary:**
- Refactored `GUIGetChatboxLayout` in `CLuaGUIDefs`;
- Added the `CVar` argument as advertised on Wiki (been missing all this time);
- Pretty small and simple fix, easy to test.

**Tested with:**
```lua
local cvars = {
	123,
	"nonsense_cvar",
	"chat_font",
	"chat_lines",
	"chat_color",
	"chat_text_color",
	"chat_input_color",
	"chat_input_prefix_color",
	"chat_input_text_color",
	"chat_scale",
	"chat_position_offset_x",
	"chat_position_offset_y",
	"chat_position_horizontal",
	"chat_position_vertical",
	"chat_text_alignment",
	"chat_width",
	"chat_css_style_text",
	"chat_css_style_background",
	"chat_line_life",
	"chat_line_fade_out",
	"chat_use_cegui",
	"text_scale",
	false
}

for i, cvar in ipairs(cvars) do
	local result = getChatboxLayout(cvar)
	outputConsole("cvar: [" .. cvar .. "]; result: [" .. inspect(result) .. "]; type: [" .. type(result) .. "]")
end

local result = getChatboxLayout()
outputConsole("all cvars (no args); result: [" .. inspect(result) .. "]; type: [" .. type(result) .. "]")

for cvar, result in pairs(result) do
	outputConsole("cvar (from all cvars table): [" .. cvar .. "]; result: [" .. inspect(result) .. "]; type: [" .. type(result) .. "]")
end
```

### CODE REVIEW

**Comment by Pirulax** [comment]
So you added some new cvars too?

**Comment by qaisjp** [comment]
i think returning table of numbers is fine as it's compatible with the full table format @patrikjuvonen

**Comment by patrikjuvonen** [comment]
@Pirulax No it's using the same as it did before.
@qaisjp Wiki advertises it returns 4 numbers for a color and 2 numbers for a scale. I think a table is unnecessary, and isn't consistent with getVehicleColor etc.

**Comment by qaisjp** [comment]
we can change the wiki. In fact I'm not sure if this feature is necessary anymore (although it is a nice refactor so it'd be nice to keep that!)

**Comment by patrikjuvonen** [comment]
Ok, let's keep it as a table.

**Comment by Pirulax** [comment]
If you do, then the wiki is missing some cvars.
Should i add them?
Or some of the cvars in ur table aren't real cvars?(other than the "nosense_cvar")

**Comment by patrikjuvonen** [comment]
@Pirulax getChatboxLayout is supposed to return chatbox related CVars, nothing else.
The test contains a nonsense cvar to make sure it returns false when the CVar given is invalid.

**Comment by Pirulax** [comment]
image
These are the CVars that wiki lists.

**Comment by patrikjuvonen** [comment]
Ok, looks like the Wiki article is not up to date. Needs to be updated.

**Review by qaisjp — APPROVED** [review]

**Pull request merged**
