### PR TITLE
Trailer sync fix

### PR DESCRIPTION
**Pull request by tederis**
This is a small fix brings us the temporary solution for a trailer's desync issue. It was tested well on a real project for about six months. It's not a comprehensive solution but fixes the problem at the moment. Video: https://youtu.be/iFClCa_xaG4

### CODE REVIEW

**Comment by MegadreamsBE** [comment]
Does it also handle a trailer that is carrying a trailer itself?

**Comment by tederis** [comment]
> Does it also handle a trailer that is carrying a trailer itself?

Haven't tested it. But I think it should.

**Review by qaisjp — APPROVED** [review]
Thank you, looks fine to me!

**Comment by PlatinMTA** [comment]
Nice! Gonna check this on my server as soon as possible.

**Comment by fresholia** [comment]
a

Client: Multi Theft Auto v1.5.7-release-20358.5.001 - Server: Multi Theft Auto v1.5.7-release-20411

When more than one player goes with a truck, it looks like this by other players.

**Comment by dmi7ry** [comment]
> Client: Multi Theft Auto v1.5.7-release-20358.5.001 - Server: Multi Theft Auto v1.5.7-release-20411

It was fixed in r20402, so your 20358 has not the fix.

**Comment by PlatinMTA** [comment]
> > Client: Multi Theft Auto v1.5.7-release-20358.5.001 - Server: Multi Theft Auto v1.5.7-release-20411
> 
> It was fixed in r20402, so your 20358 has not the fix.

AKA: The fix just changes clientside code, just update to the last nightly and you will see the trailers synced, at least it works just fine in my server 👍

**Comment by Xenius97** [comment]
> When more than one player goes with a truck, it looks like this by other players.

This still an issue, trailers are broken.

**Pull request merged**
