### PR TITLE
Fixing MTA library hashes for Windows 7/8.x

### PR DESCRIPTION
**Pull request by nweb**
Fixes a problem (https://github.com/multitheftauto/mtasa-blue/issues/3865) for the maetro version, when real file hashes did not match the hardcoded ones.

### CODE REVIEW

**Review by TracerDS — APPROVED** [review]

**Comment by TheNormalnij** [comment]
It's a copy of missing commit: 48f94d89c1f7517cae688804a4249f99947454bc

**Review by TheNormalnij — APPROVED** [review]

**Review by botder — APPROVED** [review]

**Comment by nweb** [comment]
> It's a copy of missing commit: [48f94d8](https://github.com/multitheftauto/mtasa-blue/commit/48f94d89c1f7517cae688804a4249f99947454bc)

Nop, find one difference

**Comment by TracerDS** [comment]
> > It's a copy of missing commit: [48f94d8](https://github.com/multitheftauto/mtasa-blue/commit/48f94d89c1f7517cae688804a4249f99947454bc)
> 
> Nop, find one difference

There are no differences between these 2 commits

**Comment by nweb** [comment]
> > > It's a copy of missing commit: [48f94d8](https://github.com/multitheftauto/mtasa-blue/commit/48f94d89c1f7517cae688804a4249f99947454bc)
> > 
> > 
> > Nop, find one difference
> 
> There are no differences between these 2 commits

Check d3dcompiler_47.dll
_
_I wonder how many commits with backdoors you approved :D_

**Comment by TracerDS** [comment]
> Check d3dcompiler_47.dll _ _I wonder how many commits with backdoors you approved :D_

You said the commits dont match, but they do. Thats all

**Comment by nweb** [comment]
> > Check d3dcompiler_47.dll _ _I wonder how many commits with backdoors you approved :D_
> 
> You said the commits dont match, but they do. Thats all

But they are different. For maetro version the hash of file d3dcompiler_47.dll is different, can't you see it?

**Comment by TracerDS** [comment]
> But they are different. For maetro version the hash of file d3dcompiler_47.dll is different, can't you see it?

I dont know what are you on about, they are the same
image

**Comment by nweb** [comment]
> > But they are different. For maetro version the hash of file d3dcompiler_47.dll is different, can't you see it?
> 
> I dont know what are you on about, they are the same image

Are you kidding? This is not python, in mta the value comes first and then the key.

**Comment by TracerDS** [comment]
> Are you kidding? This is not python, in mta the value comes first and then the key.

I have no idea what you mean rn

**Comment by TracerDS** [comment]
Okay I see my mistake. Nvm

**Pull request merged**
