### PR TITLE
Fixed colshape related crashes

### PR DESCRIPTION
**Pull request by lopezloo**
I can't reproduce it on own but this happens very often on some popular polish RP server.

### CODE REVIEW

**Comment by ccw808** [comment]
How does this fix work? What is the problem with using std::list ?

**Comment by lopezloo** [comment]
Don't know at all but it was crashing in these iterators (CClientColManager.cpp line 122, CClientEntity.cpp line 1114). Always related to some ped.

My debug log before crash in CClientEntity::RemoveAllCollisions (destroying ped):
`[Output] : RemoveAllCollisions| this type ped | m_Collisions.size() 0 | m_Collisions.begin() 650331136 | m_Collisions.end() 837448704 | m_Collisions.empty 1`

I saw CFastList is used in some places for colshapes so I try it.

**Comment by ptasigryp** [comment]
We can't fully reproduce it outside my RP gamemode (devgaming.pl), but it's related to spawning/destroying peds and checking their colshape.

**Comment by qaisjp** [comment]
What is the actual issue? When are these crashes happening? Please can you [upload dumps](https://upload.mtasa.com)?

**Comment by ptasigryp** [comment]
These crashes happen when you are creating peds and sometimes when destroying them (also after /disconnect and /quit). 

Actually it's happening since MTA 1.3, but it was so rare on my server that I couldn't reproduce it. Now I'm developing new update which crashes me with 30% rate and few of my friends with 100% rate. 

Also, when you are far from ped MTA won't crash, but when you will get closer until ped streams in your game will crash. I tried to make script that will crash outside my gamemode, I copied all peds and colshapes into another resource but couldn't got crashed. I can invite you on my local server and you can test it.

 Also, here are my dumps: http://upload.mtasa.com/u/594656960/crashes-cols.zip_

Finally, when more peds are created at the same time, the higher is chance MTA will crash.

**Comment by ptasigryp** [comment]
I forgot to add, when more peds are created at the same time, the higher is chance MTA will crash.

**Comment by ptasigryp** [comment]
Any updates on chance of merging this commit?

**Pull request merged**
