### PR TITLE
Add 'every' parameter to setElementDimension

### PR DESCRIPTION
**Pull request by zneext**
While developing my server (which has multiple lobbies (same gamemode but in different dimensions)) i realized that there wasn't any "easy" way to make an object visible in every dimension (and thus not having to create every object in every dimension or dealing with *setElementDimension*) so i came up with this, it allows us to use **setElementDimension ( object, "every" )** to make an object visible in every dimension. It also reads *dimension="every"* from .map files.

It's my first time dealing with serverside functions which call their client counterpart so i don't know if i did everything correct, Please point any mistakes  i've made. 😃

### CODE REVIEW

**Comment by ccw808** [comment]
Good idea.
Although I prefer "all" instead of "every"

**Comment by qaisjp** [comment]
`CPacketHandler.cpp` and `CEntityAddPacket.cpp` both had irrelevant changes to whitespace - I have modified your original commit to undo your whitespace changes. 

Ignore the "cached" commits shown by GitHub above - they are not actually in the branch... whilst making the modifications I made reverts, but decided to modify your original commit instead (to preserve history). Sorry about the potential email spam.

**Comment by jushar** [comment]
I think we should go for `getElementVisibleInAllDimensions`/`setElementVisibleInAllDimensions` instead as letting `getElementDimension` return a string could cause issues if scripts do something like this:
```lua
local nextDimension = getElementDimension(element) + 1
```
Generally speaking, I like the idea though.

**Comment by zneext** [comment]
@ccw808 English isn't my first language, so i didn't knew what word was the *correct* so i ended up using *every*, but we can change that if needed.

@qaisjp Thanks for fixing that. VS messed up the withespaces and i didn't saw it, sorry.

@Jusonex When the programmer choose use the parameter **every** anywhere he should know that *getElementDimension* will return **"every"**, that's the expected behaviour, I think that introducing a new function for this will be strange, i.e. what is suposed to happen when you make the element visible in every dimension and then try to change its dimension? It would return *false*? and what about *getElementDimension*? it would return the previously set dimension when in reality the element *isn't in a specific dimension*?

Thanks for the feedback guys 😃

**Comment by Bonsai11** [comment]
I'm just curious, why do you even need this for your multigamemode system?

Usually each arena has its own dimension so you won't see other players. 
Objects are probably created clientside anyway so it doesn't matter if they are visible in all dimensions or not, as the localPlayer can only be in one anyway

.

**Comment by qaisjp** [comment]
@zneext a possible answer to your question

------

`obj:setDimension(dim)` will disable the "dimensionless" state and make it only visible in `dim`. If an object is "dimensionless", then doing `obj:getDimension()` will return the original dimension it was in. 

i.e, setting the dimension to 3, then making it visible in all dimensions will,

* when getting the dimension: return `3` 
* when setting the dimension: make it no longer visible in all dimensions, and update the dimension to the given dimension

**Comment by darkdreamingdan** [comment]
Why don't we assign -1 to 'dimensionless'?

**Comment by zneext** [comment]
@Bonsai11 What do you mean? It's not a multigamemode system, it has only one gamemode but different lobbies, with different matches running on, That's why i came up with this, otherwise i'd have to either create the object on every dimension i need or set all the objects' dimension right after the player join a lobby, Sorry if i haven't made it clear enought on the first post :)

I think that using **-1** instead of **"every"** is the best solution, we won't need to create another functions and it will be compatible with older codes (as *getElementDimension* would return a number too), WDYGT?

**Comment by qaisjp** [comment]
I think `-1` is a great idea.

**Comment by zneext** [comment]
Please let me know how you guys want this, I'd love to get this feature in the next update if possible.

**Comment by ccw808** [comment]
What about a range instead: 
```lua
setElementDimension( object, first, last )
first, last = getElementDimension( object )
```

**Comment by Bonsai11** [comment]
Doesn't it cause problems if an element can be in multiple dimensions?

If a player could be two dimensions, he would be visible to players of each of these dimensions.
So if a player in dimension A kills him, player in dimension B sees him being killed out of nowhere?

In case its only about objects, I think there might be a similar problem with objects that can be destroyed or explode. A vehicle crashes into a multi dimensional barrel and it will explode for everyone, even though only the driver's dimension can see him crash.

**Comment by karimcambridge** [comment]
"What about a range instead:"

Yea but then what if you you want it visible in dimension 1,3, 5?

I think you should go for an array, which is customisable.

If the array contents equals to -1, then every dimension.

**Comment by ccw808** [comment]
The advantage of a range over an array is we can avoid -1 (which seems a bit hacky). However using range/array is overcomplicating things, so let's just go with -1

**Comment by 0x452** [comment]
Good job!

**Comment by zneext** [comment]
Sorry for the delay, I've had some problems with this branch so today i rewrote this entire feature, New PR: #112

**Comment by qaisjp** [comment]
In the future, instead of fragmenting conversation and making multiple pull requests, ask for assistance.

Run these commands on the command line, it should fix the issue:

```
git checkout master
git branch -D setElementDimension-every
git checkout setElementDimension-all
git branch -m setElementDimension-every
git push origin setElementDimension-every --force
```

If your remote is not called `origin`, you may want to change it to whatever points to your own fork.

**Comment by zneext** [comment]
Sorry about that @qaisjp, Running these commands fixed the issue.

**Comment by qaisjp** [comment]
That's great to hear! No problem.

**Review by ccw808 — APPROVED** [review]

**Pull request merged**
