### PR TITLE
0009139: fix invalid model ID in engine LOD functions cause a crash

### LINKED ISSUE #446: engineSetModelLODDistance(20000,1000) causes client crash
**Describe the bug**
`engineSetModelLODDistance(20000, 1000)`
```
Version = 1.5.6-release-16542.0.000
Time = Sun Feb 24 15:04:12 2019
Module = F:\Program Files (x86)\MTA San Andreas 1.5\mta\game_sa.dll
Code = 0xC0000005
Offset = 0x000360E6

EAX=0000036F  EBX=0BED686C  ECX=14871694  EDX=05234B50  ESI=2524B080
EDI=05234B50  EBP=0177EB6C  ESP=0177EB50  EIP=0BCE60E6  FLG=00210202
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```
Dump at [client_1.5.6-release-16542.0.000_gamesa_000360e6_5_FPxMb_0100007F_55F3_009_5F89C_20190224_1504.dmp.zip](https://github.com/multitheftauto/mtasa-blue/files/2897900/client_1.5.6-release-16542.0.000_gamesa_000360e6_5_FPxMb_0100007F_55F3_009_5F89C_20190224_1504.dmp.zip)

Some other crash info:
```
Version = 1.5.2-release-7844.0.000
Time = Sun Feb 07 22:45:42 2016
Module = C:\Program Files (x86)\MTA San Andreas 1.5\mta\game_sa.dll
Code = 0xC0000005
Offset = 0x0002FF8B

EAX=2FEB6EC4 EBX=0000036F ECX=05CD1EAA EDX=31CF7710 ESI=05991864
EDI=0599186C EBP=0028EFE0 ESP=0028EEC4 EIP=0451FF8B FLG=00010202
CS=0023 DS=002B SS=002B ES=002B FS=0053 GS=002B
```
`engineGetModelLODDistance(20000)`
```
Version = 1.5.6-release-16542.0.000
Time = Sun Feb 24 15:02:56 2019
Module = F:\Program Files (x86)\MTA San Andreas 1.5\mta\game_sa.dll
Code = 0xC0000005
Offset = 0x00034A12

EAX=0000036F  EBX=000000C1  ECX=0BECD864  EDX=00004E20  ESI=17D707B8
EDI=00000000  EBP=0177EC84  ESP=0177EB84  EIP=0BCD4A12  FLG=00210206
CS=0023   DS=002B  SS=002B  ES=002B   FS=0053  GS=002B
```

**To Reproduce**
```
crun engineSetModelLODDistance(20000, 1000)
crun engineGetModelLODDistance(20000)
```

**Expected behavior**
No crash

**MTA Client (please complete the following information):**
1.5.6-release-16542.0.000

**Additional context**
https://bugs.mtasa.com/view.php?id=9139

### PR DESCRIPTION
**Pull request by patrikjuvonen**
**Mantis Bug Tracker issue**
[9139](https://bugs.multitheftauto.com/view.php?id=9139), fixes #446

**Summary:**
- An invalid model (at least 20000+) passed to [engineSetModelLODDistance](https://wiki.multitheftauto.com/wiki/EngineSetModelLODDistance) or [engineGetModelLODDistance](https://wiki.multitheftauto.com/wiki/EngineGetModelLODDistance) would cause a client crash. This PR will make sure the model is valid.

### CODE REVIEW

**Comment by patrikjuvonen** [comment]
Now that I think of it, are these supposed to support vehicle and ped models too?

**Comment by qaisjp** [comment]
does it work with vehicle and ped models?

**Comment by patrikjuvonen** [comment]
Seems like it does. I'll add those model checks in as well.

**Comment by qaisjp** [comment]
What kind of crash is caused, and where does it crash?

pModelInfo is currently (or should be) returning `NULL` for incorrect values so the current code (in master) should not be crashing.

If there is an underlying bug with `CGameSA::GetModelInfo` then that should be fixed instead.

**Comment by Pirulax** [comment]
It doesn't crash with invalid modelID, it just returns false.
At least for me.

**Comment by qaisjp** [comment]
This bug seems to be associated with https://github.com/multitheftauto/mtasa-blue/pull/155/files.

It returns true on this line: https://github.com/multitheftauto/mtasa-blue/pull/155/files#diff-3beea7b726cdd57f96a6d8226af4eb9fR538

Removing the offending line does not fix the problem. Returning `false` fixes the problem. Is `return true` a typo?

cc @Sergeanur @botder

**Comment by Sergeanur** [comment]
I don't quite remember, but I think CModelInfoSA::IsValid was used on animation request, so return true was required.

**Comment by patrikjuvonen** [comment]
I guess another option is to mark any 20000+ invalid (or make a separate IsValid method that doesn't care if it's 20000+...)

This is what I've been able to find out so far:

If the name starts with "txd", assume it's refering to a global txd. (https://github.com/multitheftauto/mtasa-blue/blob/master/Client/mods/deathmatch/logic/CModelNames.cpp#L10480)

Encode global txd as model id 20000+ (https://github.com/multitheftauto/mtasa-blue/blob/master/Client/mods/deathmatch/logic/CModelNames.cpp#L10498)

So some "global txd" is what 20000+ ids are, then causes a crash. No actual model has an id of 20000+ so I mean it must be related to some other internal SA fact how things work.

EDIT:
https://github.com/multitheftauto/mtasa-blue/pull/784#issuecomment-466710930
@forkerer commented:
> As far as I'm aware, (and in the IDB i'm using), 20000 is original size of that array in gta sa, trying to change physical properties of anything above that crashes the client. I think the additional space reserved in CGameSA (up to 26000) was made either by mistake, or in case of mta team wanting to expand some limits.

**Pull request merged**
