### PR TITLE
Fix #423: setRadioChannel doesn't work when outside a vehicle

### LINKED ISSUE #423: setRadioChannel doesn't work when outside a vehicle
**Describe the bug**
Whenever you do setRadioChannel on a client while not in a vehicle, the radio channel will not be set - instead, will go to the station for less than a second and roll back to 0.

This is however fixed when the player enters the vehicle and radio gets on, and then exits, setRadioChannel works again. But without entering a vehicle it just simply flashes to the channel and resets to 0.

Apparently fixable by setting setRadioChannel( 0 ) to the beginning of the script, yet this does not work. I even tried everything with multiple timers and different techniques like this but none of which worked.

**To Reproduce**

    Enter your server
    Spawn the player
    crun setRadioChannel(1)
    Doesn't work.
    Enter a vehicle (and make sure radio gets on).
    Exit the vehicle.
    crun setRadioChannel(1)
    Works.

Additionally you could use these to test it out easily:

```lua
srun for ,v in ipairs(getElementsByType("player")) do spawnPlayer(v, 0, 0, 3) setCameraTarget(v, v) fadeCamera(v, true, 0) end
crun setRadioChannel(1)
srun vehicle = createVehicle(410, 5, 0, 3) for ,v in ipairs(getElementsByType("player")) do warpPedIntoVehicle(v, vehicle) end setTimer(destroyElement, 500, 1, vehicle)
crun setRadioChannel(1)
```

Note, that this happens sometimes. I was no longer able to reproduce this once I had the radio working and reconnected or restarted the server. But once I restarted my client and the server, this problem appeared again.

I was also able to hear radio just about 100 ms when I reconnected to the server while having the radio on. So it seems MTA isn't resetting the radio value (properly), and for some reason sets it incorrectly as well.

~~Client and server both at Multi Theft Auto v1.4.1-release-7312.~~

Running no other scripts other than runcode.

**Expected behavior**

**Screenshots**

**MTA Client (please complete the following information):**
Multi Theft Auto v1.5.6-release-16191

**MTA Server (please complete the following information):**
n/a

**Additional context**
https://bugs.mtasa.com/view.php?id=8908

### PR DESCRIPTION
**Pull request by patrikjuvonen**
Fixes an issue where [setRadioChannel](https://wiki.multitheftauto.com/wiki/SetRadioChannel) function doesn't work on first try. You will have to enter a car or initialize an ambient track such as a stadium interior radio. This PR will initialize the ambience track manager by calling its `Service` method. It appears to fix the issue.

Feel free to comment on what should be done instead, this is my first time working with asm injection stuff.

### CODE REVIEW

**Comment by qaisjp** [comment]
Unfortunately I can't reproduce a fix using your patch (i.e your patch does not fix anything). I am using a stripped radio version of GTASA, though. I'll try and re-test with full radio.

Interestingly, both before and after applying this patch, the following problem occurs:

**setRadioChannel breaks stadium audio**

1. Start game afresh, and join server
1. `crun setRadioChannel(9)` (this does not work, except that the radio plays for like 250ms)
1. Go to a stadium and observe that the regular stadium audio does not work. normally it does play - this only happens because you tried `crun setRadioChannel(9)`. (note that this also happens in other audio interiors, like the shamal)
1. go to "outside", try to play radio, and note that step 2 still occurs
1. go back to the stadium and note that step 3 still occurs
1. spawn a vehicle in the stadium
1. when you click enter, the audio will work again
1. leave the vehicle, go "outside", and now `crun setRadioChannel(9)` will work

**Comment by patrikjuvonen** [comment]
Thanks for testing. There appears to be two issues, the latter being that once you start the radio (call to StartRadio), it will keep the radio on until you manually turn it off. I could try making it so that once you enter an area with an ambience track, it will stop the radio automatically and hence enables the ambience track. The fact that the radio doesn't turn on is weird, I'll test around a bit more. Where did you spawn? Is it the Steam version or some other version? I'm wondering if this has to do with some wrong offsets like with the radio class we had to do some tweaking.

**Comment by qaisjp** [comment]
> Is it the Steam version or some other version?

`b0cf9fb580ff473b1fdefc7b7617059d *gta_sa.exe` I think it's nocd 1.0

> Where did you spawn?

Happens with play's pirate ship spawn, as well as Easter Bay Airport in San Fierro.

**Comment by qaisjp** [comment]
Adding back the radio music to the streams folder makes this patch work. Do you think you can still fix it when you have no music? 

To remove radio make sure your audio/streams folder looks like this:

image

**Review by qaisjp — APPROVED** [review]

**Review by qaisjp — DISMISSED** [review]
Needs secondary review from @multitheftauto/blue-collaborators

**Comment by patrikjuvonen** [comment]
Odd, I can't seem to reproduce that issue even without those files.

**Comment by patrikjuvonen** [comment]
I am no longer committed to working this issue so I'm closing this PR. Hopefully some of the work could be of use to someone else in the future.

**Pull request closed without merging**
