### PR TITLE
Custom ifp animations

### PR DESCRIPTION
**Pull request by ghost**
I've implemented custom IFP animations into MTA while touching the current animation system as little as possible. I've written my own IFP loader that will allow scripters to load their own IFP file using engineLoadIFP and play animations using setPedAnimation, or replace and restore them using engineReplaceAnimation and engineRestoreAnimation respectively. The code is client-side only. 

There are three new Lua functions added:
```
// loads IFP with a custom block name 
ifp engineLoadIFP ( string ifp_file_path, string custom_block_name ) 

// this will replace an internal GTA animation with custom one, it's a light-weight operation,
// don't worry too much about performance. Different peds can have different running, walking,
// crouching, shooting, etc. animations all running simultaneously because we are not actually
// replacing animation hierarchies, we are merely storing everything in std::map which is in
// CClientPed. When an animation triggers, we get the ped by clump, and play the animation
// we wish to play. setPedAnimation works a little different than this, but the idea is same.
bool engineReplaceAnimation ( ped thePed, string block_name, string anim_name, string custom_block_name, string custom_anim_name )

// This will restore animation replaced using engineReplaceAnimation, if only 1 parameter 
// is provided which is ped, then it will restore all animations, if  block name is also provided,
// then it will restore animations of that block only, if animation name is provided as well,
// it will restore that specific animation only.
bool engineRestoreAnimation ( ped thePed [, string block_name, string anim_name ] )
```
To unload IFP, use destroyElement, and to play the custom animation simply use setPedAnimation. Also, I've tested everything countless times, but if you find something that is not the way it should be then please let me know. 

This is stable because animation loading, playing, and unloading is handled by my custom IFP loader, so we know exactly how it works. I did not use any hackish techniques in my code. I've tried my best sticking to KISS principle, so anyone can maintain it.

### CODE REVIEW

**Comment by ccw808** [comment]
Great work!
Fix merge conflicts by applying the recent source formatting:
1) http://prereleases.llvm.org/win-snapshots/clang-format-r325576.exe -> utils\clang-format-r325576.exe
2) http://findandreplace.io/downloads/fnr.zip -> utils\fnr.exe
3) Run utils\win-apply-clang-format.bat

**Comment by ghost** [comment]
@ccw808 Thank you ^^. I've executed the .bat script, but it doesn't seem to solve merge conflicts. I wonder what I'm doing wrong?

**Comment by PlatinMTA** [comment]
Hope you get this to work properly, gj

**Comment by Citizen01** [comment]
Reopened here: #190

**Pull request closed without merging**
