### PR TITLE
Command aliases feature

### PR DESCRIPTION
**Pull request by znvjder**
Added aliases to commands. Available on both sides ( client and server ), basic tested as well.

Functions:
- addCommandAlias( string alias, string command )
- removeCommandAlias( string alias, string command )
_in future:_
- isCommandAlias( string alias, string command )
- getCommandAliases( string command )

When we remove the command to which aliases are suppressed, the aliases'll be removed.
In next commit are planned:
- check if A command is an alias of B command;
- get all commands which aliases are suppressed;

### CODE REVIEW

**Comment by Dutchman101** [comment]
https://travis-ci.org/multitheftauto/mtasa-blue/jobs/420806851
@l0nger

**Comment by znvjder** [comment]
Thanks for info. I didnt check it on linux with gcc 4.8.
Tommorow i'll fix it.

**Comment by ghost** [comment]
@l0nger not necessarily your fault though, travis will fail at times for no reason.

**Comment by znvjder** [comment]
std::vector doesn't support erase with const_iterator on linux which gcc version is below 4.9.
Already fixed.

**Comment by jushar** [comment]
As already stated in https://github.com/multitheftauto/mtasa-blue/pull/172#issuecomment-416012411 we do not plan on merging this, because it can be easily implemented in Lua.

Sorry and thanks anyway.

**Pull request closed without merging**
