### PR TITLE
Refactor server side CVehicleNames.cpp

### PR DESCRIPTION
**Pull request by shadylua**
Vehicles with two names: Vehicles with alternative names are listed in order. For example, “Sadler Damaged”, the “Sadler” row has both the damaged version and the normal version names. and The vehicle names are organized alphabetically so that they can be used consistently in the same order on both server and client side. (the confusion in the table has been eliminated by sorting the server and client side from a to z)

### CODE REVIEW

**Comment by ghost** [comment]
You duplicate #3799

**Comment by shadylua** [comment]
> You duplicate #3799

one for client and one for server;

[Client/mods/deathmatch/logic/CVehicleNames.cpp](https://github.com/multitheftauto/mtasa-blue/pull/3799/files#diff-3d0fe775e3eee42f15d36dc07fa590f2b8c4716ebd74e95b668b7e59b5dc9ec3)

[Server/mods/deathmatch/logic/CVehicleNames.cpp](https://github.com/multitheftauto/mtasa-blue/pull/3800/files#diff-c676cd3507856ff0748f84f123e08edc59f394ebcd001e4d47c50db3502e285a)

**Comment by Fernando-A-Rocha** [comment]
You should merge the other PR to this one, and rename the PR to what issue it resolves

**Comment by SpeedyFolf** [comment]
Isn't this going to break things horribly? You changed the list from 400-611 to alphabetical but changed nothing else

**Comment by TracerDS** [comment]
Please add the info about changing the server version of files as per https://github.com/multitheftauto/mtasa-blue/pull/3800#issuecomment-2414458479

**Comment by ghost** [comment]
It's easier for you to merge the other one into this one and rename it, so it would be more organized.

**Comment by TheNormalnij** [comment]
It breaks `getVehicleName` function

**Pull request closed without merging**
