### PR TITLE
add dxDrawTriangle

### PR DESCRIPTION
**Pull request by forkerer**
Since there is currently no easy way to draw triangles in MTA, and they are most basic shape that can be used to draw any other shape, i decided to add dxDrawTriangle function.

This branch contains 2 new files, CTriangleBatcher.cpp and CTriangleBatcher.h, used system is similiar to (and based on) ones used currently in dxDrawLine3D or dxDrawImage, all triangles can be drawn either PreGUI or PostGUI.
There are no problems with drawing on RenderTargets.
The function looks like this:
`bool dxDrawTriangle( vec2 posVert1, vec2 posVert2, vec2 posVert3, [int colorVert1, int colorVert2, int colorVert3, bool postGUI=false] )`
If only first color is specified, all vertices will share that color, otherwise the color is interpolated between vertices.
Example image:
[solid color triangle, gradient, and triangle using alpha](https://imgur.com/a/mTpXY)

### CODE REVIEW

**Comment by qaisjp** [comment]
IMO it would be better to have a generalised function "dxDrawPolygon" that works for [simple](https://en.wikipedia.org/wiki/Simple_polygon), [convex](https://en.wikipedia.org/wiki/Convex_polygon) polygons.

**Comment by forkerer** [comment]
With current way dxDraws are handled, that would require triangulation to be performed on every frame, with dxDrawTriangle you're able to implement triangulation in lua and just use result to draw it every frame.

**Comment by jushar** [comment]
I agree with @qaisjp that dxDrawPolygon for convex polygons is better.

Also, I think it's still a lot faster in practise, because:
* you'd only need one DirectX draw command (because you could use a triangle strip)
* triangulation algorithms are in `O(n log n)` which is still quite fast for small n. More transitions from Lua to C++ and interpreting Lua is probably way slower

**Comment by CrosRoad95** [comment]
I think, both option should be implemented, triangle ( with gradient ) and polygon ( mayby with gradient if it is possible )

**Pull request closed without merging**
