### PR TITLE
setWaterLevel: added bIncludeWorldSeaLevel and bIncludeOutsideWorldLevel

### PR DESCRIPTION
**Pull request by TheNormalnij**
Recreated  #889

### CODE REVIEW

**Comment by Zangomangu** [comment]
I've tested this and it works well.
It keeps default behaviour so there are no issues with existing scripts.

**Review by ghost — APPROVED** [review]

**Comment by qaisjp** [comment]
@saml1er we are on a feature freeze :(

**Comment by ghost** [comment]
Oh shit. Revert?

**Comment by qaisjp** [comment]
Yes please - I don't think there is enough time for people to use and test `setWaterLevel`.

Also, @sbx320 asked this question in the original PR, which I do not think was answered:

> Is there any particular reason why we'd not just apply it to everything anyway? I think setWaterLevel not applying outside world boundaries is more of a bug rather than a feature.

**Comment by ffsPLASMA** [comment]
This feature would become handy for some sort of tsunami scenario.

**Comment by TheNormalnij** [comment]
@qaisjp, with this way you can replace all water and replace water level seamlessly with new water. Also this is workaround for  some streamer bugs when all map is replaced

**Comment by qaisjp** [comment]
sbx's comment is not talking about rejecting the PR, it's talking about making setWaterLevel just always work for all water and not needing to specifically set `bIncludeOutsideWorldLevel`.

Why would you ever set `bIncludeOutsideWorldLevel` to false?

**Comment by TheNormalnij** [comment]
To keep old behaviour

**Comment by qaisjp** [comment]
It's a bug, not a feature. I can't think of a reason why you'd ever want that old (broken) behaviour.

**Comment by ffsPLASMA** [comment]
Map scripts that use setWaterLevel might get broken, thats why we should keep the broken way for legacy reasons.

**Comment by TheNormalnij** [comment]
Some [scripts](https://forum.mtasa.com/topic/101142-jsconverted-maps/) will broken if we change behaviour

**Comment by TheNormalnij** [comment]
Reopen?

**Comment by qaisjp** [comment]
Yeah github doesn't support reopening of merged PRs. please can you submit another one 🙃

**Pull request merged**
