### PR TITLE
Add LuaYEET 2.0 alongside Lua 5.1

### PR DESCRIPTION
**Pull request by Pirulax**
**I'm just joking. FYI: LuaJIT == LuaYEET**

Add LuaYEET

- [x] Add premake, and yeet src
- [x] Make client build
- [x] Make client run 
- [ ] Make server compile (have to add separate Lua project)
- [ ] Add back / forward port MTA crap (like `nexpectedresults`)
- [ ] Fix issues that arise
- [ ] Test
- [ ] Disable FFI (simple, added here so I wont forget)
- [ ] Disable `require`

**Huge issue: Memory limitation of 2 GB for x86**
Which sadly means, that this has to be an opt-in, as we already have issues with 4gb limitation..
Keep in mind that YEET is API compatible with 5.1, so fortunately we can just switch DLLs run-time (when connecting to the server)
- [ ] Make it able to switch between Lua 5.1 and YEET (Client only)
 
Please discuss anything related over at [the discussion for it](https://github.com/multitheftauto/mtasa-blue/discussions/903).

### CODE REVIEW

**Comment by Disinterpreter** [comment]
> Disable FFI (simple, added here so I wont forget)

Eh... It would be great if we solve all our conflicts with potential server "security" and turn it on at the server.

**Comment by Pirulax** [comment]
Yeah I think allowing it on the server is totally possible.

**Comment by Einheit-101** [comment]
Is there anywhere info where i can read something about benefits and problems that come with LuaJit?

**Comment by Pirulax** [comment]
Yes, I think in your case it will be very beneficial. 
Please see the [discussion](https://github.com/multitheftauto/mtasa-blue/discussions/903).
If you would like I can provide you a test client with JIT. (Actually, the artifacts from here should work fine. Server doesnt compile yet, thats why it fails, but client should work.)

**Comment by Einheit-101** [comment]
I could test it with my ww2 Server, it is not as efficient as my new server and also a lot bigger code-wise

**Comment by ERAGON007** [comment]
ah shit, here we go again :(

**Comment by patrikjuvonen** [comment]
This draft pull request was closed because it has been marked stale for 30 days with no activity.

**Comment by Pirulax** [comment]
What I'll do most likely is add LuaJIT for the server.
We can't add it to the client, because of *reasons* (Mostly the memory limit, that can be solved on server by running x64).

**Comment by ERAGON007** [comment]
> What I'll do most likely is add LuaJIT for the server. We can't add it to the client, because of _reasons_ (Mostly the memory limit, that can be solved on server by running x64).

Are there any progress on this matter? what problems did you face while implementing the server side

**Pull request closed without merging**
