### PR TITLE
Add areVehicleLightsOn function

### LINKED ISSUE #478: Function to determine current vehicle light state
**Description**
Surprisingly it is currently impossible to get the vehicle light state (Enabled/disabled) in MTA.
Vehicles will always automatically disable their lights between 06:00 and 07:00 and enable them between 20:00 and 21:00. The exact point of time is random for every vehicle, it looks like it is a property of each vehicle once it gets created.

**Describe the solution you'd like**
A function that gets the current vehicle light status.

**Describe alternatives you've considered**
A function that sets the automatic light enable/disable time of a specified / all vehicles to a specified value.

**Additional context**
It can be done with scripting by simply overwriting headlight state, yes.

### PR DESCRIPTION
**Pull request by StrixG**
This function gets the vehicle lights state (on/off).
Works with automatically enabled lights at night.

_Closes #478_

### CODE REVIEW

**Comment by StrixG** [comment]
Waits for #821.

**Comment by botder** [comment]
The decision in pull request #821 (**Pin down return value on failure**) is now settled.

**Comment by patrikjuvonen** [comment]
Great! Thank you for your PR.

**Comment by Einheit-101** [comment]
Nice nice!

**Pull request merged**
