### PR TITLE
Fix a few new parser issues

### PR DESCRIPTION
**Pull request by Pirulax**
This PR fixes some issues with the new parser not being able to push some comibination of types, because of the definition order of `Push`.

Also, it fixes some stupid case where `std::vector<CElement*>` was pushed as an array of bools (For whatever reason `Push<bool>` was preferred over the actual pointer `Push`)

### CODE REVIEW

**Comment by Pirulax** [comment]
Oopsie.
Edit: Fixed.

**Review by ghost — APPROVED** [review]

**Review by sbx320 — APPROVED** [review]
Not sure I like the solution as discussed on #development, but I don't have a better one either. Guess this works for the time being

**Comment by CrosRoad95** [comment]
i fixed my issues where i was trying to return map of vector of variant ect. previously it does not work

**Comment by Pirulax** [comment]
Yeah I dont like the solution either, but I dont have a better one sadly.

**Pull request merged**
