### PR TITLE
Nick completion + setting

### PR DESCRIPTION
**Pull request by Audifire**
Nickname Autocomplete with the wish to make it togglable

Patch for ID mantis 8734.

(Tab completion)

### CODE REVIEW

**Comment by sbx320** [comment]
Looks mostly fine to me, although I couldn't test it yet (since I'd need at least 2 players). 

One thing which looks a bit inefficient to me is splitting the entire string where we're only going to use the part after the last space. Just splitting at the last occurrence of ' ' would simplify this.

**Comment by Audifire** [comment]
Refactored it :D

**Comment by Audifire** [comment]
And the Tab is gone, too

**Comment by qaisjp** [comment]
It works, and it works well! Good job :)

(13/12/15 edit: [follow up](https://github.com/multitheftauto/mtasa-blue/commit/cc580a60c8105bb264d939d627af064f09874c82))

**Pull request merged**
