### PR TITLE
Fix #429: setCloudsEnabled affects moon and stars but not actual clouds

### LINKED ISSUE #429: Disabling clouds also disables the moon and stars
**Describe the bug**
If you disable clouds via setCloudsEnabled (client/server), the moon and stars disappear. The sun seems to be unaffected.

**To Reproduce**
1. Set night time or when the moon and stars are visible
2. Use setCloudsEnabled(false)
If you set it to true, the moon and stars appear again.

**Expected behavior**
Moon should not disappear.

**Screenshots**
N/A

**MTA Client (please complete the following information):**
1.5.6

**MTA Server (please complete the following information):**
1.5.6

**Additional context**
https://bugs.mtasa.com/view.php?id=9905

### PR DESCRIPTION
**Pull request by samr46**
Fixes #429 

Fixed incorrect memory address of clouds render (2 lines)

**New behavior preview:**

<details><summary>Night</summary>

</details>

<details><summary>Day</summary>

</details>

### CODE REVIEW

**Comment by patrikjuvonen** [comment]
Nice one, however high/normal clouds are now no longer affected (e.g. weather ID 10).

mta-screen_2019-05-10_23-46-12

I think the upside about this change however is the fact that we get to keep stars and the moon.

**Comment by samr46** [comment]
Interesting. I checked all weathers and missed it.

**Comment by patrikjuvonen** [comment]
I think one way would be to introduce a new parameter or even a new function maybe since the old way affects the moon and stars (which have nothing to do with our traditional thinking of clouds per se, other than cloud density blocking line of sight, but that doesn't make sense here).

**Comment by samr46** [comment]
It seems that it's another type of clouds. Looks like some kinda "horizon / skyline clouds".

**Comment by samr46** [comment]
Fixed it.
mta-screen_2019-05-11_01-24-08

**Review by qaisjp — APPROVED** [review]
Thanks!

**Comment by patrikjuvonen** [comment]
Thanks for seeing it through, seems to work fine now. Cheers!

**Review by patrikjuvonen — COMMENTED** [review]
Thanks for seeing it through, seems to work fine now. Cheers!

**Pull request merged**
