### PR TITLE
Add possiblity to change vehicle model dummies positions

### PR DESCRIPTION
**Pull request by forkerer**
This pull request aims to expand functionality added with https://wiki.multitheftauto.com/wiki/SetVehicleModelExhaustFumesPosition, instead of having ability to change only exhaust dummy position, it makes it possible to modify other dummies as well.
Most vehicles use only few of possible dummies, and some do differ between cars/planes in how they are used, but i tried to give all of them the most fitting description, ending with this dummies enum:
```c
enum eVehicleDummies        //lua enum
{
    LIGHT_FRONT_MAIN = 0,   //light_front_main
    LIGHT_REAR_MAIN,        //light_rear_main
    LIGHT_FRONT_SECONDARY,  //light_front_second
    LIGHT_REAR_SECONDARY,   //light_rear_second
    SEAT_FRONT,             //seat_front
    SEAT_REAR,              //seat_rear
    EXHAUST,                //exhaust
    ENGINE,                 //engine
    GAS_CAP,                //gas_cap
    TRAILER_ATTACH,         //trailer_attach
    HAND_REST,              //hand_rest
    EXHAUST_SECONDARY,      //exhaust_second
    WING_AIRTRAIL,          //wing_airtrail
    VEH_GUN,                //veh_gun
};
```

This pull request modifies setVehicleModelExhaustFumesPosition to use new system as well, all changes are saved, and properly restored after disconnecting from server.

Example image with changed exhaust,engine, and front seat positions:
image

This pull request adds 2 new lua functions:
```lua
    --Get dummy offset
    float, float, float getVehicleModelDummyPosition ( int modelID, vehicle-dummy dummy )
    --Set dummy offset
    bool setVehicleModelDummyPosition ( int modelID, vehicle-dummy dummy, float x, float y, float z )
```
[dummies.zip](https://github.com/multitheftauto/mtasa-blue/files/2389583/dummies.zip)

### CODE REVIEW

**Comment by ghost** [comment]
Please kindly attach a test resource.

**Comment by forkerer** [comment]
@saml1er attached it, sit in any car, write /draw to show every dummy position, do /move to start moving them

**Comment by ghost** [comment]
When my vehicle caught fire and was about to explode, one of the dummy allowed me to change the position of it. I could see the fire moving, good stuff. I also noticed that modifying position of SEAT_FRONT and SEAT_REAR will update its collision as well which is very useful but applies to some vehicles only. We can make these two functions model independent and more flexible after merging #480. Overall, good job.

**Comment by qaisjp** [comment]
Landed in [r14403](https://buildinfo.mtasa.com/?SHA=0716b383cd41f8e8e38620af77497d26c5020f12)

**Pull request merged**
