### PR TITLE
Skip nick and serial checks if the server is a debug build

### LINKED ISSUE #3908: Skip serial and nick checks in DEBUG mode
### Is your feature request related to a problem? Please describe.

I think it would be useful to skip checking whether a nickname or serial is already in use in DEBUG mode. The issue is that during testing or debugging crashes, when MTA crashes, the player is still considered to be on the server. Sometimes the player count shows 0, sometimes 1, but in reality, the server is empty. It's very frustrating to have to kick a ghost player on a local server after every crash just to be able to join. Until now, it was somewhat bearable because it didn't always happen, but after adding serial checks, it has become extremely annoying

Image

### Describe the solution you'd like

I'd like to work on crashes faster without having to kick the ghost player after every crash

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Security Policy

- [x] I have read and understood the Security Policy and this issue is not about a cheat or security vulnerability.

### PR DESCRIPTION
**Pull request by ghost**
Closes #3908

### CODE REVIEW

**Comment by tederis** [comment]
I don't think this is really needed. You can disable the check in `mtaserver.conf`. See `check_duplicate_serials`.

**Comment by ghost** [comment]
> I don't think this is really needed. You can disable the check in `mtaserver.conf`. See `check_duplicate_serials`.

I know, I was the one who implemented it and this idea was brought up by @FileEX, but regardless I don't think it's unnecessary, it's easier than having to manually turn it off in the config

**Comment by ghost** [comment]
But you're right that it's not the most important change, it can be omitted

**Comment by FileEX** [comment]
> I don't think this is really needed. You can disable the check in `mtaserver.conf`. See `check_duplicate_serials`.

Can I also disable nick checks?

**Comment by tederis** [comment]
> > I don't think this is really needed. You can disable the check in `mtaserver.conf`. See `check_duplicate_serials`.
> 
> Can I also disable nick checks?

I don't think so. From what I can see this PR doesn't turn off nick checks as well.

**Comment by ghost** [comment]
It was a mistake, it was supposed to disable nick checks as well. But it isn't really needed, we better solve the bug itself.

**Comment by FileEX** [comment]
Since no one will fix this bug anytime soon, this solution would be much better. I see nothing wrong with disabling nickname checks. If this approach is considered bad, then let's add a '`check_duplicated_nicks'` parameter to the mtaserver.conf as well.

**Pull request closed without merging**
