### PR TITLE
Engine pool functions

### PR DESCRIPTION
**Pull request by TheNormalnij**
After #3330 and #3275

The set function is implemented for building pool only.
```
number engineGetPoolCapacity(enum pool)
number engineGetPoolDefaultCapacity(enum pool)
number engineGetPoolUsedCapacity(enum pool)
boolean engineSetPoolCapacity('building', number newSize)
```

### CODE REVIEW

**Comment by Dutchman101** [comment]
Please resolve conflicts
@TheNormalnij

**Comment by TheNormalnij** [comment]
> Please resolve conflicts
> @TheNormalnij

done

**Comment by Dutchman101** [comment]
@TheNormalnij
> done

There's still a conflict in `mods/deathmatch/logic/CClientBuilding.h`

**Comment by TheNormalnij** [comment]
> There's still a conflict in `mods/deathmatch/logic/CClientBuilding.h`

It's a new one. Resolved

**Comment by Dutchman101** [comment]
This is quite a big change, and it appears no one's interested in reviewing it. Despite that, you did many passes over it yourself (kept improving upon it) and it's known your skills resulted in your own write access as well as not really producing bugs in other contributions. That's my reasoning for just going ahead with merge and saying it can be tested in nightly instead.

Thanks!

**Pull request merged**
