### PR TITLE
Add registerChatColor and unregisterChatColor functions

### PR DESCRIPTION
**Pull request by ghost**
This PR adds "registerChatColor" and "unregisterChatColor" functions.

```lua
bool registerChatColor(string colorName, string hexColorCode)
```

```lua
bool registerChatColor(string colorName, int r, int g, int b)
```

```lua
bool unregisterChatColor(string colorName)
```

Example:

```lua
local colorsToRegister = 
{
    ["red"] = "#ff0000",
    ["green"] = "#00ff00",
    ["blue"] = "#0000ff",
    ["custom"] = {0, 0, 210}
}

addEventHandler("onClientResourceStart", getResourceRootElement(), function()
    for colorKey, colorData in pairs(colorsToRegister) do
        local typeOfData = type(colorData)
        local colorKeyEx = string.format("[color=%s]", colorKey)

        if typeOfData == "string" then
            registerChatColor(colorKeyEx, colorData)
        else
            registerChatColor(colorKeyEx, unpack(colorData))
        end
    end
end)

addCommandHandler("testcolor", function(commandName, colorKey)
    if colorsToRegister[colorKey] then
        local colorKeyEx = string.format("[color=%s]", colorKey)

        outputChatBox(string.format("%sTesting color '%s'.", colorKeyEx, colorKey))
    end
end)

addCommandHandler("unregistercolor", function(commandName, colorKey)
    if colorsToRegister[colorKey] then
        local colorKeyEx = string.format("[color=%s]", colorKey)

        unregisterChatColor(colorKeyEx)
        outputChatBox(string.format("Unregistered color '%s'.", colorKey))
    end
end)
```

### CODE REVIEW

**Comment by TracerDS** [comment]
Whats the point of this PR?

**Comment by ghost** [comment]
Well, to add support for color keys in the chatbox. This can be done with lua as well, but doing it in C++ eliminates the overhead.

**Comment by ghost** [comment]
> Whats the point of this PR?

As I can see from the code and the example, it associates a color code with a name, which can then be used in the chatbox. I, on the other hand, think that this feature is not necessary, because it is very easy to implement it in Lua, and as this is a feature based on customization, it doesn't need to be implemented in MTA itself.

**Comment by ghost** [comment]
I quickly threw together the Lua equivalent of this Pull Request. As you can see, there are a total of 67 lines, so I still hold the opinion that it is unnecessary to implement this in the MTA.

```lua
local chatColors = {}
local chatColorsCode = {
    ["red"] = {
        colorR = 255,
        colorG = 0,
        colorB = 0
    },
    ["green"] = {
        colorR = 0,
        colorG = 255,
        colorB = 0
    },
    ["blue"] = {
        colorR = 0,
        colorG = 0,
        colorB = 255
    }
}

addEventHandler("onClientResourceStart", resourceRoot,
    function()
        for k, v in pairs(chatColorsCode) do
            if not v.colorR or type(v.colorR) ~= "number" then
                v.colorR = 0
            end

            if not v.colorG or type(v.colorG) ~= "number" then
                v.colorG = 0
            end

            if not v.colorB or type(v.colorB) ~= "number" then
                v.colorB = 0
            end

            chatColors[k] = string.format("#%02X%02X%02X", v.colorR, v.colorG, v.colorB)
        end
    end
)

_outputChatBox = outputChatBox
function outputChatBox(outputText, outputColorR, outputColorG, outputColorB, outputColorCoded)
    if not outputText or type(outputText) ~= "string" then
        return
    end

    if not outputColorR or type(outputColorR) ~= "number" then
        outputColorR = 0
    end

    if not outputColorG or type(outputColorG) ~= "number" then
        outputColorG = 0
    end

    if not outputColorB or type(outputColorB) ~= "number" then
        outputColorB = 0
    end

    if outputColorCoded then
        outputText = utf8.gsub("%[color=(.-)%]",
            function(outputTextColor)
                return chatColors[outputTextColor] or outputTextColor
            end
        )
    end

    outputChatBox(outputText, outputColorR, outputColorG, outputColorB, outputColorCoded)
end
```

**Comment by TracerDS** [comment]
> Well, to add support for color keys in the chatbox. This can be done with lua as well, but doing it in C++ eliminates the overhead.

you can already use colors in chat

**Comment by ghost** [comment]
> you can already use colors in chat

Yes, it's a tiny utility. See the Lua code above your comment, it shows how it works more simply.

**Comment by ghost** [comment]
> I quickly threw together the Lua equivalent of this Pull Request. As you can see, there are a total of 67 lines, so I still hold the opinion that it is unnecessary to implement this in the MTA.
> 

I know that it is possible in lua, here is my code:

```lua
local ColorTable = {
    ["[color=test]"] = "#ff0000",
};

function ChatMessageHandler(Text, R, G, B)
    for Color, Replacement in pairs(ColorTable) do
        if utf8.find(Text, Color) then
            outputChatBox(utf8.gsub(Text, Color, function(Character)
                return Replacement;
            end), R, G, B, true);

            cancelEvent();
            break
        end
    end
end
addEventHandler("onClientChatMessage", root, ChatMessageHandler);
```

but doing it in C++ would eliminate the overhead. But if you find it unnecessary then I guess I can close the pull request.

**Comment by ghost** [comment]
You don't have to close the Pull Request, let's wait for other people's opinions, because this is just my personal opinion, maybe someone else will have a completely different opinion about it. However, it is certain that such a function does not fit into the MTA's game engine-like behavior.

**Comment by CrosRoad95** [comment]
xD useless

**Pull request closed without merging**
