### PR TITLE
Remove some startup resources

### PR DESCRIPTION
**Pull request by CrosRoad95**
In case someone is lazy :)

### CODE REVIEW

**Comment by qaisjp** [comment]
Why?

**Comment by patrikjuvonen** [comment]
Won't fix.

**Comment by jlillis** [comment]
I think we should take a second look at this - some of these startup resources aren't in common use with most players and don't need to be running by default. I would add ipb and performancebrowser to that list.

**Comment by Dutchman101** [comment]
> I would add ipb and performancebrowser to that list

Bad idea.. ipb recently got added to auto startup list, and such things only get added if others think it's a good idea and if there are reasons for it.

That was issue #1217 (see discussion about ipb being added)
Performance browser is for similar reasons probably also a keeper, to warn and alert server admins that regularly use webadmin about bad scripts and lock ups.

**Pull request closed without merging**
