### PR TITLE
Show a warning if a script modifies a non-joined player

### PR DESCRIPTION
**Pull request by Necktrox**
**Issue:** [9610: Setting player name in an onPlayerConnect event handler results in desync](https://bugs.mtasa.com/view.php?id=9610)

### CODE REVIEW

**Comment by qaisjp** [comment]
Instead of adding `VerifyPlayerIsJoinedUsage` into every method in the `Player -> Ped -> Element` tree, would it be possible to inject it?

The fact that almost all element/ped/player Lua functions are in their own class should make this easier.

Also, perhaps rename `VerifyPlayerIsJoinedUsage` to `VerifyPlayerJoined` or `CheckPlayerJoined`?

**Comment by Necktrox** [comment]
Not every method changes the `CPlayer` (e. g. all the GetPlayerFoo) - I checked all the methods to be sure and only included the call in the methods, which actually modify the player.

A function name should be clear and tell what it does without looking into the code. My added function checks if the element is a player and if the player has joined the game (`isJoined`). I have nothing against changing the name, because I don't really like the name, but it should include "Print" and/or "Warn".

**Comment by qaisjp** [comment]
Fair point about the getters. :+1:

**Comment by qaisjp** [comment]
@Necktrox feel free to merge this if you've tested it 👍

**Pull request merged**
