### PR TITLE
Add cef upgrade script

### PR DESCRIPTION
**Pull request by qaisjp**
Passing `upgrade` should say this (bonus: windows not necessary)

```
➜ ./utils/premake5-macos install_cef upgrade
Running action 'install_cef'...
Checking opensource.spotify.com for an update...
Does version '80.1.2+g9d2a31e+chromium-80.0.3987.149' look OK to you? (Y/n) y
New CEF hash is:	6cbf925620d686cae6549a40bb93ad1fd358a8eb80ec09c9313551c15930fbb0
Update `install_cef.lua` file? (Y/n) y
```

if you're on windows it will then proceed to install that new cef version

and `git diff` produces the following patch

```diff
diff --git a/utils/buildactions/install_cef.lua b/utils/buildactions/install_cef.lua
index 252cd8788..bea91be20 100644
--- a/utils/buildactions/install_cef.lua
+++ b/utils/buildactions/install_cef.lua
@@ -8,8 +8,8 @@ local CEF_URL_PREFIX = "http://opensource.spotify.com/cefbuilds/cef_binary_"
 local CEF_URL_SUFFIX = "_windows32_minimal.tar.bz2"

 -- Change here to update CEF version
-local CEF_VERSION = "80.0.4+g74f7b0c+chromium-80.0.3987.122"
-local CEF_HASH = "8fd8e24af196f00feaaa1553496bae99d8196ba023d0dd0fe44efeee93b04dfc"
+local CEF_VERSION = "80.1.2+g9d2a31e+chromium-80.0.3987.149"^M
+local CEF_HASH = "6cbf925620d686cae6549a40bb93ad1fd358a8eb80ec09c9313551c15930fbb0"^M

 function make_cef_download_url()
        return CEF_URL_PREFIX..http.escapeUrlParam(CEF_VERSION)..CEF_URL_SUFFIX
```

If CEF is already up to date (i.e CEF_VERSION matches what the server says)

```
➜ ./utils/premake5-macos install_cef upgrade
Running action 'install_cef'...
Checking opensource.spotify.com for an update...
CEF is already up to date (80.1.2+g9d2a31e+chromium-80.0.3987.149).
```

Also now we do a consistency check after download too

### CODE REVIEW

**Comment by qaisjp** [comment]
"but it works on my machine!"

my pc too

**Comment by qaisjp** [comment]
ok, this is ready for review 👍 

This change

> Also now we do a consistency check after download too

caused issues with CI. It basically boiled down to some inconsistency in executing things in powershell. So i've reverted to the old method of generating SHA256 hashes

**Comment by jushar** [comment]
I'm currently not able to test it, but it looks good to me. If it works, feel free to merge it!

**Comment by qaisjp** [comment]
Thanks! Next task is automated pull requests :-)

**Comment by qaisjp** [comment]
Next task is automated pull requests :-)

**Pull request merged**
