### PR TITLE
Fix server shutdown on kick

### PR DESCRIPTION
**Pull request by MishkaCezarj**
Fix server shutdown on kick:

function MyKick(player)
local player = client
kickPlayer(player, "Server", "My kick")
end
addCommandHandler("mykick", MyKick)

Before you go ahead and create a pull request, please make sure:

* [ ] [your code follows the coding guidelines](https://wiki.multitheftauto.com/index.php?title=Coding_guidelines)
* [ ] your commit messages are informative ("update file.cpp" is unhelpful. "fix missing model in getVehicleNameFromModel" is helpful)

If your work is incomplete, **do not prefix your pull request with "WIP"**, instead
create a _draft_ pull request: https://github.blog/2019-02-14-introducing-draft-pull-requests/

Thank you!

### CODE REVIEW

**Comment by TracerDS** [comment]
~~`client` is nil. `kickPlayer` will throw error~~
nvm, providing `nil` **does** crash the server for some reason

**Comment by CrosRoad95** [comment]
image
with
```lua
function MyKick(player)
  kickPlayer(nil, "Server", "My kick")
  end
  addCommandHandler("mykick", MyKick)
```
doesn't crash

**Comment by TracerDS** [comment]
> image with
> 
> ```lua
> function MyKick(player)
>   kickPlayer(nil, "Server", "My kick")
>   end
>   addCommandHandler("mykick", MyKick)
> ```
> 
> doesn't crash

It crashes for v1.6-21778 🙁

**Comment by MishkaCezarj** [comment]
> > изображениес
> > ```lua
> > function MyKick(player)
> >   kickPlayer(nil, "Server", "My kick")
> >   end
> >   addCommandHandler("mykick", MyKick)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > не падает
> 
> Вылетает для v1.6-21778🙁

да, забыл сказать что вылетает только на 1.6, либо на самой последней 1.5.9

**Comment by patrikjuvonen** [comment]
Thanks. This should have been created as an issue instead.

The solution is not to delete what has been added there, but to fix it.

**Pull request closed without merging**
