### PR TITLE
Disable Skimmer

### PR DESCRIPTION
**Pull request by ghost**
Temporary "fix" for #1151. ~~I'm still able to create skimmer in map editor. Does anybody know why?~~

### CODE REVIEW

**Comment by theSarrum** [comment]
I think this would break existing scripts.

**Comment by ccw808** [comment]
What does "Temporary "fix"" mean?

**Comment by Lpsd** [comment]
I don't think this is needed, why would we completely disable the Skimmer? The next step after this "temporary fix" is fixing the glitch, so I don't see the purpose of this.

**Comment by ghost** [comment]
> 
> 
> What does "Temporary "fix"" mean?

I should've explained it better. It's not a fix. We're just removing the skimmer completely. I don't know how to reproduce the bug. By removing skimmer, it will avoid the client from crashing when approaching it. Maybe we should just revert back to VS2017?

**Comment by qaisjp** [comment]
Technically speaking, neither reverting or removing the skimmer are 'fixes'.

Reverting back to vs2017 is probably more preferable in _getting 'nightly releases' suitable for public use_, so we can keep developing elsewhere.

See further info in https://github.com/multitheftauto/mtasa-blue/issues/1151#issuecomment-597128153

**Pull request closed without merging**
