### PR TITLE
Clean up  'Client Core' project round 1

### PR DESCRIPTION
**Pull request by Moris-Onz**
Clean up  'Client Core ' project round 1, i hope you like it

### CODE REVIEW

**Comment by CrosRoad95** [comment]
when you replace "CCore::GetSingleton", did you remove this method? also simillar case with "graphics" class members, if you use global, remove class members. It's hard to see it in changes

**Comment by Pirulax** [comment]
lgtm
haven't tested though

**Comment by Moris-Onz** [comment]
> при замене "CCore::getSingleton" вы удалили этот метод? аналогичный случай с членами класса "graphics", если вы используете global, удалите членов класса. Трудно увидеть это в изменениях

I removed Singleton from classes

**Comment by Moris-Onz** [comment]
They are not particularly needed in these classes, but they take up a lot of space in the code and dll

**Comment by sbx320** [comment]
Please stop submitting pointless bulk renaming PRs that don't actually improve anything.

**Pull request closed without merging**
