### PR TITLE
setCameraViewMode for trains

### PR DESCRIPTION
**Pull request by ZReC**
Camera view modes for trains

### CODE REVIEW

**Comment by ZReC** [comment]
I have a question.. This was turned off for some reason?

**Comment by lopezloo** [comment]
Maybe better idea would be fixing `setCameraViewMode` to make it work with trains?

**Comment by ZReC** [comment]
It could be, we have to investigate about it

**Comment by lopezloo** [comment]
```c++
// Disable automatic switching cinematic camera for trains
MemSet ( (void*) 0x52A50B, 0x90, 0x52A536 - 0x52A50B );

// Enable camera view mode switching in trains
MemPut < BYTE > ( 0x528152, 18 );
MemSet ( (void*) 0x52815B, 0x90, 5 );
```

Now you can switch camera view mode in trains like in any other vehicle.

**Comment by ZReC** [comment]
I like your idea more, now I'm going to try it.

## Works very fine!

Update! (Sorry for doing 2 commits I was wrong because I was in a hurry)

**Pull request merged**
