### PR TITLE
New function setElementLighting

### PR DESCRIPTION
**Pull request by FileEX**
This PR adds the ``setElementLighting`` function, which allows setting custom lighting for a specific element.

### CODE REVIEW

**Review by tederis — APPROVED** [review]

**Comment by Fernando-A-Rocha** [comment]
Can u showcase this in action?

**Comment by FileEX** [comment]
> Can u showcase this in action?

I don't think there's much to show here. You can simply adjust the brightness of elements like peds, vehicles, or objects

**Comment by Fernando-A-Rocha** [comment]
> > Can u showcase this in action?
> 
> I don't think there's much to show here. You can simply adjust the brightness of elements like peds, vehicles, or objects

Ah I think a more appropriate name would be
setElementLightBrightness or setElementLightIntensity ?

**Comment by FileEX** [comment]
> > > Can u showcase this in action?
> > 
> > 
> > I don't think there's much to show here. You can simply adjust the brightness of elements like peds, vehicles, or objects
> 
> Ah I think a more appropriate name would be setElementLightBrightness or setElementLightIntensity ?

This function is the missing counterpart to ``getElementLighting``. The names of these functions can be changed if someone wants, and the current ones can be marked as deprecated, although I think these names are ok

**Comment by tederis** [comment]
I agree with the FileEX's arguments. `setElementLighting` and `getElementLighting` deal with the same value. And if someone wants to change a function's name then it must be applied to both functions.

**Comment by AlexTMjugador** [comment]
Now that this feature has been merged for a few days, it would be great to have a wiki article documenting it.

Also, in my opinion, a well-written wiki article should clearly explain how often the game computes lighting values for elements. This information is needed for script developers to decide whether to call it one-time or on every frame. The one-time approach is sufficient if the game doesn't frequently recalculate lighting values, but if the game recalculates lighting values every frame, calling it on each frame would be necessary for an override to have visible effects, which is also a reasonable design choice for the GTA rendering engine.

**Comment by FileEX** [comment]
> Now that this feature has been merged for a few days, it would be great to have a wiki article documenting it.

The article will be published when the build is released; I always make sure of that.

**Pull request merged**
