### PR TITLE
Added quality argument for dxCreateFont

### PR DESCRIPTION
**Pull request by Kernell**
mta-screen_2015-04-24_20-11-53

### CODE REVIEW

**Comment by ccw808** [comment]
What is the advantage of not using PROOF_QUALITY ?

**Comment by Kernell** [comment]
@ccw808 
Each of his preference for the perfect font. I dislike PROOF quality, it is terrible. In the function i use proof as default quality. Who wants to, can be used for example cleartype.
Even DEFAULT quality looks better than PROOF. See the screenshot above.

**Comment by ccw808** [comment]
Can you make the screenshot with a black background?

**Comment by Kernell** [comment]
@ccw808 
mta-screen_2015-04-24_23-38-26
mta-screen_2015-04-25_00-01-29
mta-screen_2015-04-25_00-03-23

**Comment by Kernell** [comment]
@ccw808 Fonts can vary depending on the context. I only give the opportunity to choose quality. Not all fonts are displayed correctly under some settings.

**Comment by ccw808** [comment]
Ok, thanks for the info.
About the patch itself:
Can you change strQuality to an enum + ReadEnumString (like used in CLuaFunctionDefs::dxSetTestMode) ?

**Comment by Kernell** [comment]
@ccw808 
Yeah, I thought to do so initially. But I thought it was a waste of resources.
I'll do it tomorrow.

**Comment by Kernell** [comment]
@ccw808 
Done

P.S.On a white background better seen a difference

mta-screen_2015-04-26_19-45-29

**Pull request merged**
