### PR TITLE
Event onPlayerTryConnect

### PR DESCRIPTION
**Pull request by CrosRoad95**
Added event "onPlayerTryConnect" with arguments: reason, nick, ip, serial, version
reasons:
bad_version, wrong_password, join_flood, account_is_banned, ip_is_banned, client_version_is_below_minimum, invalid_nickname, nick_already_in_use

I added this becose, next i add option to disable default logs, if someone use mysql, then ignore server.log or look into server.log for important logs.

### CODE REVIEW

**Comment by dsmatias** [comment]
Hello, can anyone help me with how can I create a steering smooth whell?

Also known as: Steering wheel help / assist
-

Example:

Https://youtu.be/zu8jZXy2BZg

**Comment by Timic3** [comment]
This should be put into onPlayerConnect event. Having two events which (nearly) do the same thing is a bit confusing.

**Comment by CrosRoad95** [comment]
i made this in separated event to make it compatible with previous versions of mta, and i dont prefer to make 1 event which have few applications

**Comment by qaisjp** [comment]
Thanks for the pull request.

I'm not too sure about this extra event, especially considering the very similar event function signatures. I've created [this feature report](https://bugs.mtasa.com/view.php?id=9674) outlining a possible solution to what you're looking for.


Here's some feedback:

- Use an enum instead of raw strings
- Use desktop.github.com
- Try to avoid superfluous changes that affect random files
- Maybe the event would sound better as `onPlayerConnectFailure`

**Pull request closed without merging**
