### PR TITLE
Fix #863 warpPedIntoVehicle fails when there are too many vehicles streamed in

### LINKED ISSUE #863: warpPedIntoVehicle doesn't work when there are too many vehicles streamed in
**Describe the bug**
I have a map that contains over 500+ vehicles and players can spawn vehicles themselves with _/vehicle_ command. This command also warps players into newly created vehicle. In any area which has vehicles created with the .map file, players can not warp into this newly created vehicle because warpPedIntoVehicle() doesn't do its job.

**To reproduce**
1. Create a map file that contains too many cars.
2. Test warpPedIntoVehicle to a vehicle that's created with createVehicle(...)
3. You'll see it's not going to warp into the vehicle.

**Expected behaviour**
I expect my ped warp into vehicle even though the area is full of vehicles or the .map file has 60000 vehicles.

**Screenshots**
 - no screenshots. -

**Version**
I'm using MTA 1.5.6 on Linux with Wine.

### PR DESCRIPTION
**Pull request by ghost**
**Context**

When the vehicle's memory pool reaches its limit, then the streamer needs to stream out a vehicle to make room for a new vehicle. This causes a small delay when we call `warpPedIntoVehicle`, and the game detects that the ped is supposed to be in a vehicle that doesn't exist, so it sets the occupied state of ped to false. When that new vehicle is finally created after the small delay, too bad the ped doesn't occupy the vehicle anymore and isn't warpped back into the vehicle.

### CODE REVIEW

**Comment by ghost** [comment]
Oh, it turns out #863 and #1337 are related. Should I fix it? @botder

**Review by qaisjp — APPROVED** [review]
Looks good. What if the player is being warped into *a different* vehicle whilst it's previous vehicle is momentarily unloaded? (Is that even possible?)

**Comment by ghost** [comment]
> 
> 
> Looks good. What if the player is being warped into a different vehicle whilst it's previous vehicle is momentarily unloaded? (Is that even possible?)

I believe that scenario is handled by warpPedIntoVehicle function. 
```
// Toss the previous player out of it if neccessary
if (CClientPed* pPreviousOccupant = pVehicle->GetOccupant(uiSeat))
    RemovePedFromVehicle(pPreviousOccupant);
```
The vehicle occupant at a specific seat is kicked out of the vehicle when warpPedIntoVehicle is called and the occupant array of the previous vehicle is updated in CClientVehicle, so if the previous vehicle streams in before the new vehicle, it won't make a difference since it won't have the occupants in the array. And finally, when the new vehicle streams in, it will go through its occupant array and warp all peds into the vehicle.

The code at the bottom of `CClientGame::UpdateVehicleInOut` function looks like a hack to me, and it's responsible for the bug. Someone probably tried fixing a bug and didn't realize that it caused other bugs to pop up.

If you mean actual GTA internal warp, then obviously no. GTA SA gameplay logic runs on a single thread ;d

**Comment by PlatinMTA** [comment]
I'm gonna test tomorrow (or later) if this fixes #1337, i hope it does.

Thanks.

**Comment by ghost** [comment]
@PlatinMTA It doesn't fix #1337. I'll write a separate fix for it tomorrow.

**Pull request merged**
