### PR TITLE
Fix game freeze & updated BASS libraries

### PR DESCRIPTION
**Pull request by Dutchman101**
BASS.dll fixes:
- Fixed bug in BASS.dll that can cause game freezes when a resource seeks corrupted .ogg files (as in issue #1718)
- Avert low memory crash on offset 0000184e (reported by MTA)
- Fix failed alloc (in Ogg Vorbis decoder) crashes on 0000d013 and 0000d79c (reported by MTA)

bass_fx.dll fixes:
- Fixed a bunch of failed reallocs that were remaining after the last update (to stop memory corruption)
Further hardening against out of mem, it should now result in audio glitches (due to no buffer space) rather than crashes

bass_aac.dll fixes:
- Avert low memory crash on offset 000020dc (reported by MTA - the only change)

NOTE: after this PR gets merged, i advise no one gets the latest nightly until at least the Microsoft Defender false positive on BASS.dll has been resolved (already reported it). They usually take less than a day.

### CODE REVIEW

**Comment by qaisjp** [comment]
Do you have download links for the dlls?

**Comment by Dutchman101** [comment]
> Do you have download links for the dlls?

yeah, i forgot.. here:

[http://www.un4seen.com/stuff/bass.zip](http://www.un4seen.com/stuff/bass.zip)
[http://www.un4seen.com/stuff/bass_aac.zip](http://www.un4seen.com/stuff/bass_aac.zip)
[http://www.un4seen.com/stuff/bass_fx.zip](http://www.un4seen.com/stuff/bass_fx.zip)

**Review by qaisjp — APPROVED** [review]
LGTM / verified, although if there are Windows Defender problems I would recommend waiting for the dlls to be whitelisted before merging.

**Comment by Dutchman101** [comment]
> LGTM / verified, although if there are Windows Defender problems I would recommend waiting for the dlls to be whitelisted before merging.

I agree

**Comment by Dutchman101** [comment]
It's solved, see below

fp

**Pull request merged**
