### PR TITLE
WIP: Fix lack of distinction between left and right modifier keys in getKeyState()

### LINKED ISSUE #367: getKeyState('lshift') returns true for 'rshift'
**Describe the bug**
`getKeyState('lshift')` returns `true` if `rshift` is pushed down.

This happens for "lshift", "lalt", "lctrl", "rshift", "ralt", "rctrl" as well.

**Expected behavior**
It should work properly.

**Additional context**
From https://bugs.mtasa.com/view.php?id=5876

### PR DESCRIPTION
**Pull request by 4O4**
Fixes #367

### CODE REVIEW

**Comment by 4O4** [comment]
Putting this on hold because of what I reported here: https://github.com/multitheftauto/mtasa-blue/issues/367#issuecomment-436009853

**Comment by qaisjp** [comment]
> Putting this on hold because of what I reported here: [#367 (comment)](https://github.com/multitheftauto/mtasa-blue/issues/367#issuecomment-436009853)

Are you saying that `V_LALT`, `V_RALT`, `V_LCTRL` and `V_RCTRL` don't work?

**Comment by ccw808** [comment]
Seems code changes are required as well: https://stackoverflow.com/questions/15966642/how-do-you-tell-lshift-apart-from-rshift-in-wm-keydown-events

**Comment by 4O4** [comment]
> > Putting this on hold because of what I reported here: [#367 (comment)](https://github.com/multitheftauto/mtasa-blue/issues/367#issuecomment-436009853)
> 
> Are you saying that `V_LALT`, `V_RALT`, `V_LCTRL` and `V_RCTRL` don't work?

I mean `getKeyState()` works correctly, but `onClientKey` event is totally fckd up after changes from the second commit :smile: For me it stopped reporting alt, ctrl and letters as well. Numpad keys report letters instead. 

I'm gonna dig into that ~spaghetti~ complex code later to see what's going on, there are some shady things going on in CKeyBinds (some are even explicitly labelled as `HACK`s).

**Comment by qaisjp** [comment]
I think this is abandoned, so I'm closing it, but please do re-open if you are working on it!

**Pull request closed without merging**
