### PR TITLE
Update credits

### PR DESCRIPTION
**Pull request by patrikjuvonen**
This update is preliminary and is subject to change. We will merge these changes in the next release.

## Summary
- Update credits
- Added missing software/libraries to credits

### New Patch Contributors
- BCG2000 (@BCG2000)
- DarkDrifter Nacim (@darkdrifter)
- Fernando Rocha (@Fernando-A-Rocha)
- gta191977649 (@gta191977649)
- Inder00 (@Inder00)
- JessePinkman (@bum8hj)
- lyncon
- Merlin (@Merlin)
- Santi (@matheustkn)
- TFP-dev (@TFP-dev)
- turret001 (@turret001)
- vahook (@vahook)

### New Special Thanks
- headfonez (MTA 0.x dev)
- trx (MTA 0.x dev)

Are you missing from credits, or wish to update your existing entry? Please comment in this pull request with your preferred name.

Thank you all for your contributions!

### CODE REVIEW

**Review by matheustkn — COMMENTED** [review]
Change name to Santi

**Comment by bum8hj** [comment]
Lmao, thanks. I'd like the name **JessePinkman** instead

**Comment by PlatinMTA** [comment]
I would like to have mine changed from PlatinMTA to just Platin, thank you!

**Comment by r12750** [comment]
I wanted to thank you for being on the list, I would also like to change my name from "starmakers" to "ghostkc12"

**Comment by tederis** [comment]
I think TEDERIs(instead of tederis) would be more recognizable for me.

**Comment by F2BShady** [comment]
good lucky

**Comment by darkdrifter** [comment]
Hello, I'd like the name "DarkDrifter Nacim". Thanks!

**Comment by r12750** [comment]
> I wanted to thank you for being on the list, I would also like to change my name from "starmakers" to "ghostkc12"

Last request, I would like you to change my name "ghostkc12" to "lyncon" and remove mention that was given to this account, just leave the name

**Comment by PlatinMTA** [comment]
Hi patrik, you should take this into account #2898

**Pull request merged**
