### PR TITLE
Add bRelative argument to getCursorPosition() and fix inaccurate 3D Positions being returned

### PR DESCRIPTION
**Pull request by Pirulax**
Partially fixed #5226 in [this commit](https://github.com/multitheftauto/mtasa-blue/commit/21ee6b7a6ac4002e3e659e5ac38f02b44f3a64ab)
Totally fixed it in [this commit](https://github.com/multitheftauto/mtasa-blue/pull/205/commits/2beb0277469eb7739818d2b01f1964b6185646f0)

Added feature to retrieve non-relative positions with getCursorPosition(), because relative positions are nonsense, and was requested as a feature in #9885.

I've tested everything before the PR, so everything should be just fine.

This is my first PR into this repo, so I may made some mistakes(mostly because I never worked with C++ before)

### CODE REVIEW

**Comment by Pirulax** [comment]
Thinked about it:
I think I'll totally fix #5226 tomorrow(so basically today(its 2:09 here)), gonna commit that.

**Comment by Pirulax** [comment]
Thats it.
Modified the PR name.

**Comment by qaisjp** [comment]
Thanks for your pull request.

It appears that your PR makes two changes in one that should probably be kept separate.

Why do you need absolute positions in `getCursorPosition`?

**Comment by Pirulax** [comment]
Because everytime I write a script that has hovers in it(so basically I need cursor position) I need to convert relative positions back to absolute. 
I'll add this note to the mantis site too.

**Comment by Pirulax** [comment]
Should I separate them somehow?
Or its ok for now?

**Comment by Pirulax** [comment]
Any update?

**Comment by qaisjp** [comment]
> Should I separate them somehow?
> Or its ok for now?

It should be OK for now.

I'm trying to think of a better . Something like splitting `getCursorPosition` into `x, y getScreenCursorPosition(bRelative)` and `x, y, z getWorldCursorPosition(bCheckForCollision)`.

**Comment by Pirulax** [comment]
I could do it that way too, but since getCursorPostion() already returns x, y and x, y, z it would make no sense.
Or we would just make getCursorPosition() deprecated?

**Comment by qaisjp** [comment]
The idea would be to eventually deprecate the "old" getCursorPosition...

What do the other devs think?

**Comment by Pirulax** [comment]
Actually, that would be a pretty good idea.
Mostly because when you use vectors you need to create variables and then declare the vectors.
But with introducing the mentioned functions it would be much "easier".

**Comment by patrikjuvonen** [comment]
It's kind of a double edged sword in my opinion. I think it's nice if they were separate but again some scripts do benefit for getting all of that in one function call.

I tested this patch. Works fine.

**Comment by Pirulax** [comment]
Any update, qaisjp?

**Comment by ghost** [comment]
The code looks absolutely fine. I like qaisjp's idea on splitting the function and deprecating `getCursorPosition`. Can you do it @Pirulax ?

**Comment by Pirulax** [comment]
I think so.

**Comment by Pirulax** [comment]
It should be working, im not sure.
Mainly because my repo is fucked up for some reason, and it keeps throwing errors that it cannot found IFP shit.
But haven't seen any errors that are talking about cursor funcs.
But test it.

**Comment by patrikjuvonen** [comment]
Should also deprecate it in `Server\mods\deathmatch\logic\CResourceChecker.Data.h` by adding the old one with replacement to the `clientDeprecatedList`.

Also it seems you completely deleted the `getCursorPosition` function or am I missing something? We should still have it for backwards compatibility, but just mark it as deprecated for the end users.

**Comment by Pirulax** [comment]
Dont wanted to deprecate because Im not sure when it'll be removed(getCursorPosition) and when this function will be added. 
Also, we should add a min-client-version for getCursor(World/Screen)Position.

**Comment by Pirulax** [comment]
yey... 
im totally noob /w git

**Comment by Pirulax** [comment]
fixed it hope

**Comment by Pirulax** [comment]
Could someone rerun appveyor here?

**Comment by Citizen01** [comment]
AppVeyor failed to build **after** your revert commit 0cfd01c
**EDIT:** hmmm it actually failed to upload the result of the build, your code compiled fine after the revert

**Comment by Pirulax** [comment]
Yeah, this is why I asked it to be rerun.

**Comment by patrikjuvonen** [comment]
This PR is empty (https://github.com/multitheftauto/mtasa-blue/pull/205/files). Please recommit anything relevant.

**Review by patrikjuvonen — CHANGES_REQUESTED** [review]
This PR is empty (https://github.com/multitheftauto/mtasa-blue/pull/205/files). Please recommit anything relevant.

**Pull request closed without merging**
