### PR TITLE
0006867: Fix by adding a function to manually do collision detection

### PR DESCRIPTION
**Pull request by CrosRoad95**
Fix for [#6867](https://bugs.mtasa.com/view.php?id=6867)
Type: server and clientside
Syntax: `bool doHitDetection( colshape )`
Should be called after created new colshape, then every element inside will be detected.

Example test clientside
```lua
addEventHandler ( "onClientColShapeHit", root, function(element)
  iprint("hit",element,getTickCount())
end )
a = createColSphere(-2422.72070, -608.78345, 132.56250, 50)
iprint("now",getTickCount())
doHitDetection(a)
```

test serverside
```lua
addEventHandler ( "onColShapeHit", root, function(element)
  iprint("server hit",element,getTickCount())
end )
a = createColSphere(-2422.72070, -608.78345, 132.56250, 50)
iprint("now",getTickCount())
doHitDetection(a)
```

### CODE REVIEW

**Comment by Pirulax** [comment]
Whats iprint?
Is that a custom function?

But to be on-topic:
I think you should just add an argument to setElementPosition, like bDoHitDetection = false

**Comment by qaisjp** [comment]
https://wiki.mtasa.com/wiki/iprint

**Comment by Pirulax** [comment]
Thanks!

**Comment by qaisjp** [comment]
Smart solution.

**Comment by ccw808** [comment]
Is doHitDetection required server side?

**Comment by CrosRoad95** [comment]
i don't know do this function is required serverside

**Comment by NmLa0s** [comment]
why DoHitDetection = false , required please

**Comment by ccw808** [comment]
Instead of a new function, I suggest we add an optional `bool conformHitDetection` parameter to create colshape functions.
When true, hit detection is done automatically.

**Comment by botder** [comment]
Introducing a new function, which will effectively be called once and not more, is senseless, unless proven otherwise.

I assume this functionality is meant for usage with `getElementsWithinColShape` to get the non-moved elements inside the colshape. I would rather add a parameter to include the non-moved elements.

When this issue is all about getting elements in range to a position, then a new function for this specific problem should be added, which avoids the collision shape. For example  
`getElementsInRange(float x, float y [, float z ], float radius [, string elementType = nil])`.

**Comment by Citizen01** [comment]
It is also to trigger "on(Client)ColShapeHit" if the colshape is created in top of an existing element.
But then, like ccw said an optional `bool conformHitDetection` parameter is good enough and imo better than a new function.
Also, for me, it should have been like that by default, this PR could be seen as a fix for the events not being triggered.

**Comment by Pirulax** [comment]
I'd be happy if this gets merged

**Comment by qaisjp** [comment]
What if we automatically performed the hit detection for resources with a certain minversion?

**Comment by ccw808** [comment]
`min_mta_version` can be automatically increased with the upgrade command, and the upgrade command should not change script behaviour. I think adding an extra parameter to `createColSphere` etc. would be preferable.

**Comment by samr46** [comment]
Also there is no hit detection in SpawnVehicle and RespawnVehicle. I don't want to create new PR for 2 lines. I think you can add this since your PR related to collision detection :)

`m_pColManager->DoHitDetection(pVehicle->GetPosition(), pVehicle);`

By the way at this moment it's possible to fix it by calling setElementPosition after (re)spawnVehicle with a small position change.

**Pull request closed without merging**
