### PR TITLE
Fix #2965: sourceResourceRoot is incorrect in event handlers

### LINKED ISSUE #2965: sourceResourceRoot is incorrect in event handlers
### Describe the bug

Global variable `sourceResourceRoot` is okay when you call an exported function, but if you try to call the same function as event handler, `sourceResourceRoot` will unexpectedly become a dynamic map element of first resource.

### Steps to reproduce

1. Start both attached resources.
2. Execute command `runtest`. Resource 1 will call resource 2 in two different ways: by export and by event.
3. View clientscript log for results.
[Test resources.zip](https://github.com/multitheftauto/mtasa-blue/files/11222651/Test.resources.zip)

### Version

Client: v1.5.9-release-21630 (Windows 7, 64-bit)

### Additional context

_No response_

### Relevant log output

```shell
[2023-04-13 20:19:30] INFO: "thisRes"    resource[test_res1]
[2023-04-13 20:19:30] INFO: "thisRoot"    elem:resource9CF9C418

[2023-04-13 20:19:30] INFO: "export_test_2()"    "by export"
[2023-04-13 20:19:30] INFO: "source"    nil
[2023-04-13 20:19:30] INFO: "sourceResource"    resource[test_res1]
[2023-04-13 20:19:30] INFO: "sourceResourceRoot"    elem:resource4E3C2E68

[2023-04-13 20:19:30] INFO: "export_test_2()"    "by event"
[2023-04-13 20:19:30] INFO: "source"    elem:resource719E1E80
[2023-04-13 20:19:30] INFO: "sourceResource"    resource[test_res1]
[2023-04-13 20:19:30] INFO: "sourceResourceRoot"    elem:map62BE7A08

[2023-04-13 20:19:30] INFO: "eventCall"    true
```

### Security Policy

- [X] I have read and understood the Security Policy and this issue is not security related.

### PR DESCRIPTION
**Pull request by TracerDS**
Currently MTA is pushing **dynamic** resource root element instead of normal resource root element.
Changing it from `GetResourceDynamicEntity` to `GetResourceEntity` fixes the issue

### CODE REVIEW

**Comment by CrosRoad95** [comment]
i see one problem with this fix: people may already depend on this bug in their existing resources so now you are breaking them

**Comment by TracerDS** [comment]
> i see one problem with this fix: people may already depend on this bug in their existing resources so now you are breaking them

maybe its time to stop relying on bugs ¯\\_(ツ)_/¯

**Comment by ghost** [comment]
I guess you can still do that, and it can be pushed to 1.6 branch - because this version already breaks some stuff, see: https://wiki.multitheftauto.com/wiki/Changes_in_1.6
obraz

**Comment by botder** [comment]
I think it's too late to push this with 1.6, maybe next time.

**Comment by Fernando-A-Rocha** [comment]
1.6.1 ?

**Comment by TracerDS** [comment]
> 1.6.1 ?

It was actually ready for 1.6 but this PR didnt get enough attention 😢

**Comment by Fernando-A-Rocha** [comment]
> > 1.6.1 ?
> 
> It was actually ready for 1.6 but this PR didnt get enough attention 😢

It's never too late!

**Comment by Fernando-A-Rocha** [comment]
Marge, or put this in wiki breaking changes? Idk the procedure

**Comment by TracerDS** [comment]
Im not interested in advancing this PR further anymore.
If someone wants to refresh it, feel free to do so.

**Pull request closed without merging**
