### PR TITLE
Update unrar from 5.71 to 5.91

### PR DESCRIPTION
**Pull request by patrikjuvonen**
## Summary
- Update UnRAR  from 5.71 to 5.91
- Changelogs at https://www.rarlab.com/rarnew.htm
- Affects our installer/updater as far as I know, and these updates should bring stability and performance improvements so probably speeds up the process slightly...
- Versions: 5.80, 5.90, 5.91

## Validation
To help validate the integrity of the update I have created the following bash script that diffs between my PR branch and the official package provided from the [WinRAR extras page ("UnRAR source")](https://www.rarlab.com/rar_add.htm).
```bash
#!/bin/bash

UNRAR_UPDATE_VERSION=5.91
UNRAR_PATH_NAME=unrar-$UNRAR_UPDATE_VERSION

GIT_REPO_BRANCH=vendor/unrar-$UNRAR_UPDATE_VERSION
GIT_REPO_URL=https://github.com/patrikjuvonen/mtasa-blue.git
GIT_REPO_UNRAR_PATH=vendor/unrar/

echo 1. Download and extract $UNRAR_PATH_NAME...
curl -L https://www.rarlab.com/rar/unrarsrc-5.9.4.tar.gz | tar -xz
# Not sure why they named the archive 5.9.4 but that's the one...

echo 2. Fetch and checkout the vendor update branch $GIT_REPO_BRANCH from $GIT_REPO_URL...
git fetch $GIT_REPO_URL $GIT_REPO_BRANCH:$GIT_REPO_BRANCH
git checkout $GIT_REPO_BRANCH

echo 3. Start checking integrity...
diff -r --strip-trailing-cr $GIT_REPO_UNRAR_PATH unrar

echo 4. Completed.
exec $SHELL
```
- [Download validation script (fetch and checkout on existing clone) (.txt)](https://github.com/multitheftauto/mtasa-blue/files/5052287/validate-mtasa-blue-1606-v1-noclone.txt)
- [Download validation script (fresh clone) (.txt)](https://github.com/multitheftauto/mtasa-blue/files/5052206/validate-mtasa-blue-1606-v1-clone.txt)

## Past unrar updates in MTA
| Date | From | To | Link |
| :--- | :--- | :--- | :--- |
| May 2019 | 5.21 | 5.71 (current) | #269 |
| July 2015 | 4.20.3 | 5.21 | ae92d93cd9d81b73424782c888df6290d270ab33 |
| June 2012 | - | 4.20.3 | 521427daa123e93aba1aff68588ca80f610f3279 |

### Version 5.91

1. Dialogs are centered inside of WinRAR window similarly to WinRAR 5.80
      and not inside of entire screen as in WinRAR 5.90.

   2. When editing an archived file with external software, extra measures
      are taken to reduce the probability of interfering with editor
      and opening its temporary files while editor still may need them.
   
   3. "Version to extract" field in archive properties opened from
      Windows Explorer context menu provides the additional information
      about ZIP compression and encryption algorithms, such as LZMA or AES.
      This information was already available in WinRAR "Info" command,
      but missed in archive information accessible from Windows Explorer.

   4. "MS DOS" and "Unix" host OS types are recognized and included
      for LZH archives in "Info" command. Previously the host OS field
      was always "Unknown" for LZH archive format.

   5. Files created by external editor and matching "Settings/Viewer/
      Ignore modifications for" masks are never added to archive.
      Previously WinRAR still added them if some file not matching
      these masks was also created or modified.
   
   6. Bugs fixed:

      a) empty file names were displayed inside of some Unix LZH archives;

      b) WinRAR could not process more than 999 7z volumes in a single set;
      
      c) if user cancelled the user account control prompt after changing
         "Integrate WinRAR into shell" option, a new state of this option
         was displayed in "Settings" dialog, even though the actual state
         of shell integration was not modified;

      d) the main window size could be too small on the first run after
         clean install with no previous WinRAR version present;

      e) WinRAR could stop responding after editing an archived file
         with external software in Windows 10 version 2004.

### Version 5.90
   
   1. RAR compression speed is improved for CPUs with 16 and more cores.

   2. "Fastest" method (-m1 command line equivalent) typically achieves
      a higher compression ratio for highly compressible data types
      when creating RAR5 archives.

   3. Maximum number of utilized threads is increased from 32 to 64.
      Command line -mt<threads> switch accepts values from 1 to 64.

   4. "Multithreading" parameter on "General" page of WinRAR settings
      is replaced with "Threads" input field, where you can specify
      the desired number of CPU threads. It can take values from 1 to
      maximum number of available logical CPU units.

   5. WinRAR displays packed and unpacked folder sizes when browsing
      archive contents.
   
   6. "Total folders" field is added to list of archive parameters
      displayed by WinRAR "Info" command. Same field is added to
      "Archive" page in archive properties in Windows Explorer.

   7. Window including a progress bar and "Cancel" button is displayed
      if reading archive contents takes noticeable time.
      It can be useful for archive formats with slower access to contents,
      such as large TAR based archives like .tar.gz and tar.bz2.

   8. Archiving and extraction progress windows, also as progress windows
      for some other commands, can be resized.
         
   9. "Repair" performance for RAR5 archives with recovery record
      and without data shifts is improved. It deteriorated in WinRAR 5.80
      and is now restored to original level.

  10. Password prompt is not issued when performing recovery record based
      repair for RAR5 archives with encrypted file names.
      This command can be performed without providing a password.

  11. If folder for converted archives in "Convert archives" command
      does not exist, WinRAR attempts to create it. Previous versions
      failed to create converted archives in non-existent destination folder.

  12. Added extraction support for GZIP archives with optional header
      checksum field.
   
  13. Bugs fixed:

      a) "Repair" command could erroneously display "Recovery record is
         corrupt" message when processing an archive with valid recovery
         record. This message did not prevent further repair operation;

      b) if quick open information option was set to "Do not add" in default
         compression profile and this profile was loaded by some command
         or dialog, WinRAR ignored quick open information when browsing
         contents of RAR archives. For example, it happened after opening
         archiving or password dialogs;

      c) Ctrl+C "Copy" shortcut key did not work in archive comment window;

      d) if "Put each file to separate archive" and "Archives in subfolders"
         options were set, WinRAR ignored the destination path specified
         in archive name field.

### Version 5.80
   
   1. "Preserve source files last access time" option on "Time" page
      of archiving dialog permits to preserve the original last access time
      of archiving files.

   2. Command line -tsp switch can be used to preserve the original
      last access time of archiving files. It can be combined with other
      -ts switches, like: rar a -tsc -tsp arcname files

   3. It is allowed to combine several modifiers in the same -ts switch.
      For example, we can use -tscap instead -tsc -tsa -tsp.

   4. WinRAR can read default values of command line switches from rar.ini
      text file, which can be stored either in the same folder as WinRAR.exe
      or in %APPDATA%\WinRAR folder. This file includes strings in following
      format:

      switches=<any RAR switches separated by spaces>
      switches_<command>=<any RAR switches separated by spaces>

      First applies switches to all and second to individual commands.
      For example:

      switches=-m5 -s
      switches_x=-o+

      Most of switches specified in rar.ini are used only in the command line
      mode. Some switches can be applicable both in shell and in command line
      modes. Previously this rar.ini format was supported only by console RAR.

   5. Command line -agf<default_format> switch specifies the default format
      string for -ag switch. It has a practical value only if placed to
      rar.ini configuration file or to RAR environment variable.
      For example, if we set RAR environment variable to -agfYYYY-MMM-DD,
      we can use -ag without a parameter with YYYY-MMM-DD format string
      assumed.

   6. Switches -ed and -e+d can be used in archive processing commands
      for any combination of RAR and archive operating systems.
      In older versions RAR for Windows could not use them for Unix RAR
      archives also as RAR for Unix for Windows RAR archives.

   7. Previously "Test" command failed to check integrity of archived NTFS
      alternate data streams and issued "Unknown data header format" warning
      if size of such stream exceeded 16 MB. This limitation is removed now.

   8. Archiving speed for large NTFS alternate data streams on multi-core
      CPUs is increased.
   
   9. "Find" command:

      a) when extracting encrypted files directly from "Search results"
         dialog, password prompt was issued for every found file
         even if all files belonged to same archive.

         Now password is requested only once per archive;

      b) Ctrl+A hotkey selects all files in "Search results".

  10. Archive comment window:

      a) previous versions did not allow to use Ctrl+W shortcut to close
         WinRAR when comment window had keyboard focus. Now Ctrl+W works
         also from comment window;

      b) mouse wheel is supported also for comments with ANSI Escape sequences;
      
      c) for some lenghty comments with ANSI Escape sequences last line
         of comment was visible only partially even after scrolling up to
         bottom. It is displayed comletely now.

  11. Maximum path length for files in 7z archives is increased up to
      2048 characters. While such lengthy paths were already supported
      for RAR and ZIP formats, previous versions limited the path length
      to 260 characters for 7z archives.

  12. If archive or file name is too lengthy to fit to archiving
      or extraction progress window, it is truncated. Previously such names
      were truncated at the end, making the file extension invisible.
      This version truncates them removing the path component and symbols
      in the middle, but preserving beginning of file name and file extension.

  13. If files selected for archiving differ only by extension,
      a proposed archive name is based on their name part.
      For example, archiving dialog will propose Readme.rar if we selected
      Readme.txt and Readme.doc.

      Previous versions always generated the archive name based on parent
      folder name for several selected files.

  14. "Symlink" and "Hardlink" is diplayed in "Type" column for symlink
      and hardlink records in .tar archives. Previous versions displayed
      a proper type for such records only in .rar archives.
         
  15. Copying and pasting files from large archives could fail if
      extraction took a lot of time. This version can paste files from
      such archives as well, but we have to start extraction already on
      "Copy" command and not on "Paste" to achieve this.
   
  16. Similarly to RAR5 volumes, recovery volumes in RAR4 format use
      the same width of volume number field as corresponding RAR volumes.
      While previously WinRAR could create arc.part01.rar and arc.part1.rev
      in RAR4 format, now both types of volumes will use "part01".

  17. "Set font..." button in "Settings/File list" also changes the folder
      tree panel font. Previously it changed only the file list font.

  18. "Find files" and command line mode "i" commands:

      a) if "Use all tables" option or "t" modifer of "i" command are used,
         additionally to already supported ANSI, OEM and UTF-16 encodings
         WinRAR will search the specified string in UTF-8 files as well;
      
      b) better support for Unicode text strings;

      c) better performance, especially for case insensitive search;

      d) hexadecimal search output includes both text and hexadecimal
         representation of found matches.

  19. File and total progress bar is displayed when unpacking
      tar.bz2, tar.gz, tar.lz, tar.xz, tar.z archives.
      
      Previously only the total progress was displayed properly for tar.bz2,
      tar.gz and tar.z. Neither file nor total progress was displayed
      for tar.lz and tar.xz.

  20. "File list/Files/Exact sizes" option also changes the file size format
      in WinRAR status bar.
   
  21. Bugs fixed:

      a) if non-existent path is specified in archive name in archiving
         dialog, WinRAR proposes to create such path. Previous versions
         could create such path in WinRAR start-up folder instead of
         currently displayed folder;

      b) WinRAR could crash when adding the recovery record in RAR5 format
         on CPUs not supporting CPUID EAX=7 command and returning random
         data in response. These are some CPUs from early 2000s;

      c) WinRAR failed to create archives after dragging files with
         right mouse button in Windows shell, dropping them to another folder,
         selecting "Add to archive..." in context menu and enabling
         "Put each file to separate archive" option;

      d) "winrar r *.zip" command repaired only the first ZIP archive
         in the set if all archives had numeric names like 1.zip, 2.zip
         and signatures in the beginning of archives were missing;

      e) previous WinRAR version failed to unpack folder records
         in archives created by RAR 1.50;
      
      f) in rare cases WinRAR failed to extract and reported an error
         for valid .gz archives produced by some compression optimization
         tools;

      g) progress bar in tray icon never reached 100% in high DPI mode;

      h) creation and last access time was not displayed for archived folders
         if folder records were stored in archive after folder contents;

      i) "Skip encrypted archives" option in "Convert archives" command
         did not work for 7-Zip archives with headers encryption.

### CODE REVIEW

**Comment by qaisjp** [comment]
Please can you update your script to not require a brand new clone? My internet is too slow to clone the repo even when `--depth 1`.

It should be possible to fetch right into a branch: `git fetch https://github.com/patrikjuvonen/mtasa-blue remoteBranchName:localBranchName`

**Comment by patrikjuvonen** [comment]
> Please can you update your script to not require a brand new clone? My internet is too slow to clone the repo even when `--depth 1`.
> 
> It should be possible to fetch right into a branch: `git fetch https://github.com/patrikjuvonen/mtasa-blue remoteBranchName:localBranchName`

Thanks @qaisjp! I've updated the validation script here and my other open PRs too.

**Comment by qaisjp** [comment]
Thank you!!!

**Review by Dutchman101 — APPROVED** [review]
I suggest we merge this soon, so it can get atleast 2 weeks of testing while we work through #1645's checkklist, and then be included in the release of 1.5.8

**Review by ghost — APPROVED** [review]

**Pull request merged**
