### PR TITLE
Update credits

### PR DESCRIPTION
**Pull request by patrikjuvonen**
This update is preliminary and is subject to change. We will merge these changes in the next release.

These are still part of the 1.6.0 release. Addendum to #2846.

## Summary
- Update credits

### New Patch Contributors
- androksi (@androksi)
- Efe "efex" Batır (@efexc)
- Mvrat (@muratdogdas)
- Tracer (@TracerDS)
- vyn666 (@vyn666)

Are you missing from credits, or wish to update your existing entry? Please comment in this pull request with your preferred name.

Thank you all for your contributions!

### CODE REVIEW

**Comment by TracerDS** [comment]
I'd like to have just Tracer, thank you ❤️

**Comment by muratdogdas** [comment]
Can you change mine to my ingame nick "Mvrat"?

**Comment by efexc** [comment]
Can you change mine name to Efe "efex" Batır please. Greetings :)

**Comment by theSarrum** [comment]
Please rename `theSarrum` to `Sarrum`.

**Comment by vyn666** [comment]
Can you change `vyn666` to `czahor` please?

**Comment by vyn666** [comment]
Please rename `vyn666` to `skyee`

**Pull request merged**
