### PR TITLE
Add "randomfoliage" special property

### PR DESCRIPTION
**Pull request by ZReC**
Enable/Disable random foliage generation.

BEFORE:
https://drive.google.com/open?id=0BxjQi6_IK2doWjJEaWY3Sm42QW8

AFTER:
https://drive.google.com/open?id=0BxjQi6_IK2doY2xFRzh5aGpXZTA

Is better that > https://bugs.mtasa.com/view.php?id=7657#c24546

### CODE REVIEW

**Comment by ZReC** [comment]
I have researched how the foliage generation works, now, in addition to deactivating it, it eliminates waste.

**Comment by qaisjp** [comment]
Please add to `setWorldSpecialPropertyEnabled`

**Comment by jushar** [comment]
Don't worry about the whitespace changes in my merge commit. https://github.com/multitheftauto/mtasa-blue/pull/118/files?w=1 hides those changes.

The patch is good. However, its purpose collides a bit with `CSettingsSA::SetGrassEnabled` (which can be set in the video settings menu) as it also enables/disables grass. I'm fine with that, but someone else should approve it as well before merging it.

**Review by jushar — APPROVED** [review]

**Comment by qaisjp** [comment]
Is all random foliage just grass, or is grass a subset of random foliage?

**Comment by jushar** [comment]
It's a subset (cactuses are another example).

**Comment by ccw808** [comment]
I think this is ok because grass is part of GTA's FX quality settings, so should be user changeable.
Disabling cacti and rocks via scripting allows ground models to be used in different ways by mappers.

**Review by ccw808 — APPROVED** [review]

**Review by qaisjp — APPROVED** [review]

**Comment by ZReC** [comment]
Well, thanks for considering these requests, I hope to be able to contribute more to this pleasant community!

**Pull request merged**
