### PR TITLE
Add event "OnResourceStateChange"

### PR DESCRIPTION
**Pull request by TracerDS**
#3305

Some might say this event is pointless. But it might be a good alternative for `onResourceLoadStateChange`.
It will also help resources that monitor changing resources. Connecting that event with tables and other data would be easier than tracking 3 separate events.

### CODE REVIEW

**Comment by znvjder** [comment]
I'm in favor of accepting this, but removing the `onResourceLoadStateChange` event. It's entirely pointless and unnecessary.

**Comment by TracerDS** [comment]
> I'm in favor of accepting this, but removing the `onResourceLoadStateChange` event. It's entirely pointless and unnecessary.

For backwards compatibility its better to leave it for now and deprecate it when this PR gets merged

**Review by ghost — APPROVED** [review]
LGTM :shipit:

**Review by Lpsd — APPROVED** [review]
LGTM. Please add the relevant wiki page once the nightly build has been created, following the "new feature" format ([example](https://wiki.multitheftauto.com/wiki/OnPlayerProjectileCreation))

**Pull request merged**
