### PR TITLE
Add ability to change internal vehicle names - SetVehicleName

### PR DESCRIPTION
**Pull request by TracerDS**
This is my attempt at making a possibility to change internal vehicle name.
That way you can either replace vehicle name or add a new name for custom vehicles

### CODE REVIEW

**Comment by Dutchman101** [comment]
This would be a really cool feature, please clarify if it's really still a draft (you have more changes planned?) or when it's ready for review

**Comment by TracerDS** [comment]
> This would be a really cool feature, please clarify if it's really still a draft (you have more changes planned?) or when it's ready for review

Right now its still a draft. I want to be able to replace vehicle names by id too instead of only replacing individual vehicle name.

**Comment by ghost** [comment]
Hello @TracerDS, are you still working with this pr?

**Comment by TracerDS** [comment]
> Hello @TracerDS, are you still working with this pr?

I have some issues with instances within gta and mta that basically hold this PR in one place. Check https://discord.com/channels/801330706252038164/801411628600000522/1281674962352079012

**Comment by TracerDS** [comment]
Im not interested in advancing this PR further anymore.
If someone wants to refresh it, feel free to do so.

**Pull request closed without merging**
