### PR TITLE
Updated main menu's Arabic language pictures

### PR DESCRIPTION
**Pull request by Haxardous**
- fixed their positioning & scale
- redone the translation

### CODE REVIEW

**Comment by qaisjp** [comment]
Please submit on https://translate.mtasa.com instead

Thank you!

**Comment by qaisjp** [comment]
Or actually we can still use this PR, it just needs submitting there _as well_! Just so that pootle is also up to date.

**Comment by Haxardous** [comment]
all images on imgur // https://imgur.com/a/LcqC5S6 
added to translate.mtasa.com // https://translate.mtasa.com/ar/mainmenu/translate.html

**Comment by qaisjp** [comment]
you mentioned in pm that you ran it through zoplinpng

is the increase in size for Shared/data/MTA San Andreas/MTA/locale/ar/menu_disconnect.png and Shared/data/MTA San Andreas/MTA/locale/ar/menu_browse_servers.png intentional?

**Comment by Dutchman101** [comment]
> you mentioned in pm that you ran it through zoplinpng
> 
> is the increase in size for Shared/data/MTA San Andreas/MTA/locale/ar/menu_disconnect.png and Shared/data/MTA San Andreas/MTA/locale/ar/menu_disconnect.png intentional?

I don't see any increase in filesize, only a decrease (as intended), but @Haxardous told me he intended to resize the image resolution in order to..

> * fix their positioning & scale

Note to @qaisjp: you wrote the same file name twice in your post above

**Comment by qaisjp** [comment]
> Note to @qaisjp: you wrote the same file name twice in your post above

fixed



> I don't see any increase in filesize

image

**Comment by Dutchman101** [comment]
> > Note to @qaisjp: you wrote the same file name twice in your post above
> 
> fixed
> 
> > I don't see any increase in filesize
> 
> image

oh, I was mistaken as originally he demonstrated his improved images of which for example menu_disconnect was 6kb, which again got reduced to 2kb after running it through Zopflipng. But the original in MTA is 572 bytes.

@Haxardous why don't you show the effect of your edits (like resize), so we can see if your resolution change is worth it for the visuals?

**Comment by qaisjp** [comment]
it's probably fine, i just wanted to know if it's intentional

**Comment by Dutchman101** [comment]
> it's probably fine, i just wanted to know if it's intentional

ah, yes, since i discussed it with him i know it was intentional, since it happened in the process of improving the menu images..

anyways, here's a comparison (ingame screenshots) of appearance..

old: [https://i.imgur.com/kaPc3aR.png](https://i.imgur.com/kaPc3aR.png)

new: [https://i.imgur.com/qUPIYVX.png](https://i.imgur.com/qUPIYVX.png)

i personally think it looks much better.. maybe we need to get a second-opinion on the new translation quality (from other arabic speakers) as well

**Comment by qaisjp** [comment]
Is your name @haxardous?

**Comment by Dutchman101** [comment]
> Is your name @Haxardous?

we collaborated in the graphic design, no need to act like this @qaisjp

**Comment by qaisjp** [comment]
in that case it's fit to merge, but it's better to just let him reply since he has a voice too

**Comment by Dutchman101** [comment]
> in that case it's fit to merge, but it's better to just let him reply since he has a voice too

providing answers because i know them doesn't equal not letting him reply (he is free to do so), we are talking throughout the process of this PR, it's better not to make assumptions

anyways, nice

**Comment by qaisjp** [comment]
> we are talking throughout the process of this PR

if the conversation didn't happen on the MTA discord, the conversation never happened

**Comment by Haxardous** [comment]
I modified it's overall resolution for an accurate scaling (didn't changed the resolution pixels's width or height)

to make it more clear:
https://i.imgur.com/rG1zIdI.gif

**Comment by Haxardous** [comment]
Sorry for late response, I was editing this in photoshop to make it more clear, my apologize.

**Comment by Dutchman101** [comment]
> > we are talking throughout the process of this PR
> 
> if the conversation didn't happen on the MTA discord, the conversation never happened

collaboration (in this case, helping someone with their PR) doesn't neccesarily have to be in public channels, if i dont want to credit myself on this contribution (i really didn't need to, as most work is from @Haxardous) - saying I am informed enough to comment what I know because of a collaboration should be sufficient for you not to do what you did - then it doesn't mean you incorrectly assuming things should break the peace/be rude in here.. that's all I was trying to say

**Comment by qaisjp** [comment]
>   you incorrectly assuming things should break the peace/be rude in here.. that's all I was trying to say

OK, I apologise for the rudeness [here](https://github.com/multitheftauto/mtasa-blue/pull/1050#issuecomment-520250476).


> collaboration doesn't necessarily have to be in public channels

No, **collaboration should be in public channels**. I have repeated this several times, yet everyone still does it — collaboration and quality overall (project-wide) is worsened when it happens in PM.

If someone contacts you in PM, and it's non-trivial + not security related, please try to encourage them to ask in #development instead. (This goes for everyone.)

**Comment by qaisjp** [comment]
> (This goes for everyone.)

Obviously, I am perfectly happy to debate this. It's just that every time I say it, nobody objects

**Comment by Dutchman101** [comment]
> OK, I apologise for the rudeness [here](https://github.com/multitheftauto/mtasa-blue/pull/1050#issuecomment-520250476).

alright, and i also have to admit that im mostly opposing this because we all know there's a problem between me and you, and I quickly believe it causes things like this

> No, **collaboration should be in public channels**. I have repeated this several times, yet everyone still does it — collaboration and quality overall (project-wide) is worsened when it happens in PM.
> 
> If someone contacts you in PM, and it's non-trivial + not security related, please try to encourage them to ask in #development instead. (This goes for everyone.)

To be exact, there's no project guidelines that state you cannot help someone get small details in their PR ready, and it should be obvious this is also less relevant when it comes to non-changes (like this optimization of *his work* doesn't change anything that is perceived, and it's not code)
What happens now seems to just be shoving off the problem, (that was, you making assumptions that set the tone)..  or making something else seem to be the problem.. at first I just expressed some criticism based on your post.

But let's leave it here

**Pull request merged**
