### PR TITLE
Update credits

### PR DESCRIPTION
**Pull request by patrikjuvonen**
This update is preliminary and is subject to change. We will merge these changes in the next release.

## Summary
- Update credits
- Sort credits in alphabetical order as supposed to

### Promotions to Contributors
- colistro123 (@colistro123)
- Pirulax (@Pirulax)
- TheNormalnij (@TheNormalnij)

### New Contributors
- SugarD-x (@SugarD-x)

### New Patch Contributors
- Allerek (@Allerek)
- cleopatra (@cleoppa)
- delinx (@delinx)
- drop-club (@drop-club)
- fastman92 (@fastman92)
- iDannz (@iDannz1)
- JeViCo (@JeViCo)
- NanoBob (@NanoBob)
- PauloKim1246 (@PauloKim1246)
- pieT (@Pieter-Dewachter)
- se16n (@se16n)
- STR6 (@STR6)

### New Special Thanks
- leetIbrahim (bug bounties)
- Rocketbunny

Are you missing from credits, or wish to update your existing entry? Please comment in this pull request with your preferred name.

Thank you all for your contributions!

### CODE REVIEW

**Comment by Lpsd** [comment]
Please update from `LopSided` to `Lpsd`

**Comment by FileEX** [comment]
Please update from ```FileEX``` to ```Marcin "FileEX" Pawlicki```

**Comment by fresholia** [comment]
Please update from `cleopatra` to `Enes "cleopatra" Akıllıok`

**Comment by CrosRoad95** [comment]
change mine to `Sebastian "CrosRoad95" Jura`

**Comment by Unde-R** [comment]
also mine from `Unde-R` to `Amine "UndR" Bidah`

**Comment by xLive** [comment]
If you don't mind update mine to `Nawaf "xLive" Alqarni` please.

**Comment by Pirulax** [comment]
Since everyone is changing their names, update mine to `Chris 'Pirulax' Cockwanger`.
<details>
<summary>Spoiler</summary>
Jokes aside, `Patrik 'Pirulax' Jankovics-Szmolenicki`
Edit: Discord ruined my plan ffs
</details>

**Comment by Pieter-Dewachter** [comment]
Would it be possible to change my name from `Pieter Dewachter` to `Pieter "pieT" Dewachter`?

**Pull request merged**
