### PR TITLE
Fixed isGarageOpen / setGarageOpen / GetGarage* returning true while disabled / invalid

### LINKED ISSUE #545: Certain garage ID's do not open
**Describe the bug**
Garage ID's 1 (lspd), 26 (sfpd) and 29(lvpd) do not open.

tested with runcode and got `setGarageOpen(1, false)` returns `true`

But still garage is closed.

Tested server side, but tested client side and same problem occurred.

**To reproduce**
tested code with ID 19 (doherty pay and spray) and worked fine

test code:
```lua
function gfunc(playersource, commandName, garageID)
	if (not isGarageOpen(tonumber(garageID))) then
		-- open the door
		setGarageOpen( tonumber(garageID), true)
	else
		setGarageOpen ( tonumber(garageID), false )
	end
end
addCommandHandler("garage", gfunc, false)
```
**Expected behaviour**
Garage door(s) to open.

**Additional context**
The same seems to be the case with garage ID 32, the one near Royal Casino.

From https://bugs.mtasa.com/view.php?id=3935

### PR DESCRIPTION
**Pull request by ghost**
This PR fixes https://github.com/multitheftauto/mtasa-blue/issues/545

- Luxy.c

### CODE REVIEW

**Review by qaisjp — CHANGES_REQUESTED** [review]
Thank you for the pull request. Please refactor that `for` loop into `bool CGaragesSA::IsDisabledGarage(unsigned char ucGarageID)`

**Comment by ghost** [comment]
Will do in about 1h.

Luxy.

**Comment by ghost** [comment]
Since the size of the array remains the same, you can use std::array along with C++ loop for the container, like ```for (const auto &dwGarageID : iDisabledGarages)```.

**Comment by botder** [comment]
This PR doesn't fix #545. It only prevents modification of disabled garages.

**Pull request closed without merging**
