### PR TITLE
`xmlLoadFile` print error

### PR DESCRIPTION
**Pull request by CrosRoad95**
xmlLoadFile print error in console when somethink wrong with xml
Now you dont know what's wrong with your file, now you know!

example script lua
```lua
a=xmlLoadFile("wrong.xml")
iprint(a)
```
wrong.xml
```xml
<xml>
  asdf
  <b> </b>

  <a> </b>
</xml>
```
e5vrmfwbsukven-zyxksoq

### CODE REVIEW

**Comment by 4O4** [comment]
Someone give that man a cookie!

**Comment by AlexTMjugador** [comment]
The idea behind this PR seems great. However, I'm a little concerned about backwards compatibility. For example, this code snippet would initialize a table with two fields instead of one, which can translate in unexpected behaviour of the script:

`myTable = { xmlLoadFile("file.xml") }`

Although I think that most scripters only take into account the first return value currently, I wouldn't take that for granted. IMHO, a 100% backward-compatible solution would be definitely better. [This PR](https://github.com/multitheftauto/mtasa-blue/pull/150) faced a similar problem which was solved by modifying the behaviour of the function according to min_mta_version. Maybe this could be improved the same way?

**Comment by Dezash** [comment]
Better yet, instead of adding an extra field, just use LogWarning

**Comment by AlexTMjugador** [comment]
@Dezash , that sounds nice to me 👍 . engineLoadDFF does that too when trying to load a bad DFF, if I remember correctly.

**Comment by CrosRoad95** [comment]
i change that print error in debugscript insted of return argument.

**Review by qaisjp — APPROVED** [review]

**Comment by CrosRoad95** [comment]
[xmlErrorTest.zip](https://github.com/multitheftauto/mtasa-blue/files/1506808/xmlErrorTest.zip)
Example resource which test errors.
7npfzjlxqlynwv7w8vib_g

**Comment by ccw808** [comment]
Thanks!

**Pull request merged**
