### PR TITLE
Update copyright year(s)

### PR DESCRIPTION
**Pull request by fresholia**
Screenshot_1

Updated copyright year validity in many places, including photo

### CODE REVIEW

**Comment by patrikjuvonen** [comment]
At least the .po file changes should be reverted as they are commented out and do not affect the mod.

As for header files perhaps we could overall revamp that string to not be year dependent perhaps. Also there are Rockstar North copyright strings that have an old year.

Let's think about this.

**Review by patrikjuvonen — CHANGES_REQUESTED** [review]
At least the .po file changes should be reverted as they are commented out and do not affect the mod.

As for header files perhaps we could overall revamp that string to not be year dependent perhaps. Also there are Rockstar North copyright strings that have an old year.

Let's think about this.

**Comment by patrikjuvonen** [comment]
Additionally I asked ccw to update the copyright year on build server and that is now done, so the exe should have right year.

**Comment by fresholia** [comment]
Instead of replacing all of the header files in bulk, the person who last updated that file can write the current MTA version & year.

**Comment by Disinterpreter** [comment]
https://www.quora.com/If-you-update-a-site-does-the-copyright-year-change
https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated

Is it really need?

**Comment by patrikjuvonen** [comment]
Yeah general rule is to update latest year when the file is updated, which is not the case here.

**Comment by patrikjuvonen** [comment]
Thanks for the pull request. This seems to not be necessary. Let's try to keep an eye on those years if code changes within a header file in the future though.

**Pull request closed without merging**
